app/contexts.go
app/test/login.go
app/test/version.go
jenkins/linux/Dockerfile
jenkins/linux/Makefile
jenkins/linux/build.sh
tool/alm-cli/main.go

This adds the ability for jenkins (or any other user) to build the software in an (semi-)reproducible environment (docker container) by running `cd jenkins/linux/ && make`.
Currently this fails with this reason:
```
go-bindata-assetfs -debug assets/...
godep get
go build -ldflags "-X main.Commit=`git rev-parse HEAD` -X main.BuildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'`" -o alm
cd tool/alm-cli && go build -o ../../alm-cli
./main.go:27: c.Timeout undefined (type *"github.com/almighty/almighty-core/client".Client has no field or method Timeout)
Makefile:32: recipe for target 'alm-cli' failed
make: *** [alm-cli] Error 2
+ echo 'SIGNAL received. Will clean up.'
SIGNAL received. Will clean up.
+ almighty_clean_up
+ chown -R kkleine /build-dir
Makefile:76: recipe for target 'build' failed
make: *** …
```

Jenkins scripts

---

Makefile

When finding all source and design *.go files, make sure the vendor subdirectory is ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/26)

Ignore source files in vendor subdir

---

Makefile

Fixes this error, when running in Cygwin:
````
$ find / -name "*.go" -not -path /usr/*
find: paths must precede expression: /usr/include
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
````
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/27)

Fix Makefile find command

---

Makefile
Makefile.lnx
Makefile.win
jenkins/windows/README.md
jenkins/windows/download-file.ps1
jenkins/windows/extract-zip.ps1
jenkins/windows/git.inf
jenkins/windows/make.bat
jenkins/windows/mercurial.inf

This change contains a make.bat file in jenkins/windows/ that
can be used to prepare a Windows machine to build and test
this project.
We need these tools to build on Windows:
* cygwin
* go
* glide
* git
* mercurial
The `make.bat` file can install and configure those tools locally
without requiring any user interaction.
I decided to write this file to be able to have a Jenkins job
on a Windows machine that knows nothing about any of the required
tools. This way we can modify our requirement in code.
The only thing a Windows host needs is the terminal `cmd.exe`.
`make.bat` can be seen like a Makefile on Linux. There are many targets
that can be executed. Among those targets is one called `help` that
tells more about what is available exactly.
A jenkins job can be configured to run …

Build script for Windows (jenkins ready)

---

Makefile
version_test.go
workitem_test.go

Tests marked with // +build integration will only run when 'make test-integration' is called.
Tests marked with // +build !integration will not run when 'make test-integration' is called.
Makefile:
* make test
Runs all non integraton tests
* make test-integration
Runs all integration tests. Requires a DB
fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/42)

Add seperation between unit and integration test using build tags

---

Makefile

Previously it was simply starting postgres instance and blocking on this step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/58)

Runs docker container in the background so make dev can start ALM server

---

Makefile
jenkins/linux/Makefile
jenkins/linux/build.sh

Previously I determined the username and group ID of the user that started the jenkins build script and created a user with the exact same ID inside the container.
This is not needed due to the "-u" switch on the "docker run" command.
This change greatly simplifies the build on a linux machine.
The build now runs in source and no longer out-of-source.
This greatly simplifies the way we build on a jenkins machine in terms of user-management and archiving artifacts that were built inside a container with proper permissions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/51)

Re-use user:group of caller in jenkins automatically

---

.gitignore
.make/Makefile.lnx
.make/Makefile.win
.make/test.mk
Makefile
glide.lock
glide.yaml

Testing has become a rather big and interconnected topic and that's why it
has arrived in it's own file.
We have to types of tests available:
1. unit tests and
2. integration tests.
While the unit tests can be executed fairly simply be running `go test`, the
integration tests have a little bit more setup going on. That's why they are
split up in two tests.
If you want to run the unit tests, type
$ make test-unit
To run the integration tests, type
$ make test-integration
To run both tests, type
$ make test-all
To show unit test coverage in a terminal, type
$ make show-coverage-unit
To show unit test coverage in a browser, type
$ make show-coverage-unit-html
If you replace the "unit" with "integration" you get the same for integration
tests.
We execute tests with coverage output by default. …

Fix #62: Show test coverage with makefile

---

models/field_definition.go

As part of #79 the datatype of Kind was changed from Byte to String. That broke the marshalling format string where we were using %d
Changing the format string to have "%s" fixed the issue. Tested by running the test inside models/
Fixes #113
Signed-off-by: Shoubhik <shoubhik@dhcp35-156.lab.eng.blr.redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/114)

updated the datatype during marshalling from Byte to String

---

main.go
models/gorm_repository.go
workitem_test.go

Since we would be continuing with a flat model package
the work item repository constructor is renamed to something more
specific that was present ( NewRepository )
Fixes #119
How:
Updated the model constructor and the corresponding test. 
Local build was a success.
Signed-off-by: Shoubhik <shoubhik@dhcp35-156.lab.eng.blr.redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/124)

Renamed models.NewRepository to models.NewWorkItemRepository

---

design/resources.go
design/user_types.go
workitem.go
workitem_test.go

The WorkItem to be updated should be referred by its ID in the URL as a api/workitem/:ID and the code should not be reading it from the payload since ID not an editable field. 
~~The same applies for the `version` attribute in the payload. The version need not be passed as part of the payload while updating the workitem.~~
This changed required a change in the goa design code. 
The `make` task autogenerates sources inside the app/ dir
Fixes #95 #47 
Signed-off-by: Shoubhik <shoubhik@dhcp35-156.lab.eng.blr.redhat.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/125)

WorkItem Update should use the ID passed in URL

---

glide.lock
glide.yaml
models/fieldtype_test.go
models/list_type.go
models/simple_type.go

Simple table driven testing of `ConvertToModel` for SimpleType, EnumType, ListType done.
Testing is never complete :sweat_smile:  so removing label WIP.
We should be adding more and more tests on the go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/115)

Table driven tests for SimpleType, EnumType and ListType.

---

design/api.go

The UI will use Content-Type and might use X-Request-Id
when communicating with the backend. These headers should
be allowed to pass the CORS Policy.
@joshuawilson This should fix your CORS issue with 'create workitem'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/146)

Add Content-Type and X-Request-Id as allowed CORS headers

---

.make/docker.mk

Docker-based build doesn't work with SELinux enabled:
sudo make docker-start
sudo make docker-deps
result:
docker exec -t -i "almighty-core-local-build" make deps
make: stat: Makefile: Permission denied
make: *** No rule to make target `deps'.  Stop.
make: *** [docker-deps] Error 2
See [Docker docs](https://docs.docker.com/engine/tutorials/dockervolumes/#/volume-labels) for explanation of change made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/156)

docker-start target configured to relabel volume

---

Dockerfile.deploy
main.go

And output the user and group when alm starts for verification reasons.
Fixes #167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/168)

Run alm deploy container under a non-root user/group

---

models/lifecycle.go
models/workitem.go
models/workitemtype.go
models/workitemtype_test.go

Fixes #158 
Add all fields from [`gorm.Model` ](http://jinzhu.me/gorm/models.html#gormmodel-struct) except the `ID` element to allow models (like `WorkItemType`) to specify their own primary key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/164)

Add created/updated/deleted times to DB models (Fixes #158)

---

main.go

We don't panic if the current user cannot be found but instead just print the error.
(This only happened in openshift.)
Fixes #172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/177)

Don't panic if the current user cannot be found

---

cico_run_tests.sh

This change sources interesting parts of the jenkins slave environment to the worker machine. 
This is a preparation for setting up an integration of an external coverage service, that might need some environment variables to be present in order to determine the CI type. Codecov.io is an example of such a service.
See almighty/almighty-jobs@e718d3aa96c1b933f269b138d39eab4dc6a881e7 to see how the jenkins-env file was created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/226)

Source interesting parts of jenkins slave env

---

README.adoc

taken from examples/workitemtype.adoc
Fixes #208 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/195)

Add help text in README for creation, retrieval, listing of WorkItemTypes

---

remoteworkitem/scheduler_test.go
workitem_test.go

My proposal is simple: Run tests `m.Run()` no matter what the state of the environment variable is: Each test is responsible to specify which resource is required.
This way we can have unit tests and integration tests in one package without modifying a lot of the code right now. There will be a time when we might have a better way to setup and tear down a database connection. @aslakknutsen and I talked about this already. But this is a short term solution for the problem I think.
Fixes #255

Run tests even if no DB conn was setup in TestMain

---

remoteworkitem/remoteworkitem.go
remoteworkitem/remoteworkitem_test.go

PR #111 implemented the importing of a remote work item into our system and saving it in a 'staging' table
named 'TrackerItem'.
PR #152 introduced the design of mapping remote work items to ALM work items.
This PR consolidated the type 'RemoteWorkItem' and 'TrackerItem' into a single type 'TrackerItem' to be used across the codebase. They essentially wrapped the same data points prior to this PR. The tests have been updated to reflect this consolidation.
Fixes #162 #262

Consolidated the remote work item type into using TrackerItem

---

cico_build_deploy.sh
cico_run_tests.sh

This should fix the problem with funky German Umlauts in the `ghprbActualCommitAuthor` variable.
Previously we extracte the `ghprbActualCommitAuthor` variable, but now we look for a `=` after the variable name and that should limit the selection of environment variables to just `ghprbActualCommit`.

fix umlaut issue

---

README.adoc

This is a fixup for #176 
I've assigned this to @tsmaeder and @baijum because you reviewed my original PR, thus, it should not be hard to argue what this change does.

Include default config in README instead of broken link

---

docker-compose.yml

The removal of -dbhost wasn't reflected in the docker-compose.yml file.
Thanks to @aslakknutsen for finding this.

Fixup for #176

---

configuration/configuration.go
main.go
remoteworkitem/scheduler_test.go
workitem_whitebox_test.go
workitemtype_blackbox_test.go

This makes the -config switch fully optional even if there's no
config.yaml at hand.

Make default of -config switch "" instead of "config.yaml"

---

Makefile

The first version we had caused problems on Windows systems: `$(PATH)`. This was problematic due to paths with whitespaces in them.
In my second approach I did this: `$$(PATH)`. The double `$$` was used to avoid a too early expansion of the `PATH` variable. Sadly this was also wrong and cause troubles (see [this mail thread](https://www.redhat.com/archives/almighty-public/2016-September/msg00219.html))
This time, the early expansion is correct: `$$PATH`.
Lot of text for such a small change ;)

Avoid too early expansion of $PATH variable

---

design/user_types.go
glide.lock
glide.yaml
tracker_test.go
trackerquery_test.go
workitem_blackbox_test.go
workitemtype_blackbox_test.go

fix #187 
How:
Generally we add examples for each attribute separate. But type of `fields` attribute is a hash made up of UserDefinedType `fieldDefinition` and hence adding separate example for `fields` was failing. After many attempts in many direction I found this simple solution that we can add `Whole Example` along with all Attributes. Plus point is that `ExtendedType` is optional and is not promoted for usage as of now hence that is skipped.
After updating goa to b1b4f4d827a3b63b05d978ca82305c45451103b3, all dependency tree was updated by glide
Hence changes made by goagen while generateing code inside 'app' directory. And we need to use `*AlternatePayload` in our tests.
Hence updated all failing tests.

Add realtime example for WorkItemType payload.

---

Makefile
glide.lock
glide.yaml

* Remove .PHONY dependency on 'internal' targets
* Split generate up into multiple non .PHONY targets
* Make generate a dependency of build/dev targets
* Add vendor target that controls call to glide install
* Make deps a user friendly v of vendor
* Make all binaries & generator targets a dep to vendor
TODO: Make non user called steps private?
TODO: call make generate on file change detection in fresh? Can't control the calls in fresh, maybe move to something like https://github.com/cespare/reflex ? 
Fixes #265

Allow make to control when generate needs to be called

---

README.adoc

Integration test asks for psql connection on 5432. If not available it fails, hence mentioned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/140)

Readme change 

---

migration/migration.go
models/workitem_repository.go
models/workitemtype_repository.go
models/workitemtype_repository_whitebox_test.go
remoteworkitem/remoteworkitem.go
remoteworkitem/scheduler.go
remoteworkitem/trackeritem_repository.go
remoteworkitem/trackeritem_repository_test.go

1. After the remote work item is persisted in the temporary table called 'TrackerItem'
2. Convert the remote item into a local work item.
3. Check if the work item exists. Use the remote_item_id in the json to check for existence of work item.
4. If present, update it, else, create a new one.
Fixes https://github.com/almighty/almighty-core/issues/170

Persistence of mapped remote work item

---

migration/migration.go
migration/sql-files/004-drop-tracker-query-id.sql

The `tracker_query_id` column is no more required

---

migration/migration.go
models/workitemtype.go
models/workitemtype_repository_whitebox_test.go
remoteworkitem/remoteworkitem.go
remoteworkitem/remoteworkitem_test.go
remoteworkitem/trackeritem_repository.go
remoteworkitem/trackeritem_repository_test.go
workitem_blackbox_test.go

Work item type names like "system.bug" were embedded as strings directly in the code. This has now been replaced with const names like models.SystemBug . The same has been done for work item type field names like system.title which is now being referred as models.SystemTitle everywhere in the code. A subset of these were present in remoteworkitem.go but has now been moved to models/workitemtype.go
Fixes #161

Moved inline strings of work item type fields to consts

---

account/identity.go
account/user.go
convert/equaler.go
convert/equaler_blackbox_test.go
gormsupport/lifecycle.go
gormsupport/lifecycle_blackbox_test.go
models/enum_type.go
models/enum_type_blackbox_test.go
models/field_definition.go
models/json_storage.go
models/list_type.go
models/list_type_blackbox_test.go
models/simple_type.go
models/simple_type_blackbox_test.go
models/workitem.go
models/workitem_blackbox_test.go
models/workitemtype.go
models/workitemtype_blackbox_test.go
remoteworkitem/tracker.go
remoteworkitem/trackeritem.go
remoteworkitem/trackerquery.go

This is ground work for upcoming PR which is about setting system.creator in creation of WI.
@tsmaeder @aslakknutsen Please review and merge if this is acceptable, as I needed this for upcoming PR.
Why:
Need to avoid cyclic imports and it is good to make packages if there is piece of work that can/should live in isolation.
What:
Moved Lifecycle to "gormsupport" new package.
Moved Equaler to "convert" new package.

Added new packages for Lifecycle and Equaler (solve cyclic import) 

---

design/resources.go
workitem_blackbox_test.go
workitemtype_blackbox_test.go

Securing WI and WIT APIs.
fixes #243 
**Why:**
We need to prevent creation/deletion/updation of work items by unknown/guest users.
User must login and then only should be able to take above actions.
**What:**
Security("jwt") added for WI create and WIT create/delete/update APIs. Added test cases for the same.
**How:**
Table Drive tests added for Create WIT and create/delete/update WIT api.
It Generates multiple invalid tokens and test negative scenarios.
Added JWT middleware by using app.UseJWTMiddleware so that middleware will be applicable as per design.
Tested with non-secured GET api also.

Securing WI and WIT APIs and related tests

---

glide.lock
glide.yaml
main.go

As per this document: http://go-database-sql.org/accessing.html
"the sql.DB object is designed to be long-lived"
The gorm.DB wraps sql.DB, so the above statement is still valid.
Since the ALM code is attempting to create new DB object, it's better
to close every time it fails to establish connection.

close broken DB object

---

README.adoc
examples/workitemtype.adoc

POST APIs now need to use Authorization Header, same is mentioned in the examples in the documentation.
Fixes #389

Update documentation after changes made in REST APIs.

---

glide.lock
glide.yaml

There's been a UUID issue that @aslakknutsen has fixed in his [PR](https://github.com/goadesign/goa/pull/841) in GOA: https://github.com/goadesign/goa/pull/841
This change makes sure we benefit of this change by using the v1 branch of GOA.

Use v1 branch of GOA

---

.make/test.mk

Fixes #285
Trying to improve cross package coverage and excluding certain folders from the tests.

Use gocovmerge and -coverpkg for each test profile

---

workitemtype.go

A work item type (WIT) is not identified by it's ID but its name, hence
the log message needed to be changed.

Fix log message for not found WIT

---

models/workitem_repository.go
models/workitemtype_repository.go
remoteworkitem/tracker_repository.go

Pass "Where" paramters as a varargs instead of array.
Fix for #418

Pass parameter array as varargs

---

design/api.go
design/media_types.go
design/resources.go
design/user_types.go

**To be clear upfront: I'm NOT removing the dot-imports simply because
there's some warning about good Go practices on imports!**
I found that no editor could autocomplete or jump to the definition of
any of the words in the modified files. Being sick of jumping to the
online reference of GOA, I decided to take the bumpy road and live with
a DSL that looks a little bit less readable than with the dot-import.
The benefit is, that we get auto-completion and can jump to the definition
of all the GOA symbols now. Plus, we are informed about all other
errors one can make while writing GOA design files.
With migration to JSON API ahead of us we're in desperate need of
control over all files in the design folder.
@tsmaeder @aslakknutsen I'd be happy if you can approve this! Please unassign …

Remove dot-imports of goa design and design/apidsl packages

---

models/workitem_repository.go
models/workitemtype.go

Why?
As we build micro-services or handle workitems in different packages, it becomes necessary to handle the conversion from models.workitem to app.workitem
What?
Changed the method needed into an exported method.
Fixes #405

Export function which converts workitem workitem to app.workitem

---

models/errors.go
models/errors_blackbox_test.go

Why:
All the exported error types in models/errors.go depend on models.simpleError type which is non-exported and therefore the exported error types are not usable unless invoked from the same package or if the errors.go is copied over the other specific package.
What:
Added method to access the non-exported methods.
This is an additional sub-task which was missed when https://github.com/almighty/almighty-core/commit/bf4f6bc40233a2311220e7266d078fb9b20d7699 when merged.
Fixes #309

Expose ConversionError type using exported method

---

README.adoc
account/user.go
application/repositories.go
login/service.go
main.go
models/workitem_repository.go
remoteworkitem/trackeritem_repository.go
test/login.go
test/workitemrepository.go
workitem.go
workitem_blackbox_test.go
workitem_whitebox_test.go

depends on #386 
Why:
We need to set correct value for WI creator field.
What:
Every WI has list of fields, out of which SystemCreator is to be filled by system only.
Logged in user's UUID in string format should go in as value of SystemCreator in corresponding fields slice.
How:
Added a middleware to fetch,locate and set uuid in the context. If not found (for non-secured APIs) it will set it as "guest user"- currently shown as empty UUID (all zeros).
Added new parameter to repository creator method of WI to accept creator in string form.
Did required changes in system and tests are modified.

Set creator value while creating WI.

---

models/errors.go
models/errors_blackbox_test.go

Why?: so that its usable from other packages.
What?: Added a exported method which returns the error type
fixes #444

Export NotFoundError and BadParameter error

---

search/search_repository.go
search_blackbox_test.go

Fixes #454 
- Trim prefix "http protocols"
- Escape ":"
- Trim trailing slashes

Fixes #454 (fix for searching on un-registered url:port)

---

models/errors.go
models/errors_blackbox_test.go
models/errors_whitebox_test.go
models/workitem_repository.go

This adds the possibility to specify an expected value for a bad parameter error.
When you create a `BadParameter` error using the `NewBadParameterError()` constructor function you call the `Expected()` method on the result to set an expected value:
```golang
models.NewBadParameterError(param, value).Expected(expectedValue)
```
The reason for this chaining approach is that sometimes you may not want to set an expected value.

Added BadParameter.Expected() function

---

models/workitem.go
models/workitem_blackbox_test.go

@kwk noticed that we are not comparing id's in models.WorkItem.Equals(). Since we are using equals to compare items for testing, including the ID field seems to be the right thing.

Include ID field in WorktItem.Equals()

---

design/media_types.go
migration/migration.go
models/workitemtype.go
models/workitemtype_repository.go

A new base type **system.planneritem** is created.
This base type has all common fields such as:
- system.remote_item_id
- system.title
- system.description
- system.state
- system.assignee
- system.creator
which are inherited via **extendedTypeName="system.planneritem"** by the default types when the types are created/updated:
- system.userstory
- system.valueproposition
- system.fundamental
- system.experience
- system.feature
- system.bug
Fixes #288
**TODO:**
- add some tests

Extract Common Fields in WIT's to Base Type

---

application/application.go
comment/comment.go
comment/comment_test.go
design/comments.go
gormapplication/application.go
main.go
migration/migration.go
migration/sql-files/010-comments.sql
test/db.go
work-item-comments.go
work-item-comments_test.go

Stores created-at, created-by and body.
Create comment (Secured):
POST /api/workitems/n/relationships/comments
List comments:
GET /api/workitems/n/relationships/comments
Related #348
Related #349

Add Comments to WorkItem API

---

design/resources.go
identity_blackbox_test.go

UI use API as a pre fetch list to resolve users, if the endpoint
is secured no users can be displayed when viewer is not authorized.
* Update test case to not delete the whole identities table during start
* Assume there can be more than test controlled identities in the DB

Remove security from GET /api/identities

---

errors/errors.go
errors/errors_blackbox_test.go
errors/errors_whitebox_test.go
jsonapi/error_handler.go
jsonapi/jsonapi_utility.go
migration/migration.go
models/undoable_wi_repo.go
models/work-item-link-category-repository.go
models/work-item-link-repository.go
models/work-item-link-type-repository.go
models/work-item-link-type.go
models/work-item-link.go
models/workitem2_repository.go
models/workitem_repository.go
models/workitemtype_repository.go
models/workitemtype_repository_blackbox_test.go
search.go
search/search_repository.go
work-item-link.go
workitem.2.go
workitem.go

This allows for packages to use errors without causing a cyclic import.
@aslakknutsen @tsmaeder please review! Thx.

Outsource errors from "models" package into its own "errors" package and use it.

---

models/workitem_repository.go
models/workitem_repository_blackbox_test.go

0 is handled in Gorm as a Zero value and it assumes no value is set,
and generate no WHERE clause.
e.g.
```
UPDATE "work_items" SET deleted_at='2016-12-07T05:05:11+01:00'  WHERE "work_items".deleted_at IS NUL
```
> Delete ALL workitems not allready deleted

Add special ID:0 handling to WorkItem Repository Delete|Save|Load

---

design/media_types.go
work-item-link-blackbox_test.go
work-item-link.go

Changes the "included" JSONAPI array for work item links to include an array of mixed values (in Goa: `d.Any`, in Go: `[]interface{}`). This allows us to include work items, work item types, work item link types, and work item link categories in the responses for CRUL operations.
When the UI fetches a link today, it only gets the source and target's work item ID. After that it has to make multiple additional requests to get the work item type or the source and the target. The idea of this PR is that UI doesn't have to do any more requests than necessary to get all the information of a link or an array of links in one response.
**NOTE:** Currently, only include the work item link types and work item link categories in the `included` array. For the other resources to be included, they need …

WIP Fix #533 - Include related resources by default in all actions and endpoints that deal with work item links

---

migration/migration.go
migration/sql-files/012-unique-work-item-links.sql
work-item-link-blackbox_test.go
work-item-link.go
workitem/link/link-repository.go

* Deletes existing duplicate WI links on database level
* Installs a unique key to allow for only one existing WI of the same type with the same source and target
* Checks for unique key violation on creation of WI link and returns BadRequest
Fix #586

Fix #586 Unique work item links

---

design/work-item-link.go
work-item-link-blackbox_test.go
work-item-relationships-links.go

As discussed with @aslakknutsen, these endpoints have been removed:
- DELETE /workitems/{id}/relationships/links/{linkId} (delete work-item-relationships-links)
- GET /workitems/{id}/relationships/links/{linkId} (show work-item-relationships-links)
- PATCH /workitems/{id}/relationships/links/{linkId} (update work-item-relationships-links)
@sanbornsen confirmed, that they are not in use at the moment.

Remove some endpoints

---

workitem/workitem_repository.go
workitem/workitem_repository_blackbox_test.go

Do not change created at during update

---

search/search_repository.go
search/search_repository_whitebox_test.go

Fixes #637 
Added escaping for round braces. Test udpated to expose the bug and add more test_data to check other brackets forms.
API call for search `./bin/alm-cli show search --q '(value)' -H localhost:8080 --pp`
Old Response
```
2017/01/09 11:51:23 [INFO] started id=4FsSPqKA GET=http://localhost:8080/api/search?q=%28value%29
2017/01/09 11:51:23 [INFO] completed id=4FsSPqKA status=500 time=22.055212ms
error: 500: {"errors":[{"code":"internal","detail":"pq: syntax error in tsquery: \"(value):*\"","id":"9QWiejgv","status":"500","title":"Internal Server Error"}]}
{"errors":[{"code":"unknown_error","detail":"pq: Could not complete operation in a failed transaction","status":"500","title":"Unknown error"}]}
```
New Response
```
2017/01/09 11:50:51 [INFO] started id=kp+L4myG …
```

Escape round brackets from search-query-string

---

.make/docker.mk
.make/test.mk
cico_build_deploy.sh
cico_run_coverage.sh
cico_run_tests.sh
cico_setup.sh
remoteworkitem/github_test.go
remoteworkitem/remoteworkitem_test.go
remoteworkitem/scheduler_test.go
remoteworkitem/trackeritem_repository.go
remoteworkitem/trackeritem_repository_test.go
search/search_repository_blackbox_test.go
search/search_repository_whitebox_test.go

I've introduced two new make targets:
1. `test-unit-no-coverage`
2. `test-integration-no-coverage`
These targets execute much faster than the test-unit and test-integration because they don't generate coverage information.
The cico_*.sh scripts have undergone some unification in order to avoid duplicating the code in three files, which potentially can cause a maintenance issue. Alongside to this step, I've introduced a new file called **cico_run_coverage.sh** with does what previously was done by the **cico_run_tests.sh**. The **cico_run_tests.sh** now runs the **test-XXX-no-coverage** Makefile targets.
I've had to ensure that common types like `system.bug` were available when running the tests for `github.com/almighty/almighty-core/remoteworkitem` and …

Add ability to run tests without coverage for faster CI feedback on PR

---

design/iterations.go
iteration.go
iteration/iteration.go
iteration/iteration_test.go
iteration_test.go
migration/migration.go
migration/sql-files/017-alter-iterations.sql
space-iterations.go
space-iterations_test.go
workitem_blackbox_test.go

Fixes : https://github.com/fabric8io/fabric8-planner/issues/701
Added description field to iteration table optional input
added PATCH api to update existing iteration provided with iteration-ID
added tests to cross check API against NotFound, Unauthorized and OK200 cases
Added whitebox tests for update iteration repository method
In many cases `iteration` package was shadowed by the `iteration` parameter in function. It made sense to keep package name as iteration and change the parameter name
Created string constant for jsonapi based `type` value

API to update iterations (title, desc, startDate, endDate)

---

space/space.go
space/space_test.go
workitem/workitem_repository.go

The scope of the pointer reference was being reused outside of the scope
of the loop.

Fix Spaces API returning the same object for all found Spaces

---

workitem/workitemtype_repository.go
workitem/workitemtype_repository_blackbox_test.go

Added missing `name = ?`criteria in the where clause.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/610)

Bug in `workitemtype_repository.Create(...)` method (#609)

---

comments.go
config.yaml
configuration/configuration.go
iteration.go
login/service.go
login/service_blackbox_test.go
login/service_whitebox_test.go
main.go
paging.go
rest/url.go
space-iterations.go
space.go
users.go
work-item-comments.go
work-item-link-category.go
work-item-link-type.go
work-item-link.go
workitem.go

This is a WIP change which using a keycloak instance instead of GitHub for authentication.
Fixes #653
Please review!
TODO:
~~1. Update the keycloak URL and fabric8-online client ID/secret as soon as we have our keycloak instance available in dev or staging cluster.~~
2. Do we really need to store Users and Identities in the DB? Maybe we should use Keycloak of user management 100%? Think about it.
~~3. Refactor the tests so they are testing keycloak instead of github.~~
4. Create a PR to update the "GitHub" button label in UI.
5. Avatar is not available in Keycloak atm. Use gravatar+email instead?

Authentication: Switch from github to the local keycloak instance

---

README.adoc
config.yaml
configuration/configuration.go
design/user_types.go
design/work-item-link-type.go
design/workitems.go
examples/create_workitem.json
main.go
migration/migration.go
migration/sql-files/018-rewrite-wits.sql
remoteworkitem/scheduler_test.go
search/search_repository.go
search/search_repository_blackbox_test.go
search/search_repository_whitebox_test.go
work-item-link-blackbox_test.go
work-item-link-category-blackbox_test.go
work-item-link-type-blackbox_test.go
workitem/workitem_repository_blackbox_test.go
workitem/workitemtype.go
workitem/workitemtype_blackbox_test.go
workitem/workitemtype_repository.go
workitem/workitemtype_repository_blackbox_test.go
workitem_blackbox_test.go
workitem_whitebox_test.go
workitemtype_blackbox_test.go

In #549 I've talked about using ltree for work item type's `path` field because it simplifies building a type hierarchy and checking for sub-types.
In ltree a hierarchy is stored like this: `grandparent.parent.child`. WITs on the other hand were stored as `/system.planneritem/system.bug`.
This changes transform each WIT `path` field from for instance `/system.planneritem/system.bug` to `planneritem.bug`. Notice, that the `system.` prefix has been removed as discussed with @aslakknutsen .
The values for the WIT's `name` fields will then be set to the `path`'s leaf (`subpath(path,-1,1)`).
The prefix `system.` for WITs has been removed from the whole codebase. It remained in places where it is used for attributes (e.g. `system.title`).
**NOTE:** WIT names cannot have spaces in them any …

Use postgres' ltree datatype for WIT's path field

---

design/iterations.go
iteration.go
iteration/iteration.go
iteration/iteration_test.go
iteration_test.go
migration/migration.go
migration/sql-files/019-add-state-iterations.sql
space-iterations_test.go
workitem.go

As per this [comment](https://github.com/fabric8io/fabric8-planner/issues/647#issuecomment-272883624) by Todd and related discussion on [issue-647](https://github.com/fabric8io/fabric8-planner/issues/647), it was clear that start/close/create iteration should be very flexible and no-automation needed while deciding the state. Hence added three new states to the iteration in core. By looking at this attribute, UI can decide where to put each iteration.
* Iteration state can be "new" or "start" or "close".
* By default newly created iteration will have state="new".
* When user wants to start iteration, call update API with state="start"
* When user wants to close iteration, call update API with state="close"
* If there is already an iteration with state=start then another iteration can not …

WIP : Added `states` to iterations.

---

workitem.go
workitem/workitem_repository.go
workitem/workitem_repository_blackbox_test.go
workitem_blackbox_test.go

Previously you could create invalid links by changing the a work item's type if a work item of such a type was already used in some link. This change prevents links between two work items from becoming invalid by disallowing you to change a work item's type.
Fix #550
See https://github.com/fabric8io/fabric8-planner/issues/635 as well as https://github.com/fabric8io/fabric8-planner/commit/4af7d3ebf39161165c1bb6f3cc5e3c82dfe209e6 which removes the ability to change the WIT of a WI from the UI.

Fix #550 - Disallow changing a work item's type

---

search.go
search/search_repository.go
search/search_repository_whitebox_test.go
search_blackbox_test.go

fixes https://github.com/fabric8io/fabric8-planner/issues/749
Support work item URLs in search API
* `/work-item/list/detail/100`
* `/work-item/board/detail/100`

Update URL format in search API "/list/" and "/board/"

---

login/service.go
login/service_whitebox_test.go

Fixes #671
Keycloak currently doesn't provide user's avatars. This PR generates a gravatar URL by user's email and save it as avatar URL.
How it looks in case of existing gravatar:
And if there is no gravatar for this email then the generated gravatar URL will refers to the default gravatar:
If we want to use our own default image then we should add it to all the generated URLs as the following param:
`https://www.gravatar.com/avatar/<hash>.jpg?d=<defultImageURL>`
The d= param will be ignored by gravatar.com if there is an existing image for that email. IMO we should add ?d=... on the UI side instead of hardcoding it in backend.
cc: @joshuawilson

Use gravatar as an avatar image for authorized users

---

design/workitems.go
iteration.go
space-iterations_test.go
workitem.go
workitem_blackbox_test.go

Fixes https://github.com/fabric8io/fabric8-planner/issues/704 and https://github.com/fabric8io/fabric8-planner/issues/703
* List workitems API updated to have filter by iteration
* Updated tests to consume above changes
* Added WorkItemsByIteration URL in related links of list iterations
* Added test case to verify list of work items filter by iteration

List WI - filter by Iterations

---

workitem.go
workitem/field_definition.go
workitem_blackbox_test.go
workitem_whitebox_test.go

Added a validation step in the `ConvertJSONAPIToWorkItem`
function to verify that the `system.title` is not nil nor
empty.
Refactored some error handling switches to remove duplicate
code
Added tests.
Fixes #462

Prevent creating workitem with empty title

---

iteration.go
workitem_blackbox_test.go

Fixed `type` value.
Added tests to check the `type`.

Fix `type` value for iteration relationships of WI API.

---

workitem.go

Refactored code to use the `jsonapi.JSONErrorResponse(ctx, err)`
wherever it was possible. Also, used a more compact syntax to
handle errors on function calls, when applicable.
Fixes #698

Issue 698 : simplify error handling workitem

---

design/render.go
main.go
render.go
rendering_blackbox_test.go

Added an endpoint at /api/render that takes a JSON document in the
POST request and convert the 'content` value of the input doc
using the `markup` value.
Returns a JSON response containing the rendered value if the markup
is supported.
Returns a BadRequest if the markup is not supported.
Fixes #635

Add an endpoint to render markup content in HTML in 'preview' mode #635

---

remoteworkitem/remoteworkitem.go
remoteworkitem/trackeritem_repository_test.go
rendering/markup_content.go
search/search_repository_whitebox_test.go
search_blackbox_test.go
workitem.go
workitem/fieldtype_blackbox_test.go
workitem/markup_content_blackbox_test.go
workitem/simple_type.go
workitem/workitem_repository.go
workitem/workitem_repository_blackbox_test.go
workitem_blackbox_test.go
workitem_whitebox_test.go

Moved the `MarkupContent` struct and its utility functions
into the `rendering` package.

Move `MarkupContent` structure in the `rendering` package (#709)

---

iteration.go
iteration/iteration_test.go
iteration_test.go

- consumed resource href method
- changed logged string in tests.

Use the auto-generated method to generate resource URL for iteration

---

Makefile
cico_setup.sh
space.go
space/space.go

check-go-format:
- Exists with an error if there are files whose formatting differs
from gofmt's
format-go-code:
- Formats any go file that differs from gofmt's style
From this point onwards, the CI will check that GO code is correctly
formatted and if it is not, it will print an error that lists the files
that need to be changed.
In order to satisfy this CI check you can run "make format-go-code" to
have your code in proper shape. Then add those changes made to your
files and commit them.
This commit for example is based on a state of master where not all code
is correctly formatted, so it will not pass CI. I will make a second
commit that fixes this. This commit and the CI run are meant to be seen
as a demonstration that it works.
Try "make help" to find out more about the new make …

WIP Makefile: check-go-format, format-go-code + CI check

---

README.adoc

I experienced an error while testing the almighty commands. In particular, I found that the workitem creation command doesn't work with the mentioned example:
```
./bin/alm-cli create workitem --key "<TOKEN>" --payload '{"type": "Epic", "fields": { "system.owner": "tmaeder", "system.state": "open" }}' -H localhost:8080`
2017/02/02 15:33:19 [INFO] started id=hrK3JTIf POST=http://localhost:8080/api/workitems
2017/02/02 15:33:19 [INFO] completed id=hrK3JTIf status=400 time=14.057174ms
error: 400: {"errors":[{"code":"bad_request","detail":"[v4y23h48] 400 invalid_request: attribute \"data\" of raw is missing and required, attribute: data, parent: raw","id":"IDXykbYw","status":"400","title":"Bad Request"}]}
```
If you check the payload example of the workitem creation cmd, there are new …

Use an updated payload for the creation of the work item

---

design/userspace.go
userspace.go

Temp endpoint for data dump from 'userspace'
Path is a unique ID for a resource that exists in userspace
that need data synced down to saas. PUT Path stores the data and
GET Path fetch the data back.

Replace userspace POST with PUT and GET support

---

rendering/markup_render.go
workitem.go
workitem_blackbox_test.go

using the `html.EscapeString()` function to escape the
title and rendered description content (not the raw content
that remains editable as it was input by the user).
Fixes #708

Prevent script injection in workitem content #708

---

comments.go
comments_blackbox_test.go
design/comments.go
test/account.go

Replaced the `string` type with `UUID` for the `ID` parameter
in the `show` and `update` operations.
Added a `comments_backbox_test.go` to verify that comments can
be shown with and without auth, but cannot be updated without auth
or when the user was not the comment author.
Fixes #714 

Inconsistency in comment id when creating vs showing (#714)

---

comments.go
design/comments.go

Rename 'id' parameter into 'commentId' for the /comments endpoint (#739)

---

comment/comment.go
comment/comment_test.go
comments.go
comments_blackbox_test.go
design/comments.go
migration/migration.go
migration/sql-files/023-comment-markup.sql
rendering/markup_content.go
rendering/markup_content_test.go
work-item-comments.go
work-item-comments_test.go

Added a `markup` column in the `comments` table using
a migration script.
When creating or updating a comment, the default markup
is used if none was provided.
When showing comments, the default markup is also returned
if none was found in the database (ie, for older comments).
Fixes #707

Refactor comments to support markup types (#707)

---

comment/comment.go
comment/comment_test.go
migration/migration.go
migration/sql-files/024-comment-markup-default.sql

Forcing the markup value to 'PlainText' (the default value) when
creating or updating a comment.
Setting this value in the existing DB records
Refactoring the `comment/comment_test.go` test to make them more
compact yet more readable (IMO)
Fixes #741 

Set default comment markup to 'PlainText' in the database (#741)

---

comments.go
comments_blackbox_test.go
design/comments.go
work-item-comments_test.go

Added an extra field in the comment response to hold
the HTML rendered value based on the `body` and `markup`
of the comment.
Also, the generated HTML is escaped, preventing script
injection.
Refactored significantly the `work-item-comments_test.go`
file to make it more readable. Using methods instead of pure
functions allows for the same names in different TestSuite
in the same package.
Fixes #744
Fixes #724

Return the HTML rendering of comments #744

---

Makefile
migration/migration.go
remoteworkitem/remoteworkitem.go
search/search_repository_whitebox_test.go
token/token_test.go
workitem/workitemtype_blackbox_test.go
workitem/workitemtype_repository_blackbox_test.go
workitem/workitemtype_repository_whitebox_test.go
workitem_blackbox_test.go

To accomplish this, I've modified the `make format-go-code` target in order to to simplify the code.

Require simplified golang code on CI

---

cico_build_deploy.sh

This runs tests without coverage when building master for deployment. (Fixes #759)
This PR will run the existing coverage script `cico_run_coverage.sh` for master:  https://github.com/almighty/almighty-jobs/pull/76

Don't run coverage tests with coverage when deploying master

---

Makefile

removed the `--verbose` flag that is not supported
on glide 0.13.0
Fixes #764 

`make build` fails on `glide --verbose`  (#764)

---

.golint_exclude
.make/Makefile.lnx
.make/Makefile.win
.make/docker.mk
.make/test.mk
Makefile
cico_setup.sh
glide.lock
glide.yaml

I'd like to point it out several things:
- These checks don't aim to be blockers for the PR, in other words, not to fail our jenkins tests.
- These checks could help us to enforce a good quality for our code
- I selected three of the most common tools to analysis the go code: `gofmt`, `go vet`, `golint`, `gocyclo`... We already had `gofmt` in our Makefile,
- The results of these checks are included into a log file (as proposed in https://github.com/almighty/almighty-core/pull/45) but we could print them into the stdout. I think that makes more sense but I wanted to know your opinion.
If we want to add more tools maybe we could consider using  https://github.com/alecthomas/gometalinter

Go code quality checks

---

design/auth.go
design/media_types.go
design/resources.go
login.go
login/service.go
login/service_whitebox_test.go
login_test.go

This PR fixes the following parts of the #774 issue:
1. /api/login/generate now returns a payload with both refresh and access tokens:
```
[
{
"token": {
"access_token": "<ACCESS-TOKEN>",
"expires_in": 1800,
"not-before-policy": 0,
"refresh_expires_in": 1800,
"refresh_token": "<REFRESH-TOKEN>",
"token_type": "bearer"
}
}
]
```
2. /api/login/authorize when doing the final redirect now includes an encoded JSON with both refresh and access tokens in "token_json" param:
```
Location: http://localhost:8088/login?token=ACCESS_TOKEN&token_json=ENCODED_TOKEN_JSON
```
Here is an example of token_json:
```
{
"access_token": "<ACCESS-TOKEN>",
"expires_in": 1800,
"not-before-policy": 0,
"refresh_expires_in": 1800,
"refresh_token": "<REFRESH-TOKEN>",
"token_type": "bearer"
}
```
The "token" param is …

Add refresh tokens to /api/login/authorize and /api/login/generate responses

---

search.go
search_blackbox_test.go

This is code cleanup PR where I've removed repetitive code for generating paging boundaries for the paging link, inside the Search controller.

Use paging modular methods in Search controller

---

criteria/criteria.go
criteria/doc.go
design/workitems.go
workitem.go
workitem_blackbox_test.go

This extends the current filter API:
```
http://demo.api.almighty.io/api/workitems?page[limit]=23&filter[assignee]=e6f58d79-12e1-4db3-b795-87c200106c06
```
to allow for a `&filter[workitemtype]=bug` parameter, where `bug` can be any work item type. Currently the filtering is done on a concrete type and not on the WIT hierarchy.
Fixes #783

Extend WI filter API to allow filtering by WIT

---

workitem.go
workitem/link/link_repository.go
workitem_blackbox_test.go

If we don't auto-delete the links, then we get a 404 when we query for
the links on the still existing end of a link. This is because we try to
resolve both ends of the link and the one that has been deleted
obviously cannot be found.
For now we auto-delete the links associated to a WI in the WI
controller explicitly. Later we might want to have some registration
mechanism where different systems can hook into. For now this is
overkill.
Fixes #768

Auto-delete links on a WI when WI gets deleted

---

design/auth.go
errors/errors.go
errors/errors_blackbox_test.go
login.go
login/service.go
login_test.go

This is a proxy API for token refresh in case we decide to go with a proxy instead of using a public Keycloak client.

Added a proxy API for token refresh

---

migration/migration.go

Replace reverse name of "Related planner item" link type: `relates to` becomes `is related to`. This distinguishes it from the forward name which also used to be `relates to`.
As soon as the UI shows correct forward and reverse names, we need to make this change in order to distinguish "link types" or forward and reverse names in the UI.
@sanbornsen's  commit on UI side is going to fix this: https://github.com/sanbornsen/fabric8-planner/commit/18f6c0c6ea6b9de7ecaaea78bcfb855eed302e12

Have distinguishable forward and reverse names for link types

---

rendering/markup_content.go
workitem.go
workitem_blackbox_test.go

When a description is sent in the new format and deserialized
from json it has the type map[string]interface{} and not the
internal type rendering.MarkupContent
Related #835

Support system.description as type map[string]interface{}

---

migration/migration.go
migration/sql-files/027-areas-index.sql

The parent path column in the database in Area table is an
ltree field which stores the path to the parent.
Searching the ltree field can be made efficient by using
either the btree or gist index.
https://www.postgresql.org/docs/current/static/ltree.html
How to check if index is being hit:
- create a large test data  set in areas table ( tested with about 1000 )
- Fire the query similar to " explain analyze select path from areas where path ~ 'e9a6afc1_e51e_4a35_b16a_97e673b914f1.*'; "
- The output should mention which is the index that was used.

Add index for searching parent path of Areas

---

log/log.go
main.go
migration/migration.go
search/search_repository.go
workitem/link/link_repository.go
workitem/link/type_repository.go
workitem/workitem_repository.go
workitem/workitemtype_repository.go

@aslakknutsen detected that the `req_id` value was missing in the logs for some of the operations in the repositories. This PR fixes this problem and sets request id also for the database propagation.

Propagate the ctx over the repository operations

---

main.go

We don't want the logs to prompt `\n`
```
{"level":"error","msg":"ERROR: Unable to open connection to database dial tcp 127.0.0.1:5432: getsockopt: connection refused\n","time":"2017-02-21 01:10:21"}
{"level":"info","msg":"Retrying to connect in 1s...\n","time":"2017-02-21 01:10:21"}
```

Removed unnecessary newlines

---

config.yaml
configuration/configuration.go
configuration/configuration_blackbox_test.go
configuration/configuration_whitebox_test.go
design/auth.go
login.go
login/service.go
login/service_blackbox_test.go
main.go
rest/url.go
rest/url_blackbox_test.go

This PR switches the pre-configured FQNS keycloak URL's to relative URL's.
1. If the `keycloak.*` variables set up then they are always used.
2. If not set up then if in Dev Mode the hardcoded `sso.demo.almighty.io` is used.
3. If not set up nor in Dev Mode then the last segment of the core host name is replaced by "sso" (also configurable). Example: `api.service.domain.org` -> `sso.service.domain.org`
Fixes #775
**Please note (!!!)** that the current `demo.api.almighty.io` doesn't follow the service name convention used by this PR: `<serviceName>.<domain>`. It's should be `api.demo.almighty.io` instead to be correctly converted to `sso.demo.almighty.io`

Use relative URL's rather than FQDN's for dependency services

---

config.yaml
configuration/configuration.go
configuration/configuration_whitebox_test.go

With this change we don't need to pass the Keycloak realm name to the preview instance configuration. The default "fabric8" will just work.

Change the default Keycloak realm name from 'demo' to 'fabric8'

---

log/context.go
log/log.go
log/log_test.go
login/service.go
login/token_context/token.go
login/token_context/token_context.go
test/login.go
workitem/workitem_repository.go
workitem/workitemtype_repository.go

I had to make some adjustments to other packages to avoid import cycles. To avoid some spaghetti code, I decided to go with this solution instead of creating interfaces here and there.
I named the property as `identity_id` similar to the other property `req_id`.

Added identity_id to the logs for better traceability 

---

iteration.go
iteration_test.go
iteration_whitebox_test.go
space-iterations.go
space-iterations_test.go
test/work_item_repository.go
workitem/undoable_wi_repo.go
workitem/workitem_repository.go

Related story https://github.com/fabric8io/fabric8-planner/issues/647
Allows UI to use same model as there is same response for all iteration related APIs.
Like we did in list-iterations response, need to add  WI counts in response of create/update/show/create-child iterations.
Added and modified tests around WI counts.

work item count for an iteration (create/update/show/create-child).

---

account/identity.go
remoteworkitem/remoteworkitem.go
remoteworkitem/remoteworkitem_test.go
remoteworkitem/trackeritem_repository.go
remoteworkitem/trackeritem_repository_test.go
user_test.go

Applied same logic as in #756 by looking-up the identity of the
remote work item creator (or creating a new one) based on the
profile URL provided in by the remote service (GitHub or JIRA)
Fixes #806

Handle remote work item creator's identity (#806)

---

cico_setup.sh

move to the dev.registry that allows content to be pulled from various openshift clusters.

move away from the private ci registry

---

migration/migration.go
migration/sql-files/030-indentities-unique-index.sql

Replaced the unique index by adding a check on 'deleted_at' to
support soft deletes performed by GORM.
Fixes #863

Modify the unique index on `identities` table (#863)

---

comments.go
iteration_test.go
login/service.go
remoteworkitem/trackeritem_repository.go
search/search_repository_blackbox_test.go
search/search_repository_whitebox_test.go
search_blackbox_test.go
space-areas.go
space-iterations_test.go
test/work_item_repository.go
work-item-comments.go
work-item-comments_test.go
workitem.go
workitem/undoable_wi_repo.go
workitem/workitem_repository.go
workitem/workitem_repository_blackbox_test.go

Removed the `uuid.UUID` to `string` conversion and return nil if something
wrong happened.
Fixes #866

`ContextIdentity(context.Context)` function should return `(*uuid.UUID…D, error)` (#866)

---

search/search_repository_blackbox_test.go
status_test.go

For example in this [CI run](https://ci.centos.org/job/devtools-almighty-core/1925/console) we experienced this issue (and in many more):
```
--- FAIL: TestRunSearchRepositoryWhiteboxTest (0.03s)
panic: pq: duplicate key value violates unique constraint "work_item_types_pkey" [recovered]
panic: pq: duplicate key value violates unique constraint "work_item_types_pkey"
```
I found that function `TestRunSearchRepositoryWhiteboxTest` existed twice in the `search` package:
```sh
$ grep "TestRunSearchRepositoryWhiteboxTest" . -r
./search/search_repository_whitebox_test.go:func TestRunSearchRepositoryWhiteboxTest(t *testing.T) {
./search/search_repository_blackbox_test.go:func TestRunSearchRepositoryWhiteboxTest(t *testing.T) {
```
Also, there was a test that wanted to run in parallel but …

This should fix the ever occurring test failure with duplicate keys

---

config.yaml
configuration/configuration.go
main.go

ALMIGHTY_POSTGRES_CONNECTION_MAXIDLE
ALMIGHTY_POSTGRES_CONNECTION_MAXOPEN
A value of -1 triggers default pool behavior.

Add configuration options for db pool max idle and max open

---

design/work_item_link.go
design/work_item_link_category.go
design/work_item_link_type.go
work-item-link-blackbox_test.go
work-item-link-category-blackbox_test.go
work-item-link-type-blackbox_test.go
work-item-link-type.go
work-item-link.go
workitem/link/category.go
workitem/link/category_blackbox_test.go
workitem/link/category_repository.go
workitem/link/doc.go
workitem/link/link.go
workitem/link/link_repository.go
workitem/link/type.go
workitem/link/type_repository.go

Greatly simplify the handling of IDs in linking
UUIDs can be passed through most of the time and don't have to be
checked for type conversion errors.
Also the "type" field in relations is not checked for WILs, WILTs, and
WILCs because it is defined as an enum in the design folder. So REST
calls will not get through that have something different in the "type"
field anyway.

WILC, WILT, and WIL use UUIDs from REST to DB/Repo

---

configuration/configuration.go
configuration/configuration_blackbox_test.go
configuration/configuration_whitebox_test.go
gormsupport/db_test_suite.go
login.go
login/service.go
login/service_blackbox_test.go
login/service_whitebox_test.go
login_test.go
main.go
migration/migration_test.go
remoteworkitem/github.go
remoteworkitem/jira.go
remoteworkitem/scheduler.go
remoteworkitem/scheduler_test.go
search.go
search_blackbox_test.go
search_spaces_blackbox_test.go
tracker.go
tracker_blackbox_test.go
tracker_test.go
trackerquery.go
trackerquery_blackbox_test.go
trackerquery_test.go
work-item-link-blackbox_test.go
work-item-link-category-blackbox_test.go
work-item-link-type-blackbox_test.go
workitem_blackbox_test.go
workitem_whitebox_test.go
workitemtype_blackbox_test.go

This PR which fixes #592  was being solved as part of #712 - here's the new PR with the new approach.
(  After feedback from  @aslakknutsen I realized what I was doing there wasn't solving the problem. Since this change spans the entire codebase, it wasn't productive to make the new changes in the old PR ( after fixing tons of conflicts ) , hence this new one ) 
The very high-level requirement is :
- initialize config only once.
-  pass configuration options at the controller level.
- expose only those configurations which are needed.
The objective of this PR , and the stuff that was done to accomplish the above:
1. Avoid setting up configuration multiple times in different parts of the code. It needs to be setup only *once* inside main.go and should be passed on to all the …

Expose limited configuration to controllers and initialize config only once.

---

config.yaml
configuration/configuration_blackbox_test.go

The format in which the private and public keys were entered in config.yaml leads to failures when the key is parsed from the file. This fixes #883 
---------
The private and public keys in the config.yaml need to be passed
in a specific way so that the parsing doesnt remove the newlines needed for the key
to be parsed correctly into a valid PEM format
http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210
fixes #883

Fix config.yaml entry for token keys

---

migration/migration.go

This would allow us to pass static IDs to a SQL migration file that has placeholders (e.t. `"%[1]s"`) in it.
Here's a discussion on why me might want to have this: https://github.com/almighty/almighty-core/pull/852#discussion_r103242104
I wonder if we need to take special care when doing the replacements because the `%` symbol in SQL is a reserved symbol. Maybe https://golang.org/pkg/text/template/ is a better choice for doing the replacement?
This essentially allows you to write: 
```go
// Version XY
m = append(m, steps{executeSQLFile("0XY-foobar.sql", workitem.SystemSpace, 123)})
```
where `workitem.SystemSpace, 123` are used as placeholder replacements for the file `0XY-foobar.sql`.

Allow for placeholders in migration.executeSQLFile

---

controller/users.go
controller/users_blackbox_test.go
design/account.go

fixes #878 
- payload for updating user will not contain 'ID' ,  the ID would be deduced from the context token. Hence created new payload type in `design/account.go`
- refactored existing tests by putting re-usable code into method(s).
- added controller method for Update(..) in `controller/users.go`

add support for update user profile

---

controller/namedspaces.go
controller/namedspaces_test.go
controller/space.go
controller/space_test.go
design/namedspaces.go
design/spaces.go
main.go
migration/migration.go
migration/sql-files/034-space-owner.sql
space/space.go
space/space_test.go

Modified REST API URL from /api/spaces/{spaceId} to /api/spaces/{spaceName}.
This allows spaces to be queried by name through a path, without the use of a filter query parameter for the name attribute.
This also modifies URIs of sub-resources like iterations. Modified tests accordingly.

Support GET /api/spaces/{spaceName}. Fixes #696.

---

migration/sql-files/035-wit-to-use-uuid.sql

If we add a new column to a table without having a default value we **MUST NOT** use `NOT NULL` in the column definition. Add `NOT NULL` only after you have filled the column.

Add NOT NULL only after filling a column

---

migration/migration.go

Previously the name, description, and icon of a WIT were not being updated in the migration if the WIT already existed. Since we've moved to JSONAPI with a UUID as a reference for the WIT instead of its name, we can safely update the above columns.

Also update WIT's name, description, and icon during migration

---

jsonapi/jsonapi_utility.go
jsonapi/jsonapi_utility_blackbox_test.go

Previously you would have to write:
```go
jerrors, _ := jsonapi.ErrorToJSONAPIErrors(goa.ErrUnauthorized(err.Error()))
return ctx.Unauthorized(jerrors)
```
And now you can write:
```go
return jsonapi.JSONErrorResponse(ctx, errors.NewUnauthorizedError(err.Error()))
```
which is a little bit more like we have treated all the other error
causes.
I've also added some tests for this package.

Support unauthorized error in ErrorToJSONAPIError

---

controller/workitem.go
controller/workitem_blackbox_test.go

Fixes https://github.com/almighty/almighty-core/issues/953
Temporary logic to set default space for a WI while creation.
Validate space given in the API body.
Tests added.

Set and validate space while creating WI

---

migration/migration.go

BootstrapWorkItemLinking and PopulateCommonTypes launch updates over the space, and uses that space to refer it as foreign key in other creations. 
related to https://github.com/almighty/almighty-core/issues/952

Added a lock for the BootstrapWorkItemLinking function

---

controller/iteration.go
controller/space_iterations.go
controller/space_iterations_test.go
iteration/iteration.go
iteration/iteration_test.go

Fixes https://github.com/almighty/almighty-core/issues/971
Removed `ConvertToLtreeFormat` and `ConvertFromLtreeFormat` from iterations package.
Make use of `path.Path` for iteration.Path
Tests updated.
No change in representation for database layer. It is still a valid ltree sting like `218172e8_a797_49f8_b3f3_b96e5ac6f0f4.3574fb25_45db_4397_87ca_8690529328be` 
But `iteration.Path` is a slice of UUIDs(path.Path) now instead of string.

Change type of iteration.path to path.Path

---

controller/workitem_blackbox_test.go
controller/workitemtype_blackbox_test.go

Use same gorm DB instance between all controllers
to track all data created.

Reorder test init to include all resources

---

controller/search_blackbox_test.go
glide.lock
glide.yaml
login/service_blackbox_test.go
rendering/markdown.go
rendering/markup_render.go
rendering/markup_render_test.go

HTML output support the Code-Prettify CSS styles.
When UI add the code prettify CSS the output will look like:

Add syntax highlight parsing to Markdown Code blocks

---

controller/work_item_link_blackbox_test.go
controller/work_item_link_type_blackbox_test.go

- ensured that unscoped deletes in tests happens by ID and not by name.
- above change was made because it was noticed that *all spaces* were being deleted whenever `db = db.Unscoped().Delete(&space.Space{Name: s.spaceName})` was being called.
fixes #991

remove only those spaces which are created in unit tests

---

controller/search_blackbox_test.go
glide.lock
login/service_blackbox_test.go

It seems like goa `gen_controller` is not longer inside `v1.1.0`. I am trying to understand why of this reason. Meanwhile, you could use the following version ID for goa if you face problems.
@aslakknutsen I remember you upgraded goa version https://github.com/almighty/almighty-core/commit/e4f70a5fbb1d90ae2630d6916e7c9f04f4aff931. So we might be blocked by this...

Use latest goa v1 commit which includes gen_controller

---

controller/work_item_link.go
controller/work_item_link_category.go
controller/work_item_link_category_blackbox_test.go
space/space.go
space/space_test.go
workitem/link/category.go
workitem/link/category_blackbox_test.go
workitem/link/category_repository.go
workitem/link/link.go
workitem/link/link_blackbox_test.go
workitem/link/link_repository.go
workitem/link/type.go
workitem/link/type_blackbox_test.go
workitem/link/type_repository.go
workitem/workitemtype.go

In old code I've been using `satoriuuid` as the import name for the UUID library. In newer code we just use `uuid` as the import name. In order to be consistent., I've changed the import name to `uuid` everywhere.
```diff
-	satoriuuid "github.com/satori/go.uuid"
+	uuid "github.com/satori/go.uuid"
```
This was more or less a mechanical change.

Replace imported satoriuud with uuid

---

auth/authz_blackbox_test.go
config.yaml
configuration/configuration.go
configuration/configuration_blackbox_test.go
configuration/configuration_whitebox_test.go

- Switch to sso.prod-preview
- Use the test realm by default
We will also need to add the test realm URI to the list of valid redirect URIs in the tsrv cluster 
Fixes https://github.com/almighty/almighty-core/issues/1019

Switch to prod-preview test Keycloak realm

---

application/application.go
codebase/che/client.go
codebase/codebase.go
codebase/codebase_test.go
configuration/configuration.go
controller/codebase.go
controller/codebase_blackbox_test.go
controller/space.go
controller/space_codebases.go
controller/space_codebases_test.go
controller/user_test.go
design/api.go
design/codebases.go
design/spaces.go
design/workitems.go
gormapplication/application.go
log/log.go
main.go
migration/migration.go
migration/sql-files/047-codebases.sql
test/db.go

Codebase is tied to a Space. Each codebase represents some
form of repository.
Provide edit/create API via Che-Starter targeting the tenant services.
Che-Starter interaction is undertested. Needs semi-stable api to produce a api recording.

Add codebase RESt API

---

config.yaml
configuration/configuration.go
configuration/configuration_whitebox_test.go
login/service_blackbox_test.go

This PR introducing a new realm name var used in devmode. So we don't need to set up realm name vars in production and devmode. The default ones will be used.

Add Keycloak real name used in dev mode

---

controller/workitem_blackbox_test.go
workitem/workitem_repository.go

[1] fixes #1024 
Before this commit, when a workitem was updated, the execution_order would automatically get set to 0 because of wrong handling of execution_order. This commit aims to fix it. Now, if a workitem is just updated (and not reordered), its execution_order is not changed.

Fixes storage of ExecutionOrder on Update

---

goasupport/conditional_request/generator.go

Added some switches to the `generateETagValue()` function template
so that more types can be handled.
Fixes #1027 

Errors in the console related to a malformed Etag (#1027)

---

config.yaml
configuration/configuration.go
controller/iteration.go
controller/iteration_test.go
controller/planner_backlog_test.go
controller/space_iterations.go
controller/space_iterations_test.go
design/iterations.go
goasupport/conditional_request/generator.go
iteration/iteration.go
main.go

Also added `CreatedAt` and `UpdatedAt` fields on the returned iterations (JSON)
Fixes #1059

Add conditional requests and cache-control headers on the 'iterations' endpoints (#1059)

---

config.yaml
configuration/configuration.go
controller/space_test.go

Lower the `max-age` values to 10s for /spaces and /iterations (#1064)

---

configuration/configuration.go
configuration/configuration_whitebox_test.go
controller/login.go
controller/login_test.go
design/auth.go
login/service.go
login/service_blackbox_test.go

- New optional redirect param for /api/login/authorize
- If no redirect param set then use referer header
- If no redirect param and referer is empty then return 400 Bad Request
- Validate referrers/redirect URLs if they are whitelisted
Fixes https://github.com/almighty/almighty-core/issues/1073 and https://github.com/almighty/almighty-core/issues/892

Add redirect param to login endpoint

---

configuration/configuration.go
configuration/configuration_whitebox_test.go

localhost was whitelisted for requests to: api.prod-preview.osio.io/api 
but didn't work for requests to: api.prod-preview.osio.io:8080/api
Now it works for any port for prod-preview.osio.io.
Not sure if we really need it or customizing whitelist on cluster level by setting env var is enough/right approach.

Fix redirect URL whitelist exception for prod-prevew

---

controller/users.go
controller/users_blackbox_test.go

---- commit message ----
The User contextInformation is stored as a json blob in the backend. 
Prior to this PR, the client had to send the entire json blob to the API even for a tiny update.
This change ensures that only the changed attribute can be sent in the PATCH request, and the API would handle merging it with the existing contextInformation json blob
Fixes #1107 
--- end -----
Step 1:
```
./bin/alm-cli update users --key $ALM_TOKEN 
--payload 
'
{
"data": {
"type": "identities",
"attributes": {
"contextInformation": {
"a": "New Attribute , Yay!"
},
"bio": "something222"
}
}
}
'  -H localhost:8080 --pp
2017/04/03 10:11:38 [INFO] started id=QV9PrgVg PATCH=http://localhost:8080/api/users
2017/04/03 10:11:38 [INFO] completed id=QV9PrgVg status=200 time=14.818569ms
{
"data": { …
```

Add capability to PATCH user contextInformation

---

login/service.go

UI is now is now sending link=true on all requests to authorize. So we don't need to hardcode it anymore.

Disable hardcoded auto-linking during login. Relay on ?link param instead

---

configuration/configuration.go
controller/work_item_children_blackbox_test.go
controller/work_item_link.go
controller/work_item_link_blackbox_test.go
controller/work_item_relationships_links.go
controller/workitem_blackbox_test.go
design/work_item_link.go
goasupport/conditional_request/generator.go
main.go

Also added `created-at` and `updated-at` elements in the JSON responses.
Also removed the `wiConfiguration` package variable as it's a duplicate of
the `Configuration` variable inherited from the `gormtestsupport.DBTestSuite`
Fixes #1112

Add conditional requests and cache-control headers on the 'work item links' endpoints (#1112)

---

configuration/configuration.go
configuration/configuration_blackbox_test.go
controller/logout.go
controller/logout_test.go
design/auth.go
login/logout.go
login/logout_blackbox_test.go
main.go

There is now a new endpoint which redirects to Keycloak to log out user:
**GET /api/logout**
Optional param: redirect=<encodedRedirectURL>, if not set then referrer will be used to redirect to after logout.
Fixes https://github.com/almighty/almighty-core/issues/987

Logout User

---

migration/sql-files/048-unique-iteration-name-create-new-iteration.sql

Fixes #1135 
Verified with following case:-
1. Iterations having same name (append UUID to the name to make them unique)
2. Borrowed data dump from hector's commit #1134 
Modifications made in the PR are working fine for above two cases.
@aslakknutsen @alexeykazakov @hectorj2f 
I want to test this thing against Production-DB, is there any way I can get data dump for production ?

Modify migrations for root iterations.

---

controller/work_item_children_blackbox_test.go
controller/work_item_comments.go
controller/workitem.go
workitem/link/link_repository.go

In order for the planner to render an expander symbol, it needs to know if a work item has any children. I've create a `SELECT EXISTS...` query for this because we don't need to fetch or count all children for this task.
These work item actions will include the `hasChildren` meta information:
* list (tested),
* show (tested),
* update,
* reorder
* list children (tested), and
* create (tested)

include "hasChildren" field in a work item's "children" relationship

---

main.go

Currently we have many spaces in prod-preview that were created before we started creating Keycloak authz resources during space creation. So such old spaces don't have associated resources in Keycloak. Attempts to obtain or update the list of the space collaborators will fail. We basically can't authorize access to such resources via Keycloak.
This PR is a one-time solution which creates Keycloak resources for old spaces that don't have such associated KC resources yet. When it's merged & deployed we will revert it.

Create Keycloak resources for old spaces

---

workitem/workitemtype_repository.go

In the WIT repo's `Create()` function we checked if we can load a given work item type which is not needed IMHO.

Remove not needed check

---

account/user.go
controller/users.go
controller/users_blackbox_test.go
design/account.go
login/profile.go
login/service.go
migration/migration.go
migration/sql-files/050-add-company-to-user-profile.sql

fixes https://github.com/almighty/almighty-core/issues/1052
Steps to test the changes:
1. Call user update API:
```
Shoubhiks-MacBook-Pro:almighty-core shoubhikbose$ ./bin/alm-cli update users --key $ALM_TOKEN  --payload '{ "data":{ "type":"identities" ,  "attributes":{"bio":"something","company":"redhat inc " }}}'  -H localhost:8080 --pp
2017/04/10 13:38:27 [INFO] started id=tsO8VBMA PATCH=http://localhost:8080/api/users
2017/04/10 13:38:30 [INFO] completed id=tsO8VBMA status=200 time=2.48466458s
{
"data": {
"attributes": {
"bio": "something",
"company": "redhat inc ",
"email": "smith@matrix.net",
"fullName": "Agent Smith",
"imageURL": "https://www.gravatar.com/avatar/0ae61af08b4d0ea5db25d6db8afbe9b9.jpg",
"providerType": "kc",
"url": "",
"username": "testuser"
},
"id": …
```

Add company detail to user profile

---

config.yaml
configuration/configuration.go
configuration/configuration_whitebox_test.go
log/log.go
log/log_test.go
main.go

related to: https://github.com/almighty/almighty-core/issues/1166
Default log level would be set to `ERROR`. If we use `config.yaml` then it is set to `INFO`. 
By using an ENV variable `ALMIGHTY_LOG_LEVEL=debug|info|panic|error|warning|fatal`, you're specifying the log level.
FYI: @ldimaggi

Add a new ENV variable to specify the logging level

---

Dockerfile.deploy
alm+pmcd.sh
pcp.repo

Implant a performance-copilot server background process in the
almighty-core dockerfile, so that central performance monitoring
software can query process statistics.

BIOHAZARD WARNING - PMCD IMPLANT

---

gormsupport/cleaner/db_clean.go

This change checks if a GORM `Create` hook has already been registered under the name `"mighti:record"`. If that is the case, it will register the same hook under a different unique name. 
When you want to use `cleaner.DeleteCreatedEntries` outside of the and `*_test.go` file you need this.
For example, I want to create a temporary space and some work item types as well as work item link types, when somebody creates a space template. This is for validation purposes that the space template can be created.
Once I've created all those entries I want to get rid of them and just store the space template but no longer keep the temporary objects around. `cleaner.DeleteCreatedEntries` comes in handy here but without this change it won't work when invoked from within tests because the tests …

unique gorm create hook name

---

auth/authz.go
auth/authz_blackbox_test.go
auth/policy.go
auth/resource.go
controller/collaborators.go
controller/collaborators_test.go
controller/login.go
controller/login_test.go
controller/space.go
controller/space_test.go
controller/workitem.go
controller/workitem_blackbox_test.go
login/service.go
login/service_blackbox_test.go
login/service_whitebox_test.go
login/token_context/token_context.go
main.go
space/authz.go
space/authz/authz.go
space/authz/authz_test.go
test/login.go

There is a new Space Authorization Service injected in every request.
So, there following code can now be used to check if the current user is among space collaborators:
```
_, authorized, err := space.Authorize(ctx, spaceID)
if err != nil {
return jsonapi.JSONErrorResponse(ctx, errors.NewUnauthorizedError(err.Error()))
}
if !authorized {
return jsonapi.JSONErrorResponse(ctx, errors.NewUnauthorizedError("user is not authorized to access the space"))
}
```
If this PR is approved and merged then PRs for other secured space resources (WI links, types, areas, etc) will follow.
Fixes https://github.com/almighty/almighty-core/issues/1152

Only space collaborators should be able to edit Work Items

---

login/service.go

Removing deprecated token param from /api/login/authorize response. We are currently using token_json only. It will help us to reduce the length of the URL
See https://github.com/almighty/almighty-core/issues/1177

Remove deprecated token param from 307 response URL

---

login/service.go
space/authz/authz.go
space/authz/authz_test.go

RPT tokens which contains the set of spaces available to user may be too long if user has too many spaces. Login fails because we pass the token in the URL.
This PR is disabling RPT tokens. The access tokens will be used instead until we find a better solution.
Related to https://github.com/almighty/almighty-core/issues/1177

Use access tokens instead of RPTs

---

controller/space.go
controller/space_test.go
migration/migration.go
migration/sql-files/052-unique-space-names.sql
space/space_test.go

The index now checks for uniqueness across owners and space names,
instead of enforcing uniqueness on space names globally.
Fixes #1000

Modify unique index on space names.

---

controller/space_test.go

Correct me if I'm wrong but those tests look wrong to me, You dereference a point and check if the result is NotNil. The check should be done before dereferencing, no?
https://github.com/almighty/almighty-core/blame/master/controller/space_test.go#L398

Don't dereference before checking for NotNil

---

application/repositories.go
controller/search.go
controller/search_blackbox_test.go
design/search.go
search/search_repository.go
search/search_repository_blackbox_test.go
search/search_repository_whitebox_test.go

Fixes #1169 
Search API takes a `spaceID` as query param to contextualize the search results.
If not passed `spaceID` then searching will not be affected.
Tests added/updated.

Make Search API space aware 

---

migration/migration_blackbox_test.go

@sbose78 the problem was that migrationToVersion was migrating to `currentVersion`+ 1 instead of until the specified version.
related to https://github.com/almighty/almighty-core/issues/1188

Added function to migrate until a specific version

---

config.yaml
configuration/configuration.go
configuration/configuration_blackbox_test.go
controller/login.go

This is a workaround of the OS limit of using long http headers.
If an RPT token is too big then we should issue a new access token when refreshing instead of a new RPT token.
We would need to merge it if we can't solve this problem on the OS side. The OS header limit problem is being currently investigated.

Don't swap access tokens for too big rpt tokens when refreshing

---

.gitignore
Makefile
account/init_tenant.go
configuration/configuration.go
controller/user.go
glide.lock
glide.yaml
goasupport/forward_signer.go
main.go

Due to lack of 'in linking flow' location to call init tenant
it's currently being done as part of the /api/user call which
is the first call that is done from the UI after linking is done.
First call to tenant service will start the initialize process
while all other will return a Conflict error which is ignored.

Add tenant service call from /api/user

---

openshift/core.app.yaml

if its set, then use the tenant init service locally

use, if available a location for tenant services

---

space/space_test.go

Check for presence of the space in the list instead of merely the length of the list.
Before this change, this is what the error looked like:
```
--- FAIL: TestList (0.01s)
space_test.go:110: Old count of spaces : 2 , new count of spaces : 5
assertions.go:241: 
Error Trace:	space_test.go:111
Error:		Not equal: 0x3 (expected)
!= 0x5 (actual)
```
https://ci.centos.org/job/devtools-almighty-core/3020/console

Fix the "list spaces" test 

---

workitem/field_definition_whitebox_test.go

While working on the space templates, I've noticed that the tests that check if a work item type is compatible to another one, were lacking the non-happy-path tests. I've added those.

get better workitem.compatibleFiels() tests

---

controller/users.go
controller/users_blackbox_test.go

As part of this PR, we update email/username for a user only if it wasn't found in the database for another user/identity.
Prior to this, we validated the email/username inside keycloak only.

Validate uniqueness of user email/username from database

---

controller/planner_backlog.go
controller/workitem.go
controller/workitem_blackbox_test.go
controller/workitem_test.go
design/workitems.go
test/work_item_repository.go
workitem/workitem_repository.go

The top-level listing of work items in the UI's tree view should only contain work items without any parent (aka the "root" work items).
This change adds a new boolean `parentexists` list-filter to the `workitems` endpoint:
`/spaces/{id}/workitems?filter[parentexists]=false`
When filter is set to `false`, it lists all work items that have **no** parent; otherwise all work items (with and without parent) are listed.
Fixes https://github.com/fabric8io/fabric8-planner/issues/1661

API to list WIs without any parents

---

controller/users.go
controller/users_blackbox_test.go

Fixes https://github.com/almighty/almighty-core/issues/1225
If the current username is sent as part of `PATCH /api/users` , it should not be considered as an update. This fix resolves the problem of (re)setting the username to the older/same username which was causing the `registration_completed` to be set to True.

Set registrationCompleted=True only if a distinct username is used

---

login/profile.go
login/profile_blackbox_test.go

This fix ensures that KC username is updated.
Fixes #1129

Fix KC profile attribute name for username

---

login/profile_blackbox_test.go

This hardcoding was put in place to avoid failure during test cleanup. It is being removed now.

Remove test username hardcoding

---

controller/users.go
controller/users_blackbox_test.go
design/account.go

fixes #1232
- User Profile registrationCompleted should support PATCH'ed to true
-  but PATCH to false should not be supported.
Initial discussion : 
https://github.com/almighty/almighty-core/issues/1225

Expose and Support registrationCompleted=True for HTTP PATCH

---

controller/search_user_blackbox_test.go

Owing to improper clean-up, the test for number of search results ( for user search ) is showing up to be more than expected. This is causing tests to fail at times.
```
--- FAIL: TestUsersSearchOK (0.20s)
search_user_blackbox_test.go:164: With lowercase fullname query got = 4, want 3
search_user_blackbox_test.go:164: With uppercase fullname query got = 4, want 3
```
https://ci.centos.org/view/Devtools/job/devtools-almighty-core-build-master/446/consoleFull
So instead of checking the exact count, we'll check the 'at least' count till we figure out how to do the cleanup well.

Use greater-than-equal clause for search results count in tests

---

Makefile

`account/tenant` is a directory and needs the `-r` switch.

Proper clean up of tenant directory

---

config.yaml
configuration/configuration.go
controller/login.go
controller/login_test.go
login/service.go
login/service_blackbox_test.go

`export ALMIGHTY_AUTH_NOTAPPROVED_REDIRECT=https://manage.openshift.com/openshiftio` will force redirecting unapproved users to the registration app. If the env var is not set then the error is returned instead.

Redirect unapproved users to the registration app

---

configuration/configuration.go
log/log.go
log/log_test.go
main.go

Default to log plain text if dev mode, but
allow to log JSON if specified
Required by Performance tests to still log in JSON
while using dev mode features of the server.

Split DeveloperMode and LogFormat

---

controller/work_item_link.go
controller/work_item_link_category.go
controller/work_item_link_type.go
migration/migration.go
migration/sql-files/059-fixed-ids-for-system-link-types-and-categories.sql
workitem/link/category.go
workitem/link/category_repository.go
workitem/link/link_repository.go
workitem/link/link_revision_repository_blackbox_test.go
workitem/link/type.go
workitem/link/type_repository.go

In order to update the link system later I first need to make sure that work item link types and categories that have been created by the system use a pre-defined ID.
As a side-effect this will allow us to remove various loading functions that didn't properly load a category or type by an ID but by a name.
You can now pass in a complete or partial model of a category or type to the repository and have it created for you in the database. Before you needed to pass a bunch of parameters.

Use fixed IDs for system-defined link types and categories

---

codebase/codebase.go
codebase/codebase_test.go
controller/workitem_blackbox_test.go
workitem/simple_type.go
workitem/workitem_repository_blackbox_test.go

ongoing fix for #1165
refactored `/tmp/go/src/github.com/almighty/almighty-core/codebase/codebase.go:18:6: type name will be used as codebase.CodebaseContent by other packages, and that stutters; consider calling this Content`

Refactored codebase package

---

Dockerfile.builder
Dockerfile.deploy

This is a followup for #1273 according to @maxandersen 's [comment](https://github.com/almighty/almighty-core/pull/1273#issuecomment-297939758) about [`MAINTAINER` being deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) and keeping the original author in the file as well.

Replace MAINTAINER with LABEL in Dockerfile

---

.make/test.mk

By default all go test calls will use the `-v` switch when running tests. But if you want you can disable that by unsetting `GO_TEST_VERBOSITY_FLAG=` in the terminal and don't use the switch. This will hide all `testing.T.Log()` outputs.

GO_TEST_VERBOSITY_FLAG to toggle t.Log() output

---

controller/users.go
login/profile.go

Fixes #1256 
- Update KC only if a user property managed in KC is PATCH'd.
- Update KC only if a user property managed in KC is PATCH'd and is different from the existing value.
- Do not pre-fetch KC info. Get KC info only if a property managed in Keycloak was changed.

Remove redundant calls to Keycloak for User Profile PATCH

---

controller/collaborators.go
controller/collaborators_test.go
controller/comments_blackbox_test.go
controller/planner_backlog.go
controller/planner_backlog_blackbox_test.go
controller/search_blackbox_test.go
controller/space.go
controller/space_areas.go
controller/space_areas_blackbox_test.go
controller/space_codebases.go
controller/space_codebases_test.go
controller/space_iterations.go
controller/space_iterations_test.go
controller/space_test.go
controller/work_item_children_blackbox_test.go
controller/work_item_comments_blackbox_test.go
controller/work_item_link_blackbox_test.go
controller/work_item_link_type.go
controller/work_item_link_type_blackbox_test.go
controller/workitem.go
controller/workitem_blackbox_test.go
controller/workitem_test.go
controller/workitemtype.go
controller/workitemtype_blackbox_test.go
design/spaces.go
design/work_item_link_type.go

Also renamed the URL parameter to `SpaceID` to make it more expressive when used in the controllers (especially for endpoints that are children of `/space`)
Fixes #1326

Set the space id type to UUID in the REST API (#1326)

---

migration/migration_blackbox_test.go
migration/sql-files/061-replace-index-space-name.sql
migration/sql-test-files/061-add-duplicate-space-owner-name.sql

Fixed a problem in production due to duplicated space names when we lower case the space name

Rename space name duplicate to space_name-renamed

---

search/search_repository_blackbox_test.go
workitem/workitemtype.go

* Fixes #1353
* Search api returns null value for system.order. This patch aims to fix the issue and return proper expected value of system.order for that workitem.

Ooe search api

---

auth/authz_blackbox_test.go
auth/policy_blackbox_test.go

We upgraded our KC to 3.2.0.CR1-SNAPSHOT in prod-preview and there are some minor changes which affect our remote tests. We can't now add unknown users to policies. KC will reject it.

Fix remote tests after upgrading Keycloak

---

login/service.go
login/service_whitebox_test.go

fixes https://github.com/almighty/almighty-core/issues/1366 
related to https://github.com/fabric8io/fabric8-ui/issues/1442
- tested on sso.prod-preview
- updated username in kc.
- re-logged in ( localhost )
- new username showed up as required.

 Update username on re-login

---

openshift/core.config.yaml

Our current template uses a property that doesn't exist in the config map, that will fail the pod on starting.
FYI: @vpavlin

Add new property to the config map for auth_notapproved_redirect

---

controller/workitem.go
controller/workitem_blackbox_test.go

Fixes https://github.com/almighty/almighty-core/issues/1393
Include parentExist filter in the response.Links URLs
Tests are updated.
Old response links for the request : `http://localhost:8080/api/spaces/{{userSpaceID}}/workitems?filter[parentexists]=false`
```
"links": {
"filters": "http://localhost:8080/api/filters",
"first": "http://localhost:8080/api/spaces/3365d380-62ae-47af-96e7-228b2dcbf401/workitems?page[offset]=0&page[limit]=20",
"last": "http://localhost:8080/api/spaces/3365d380-62ae-47af-96e7-228b2dcbf401/workitems?page[offset]=0&page[limit]=0"
}
```
Above response links do not have `parentExists` filter sticked to it.
New response links for the request : `http://localhost:8080/api/spaces/{{userSpaceID}}/workitems?filter[parentexists]=false`
```
"links": {
"filters": …
```

Make `parentExists` filter sticky on WI links

---

workitem/link/link_repository.go
workitem/link/link_repository_blackbox_test.go

Fixing bug where link would still be counted even after soft-deletion
Also refactored the `workitem/link/link_repository_blackbox_test.go` to make
it more readable (using helper methods to create work items and initializing all
needed data during the setup)
Fixes #1411

Work item link still counted after soft-deletion (#1411)

---

controller/area.go
controller/collaborators_blackbox_test.go
controller/comments.go
controller/filter.go
controller/iteration.go
controller/planner_backlog_blackbox_test.go
controller/space.go
controller/space_areas_blackbox_test.go
controller/space_blackbox_test.go
controller/space_iterations_test.go
controller/user.go
controller/users.go
controller/users_blackbox_test.go
controller/work_item_comments_blackbox_test.go
controller/work_item_link.go
controller/work_item_link_blackbox_test.go
controller/work_item_link_type.go
controller/work_item_link_type_blackbox_test.go
controller/workitem.go
controller/workitem_blackbox_test.go
controller/workitemtype.go
controller/workitemtype_blackbox_test.go
goasupport/conditional_request/generator.go

Let's use some more common terms for the generate interfaces and methods that deal with support for conditional requests.
For instance:
- interface ConditionalResponseEntity -> ConditionalRequestEntity
- method ctx.ConditionalEntity(...) -> ctx.ConditionalRequest(...)
Fixes #1417

Rename generated methods about condition request support (#1417)

---

Makefile

Many times when switching between development branches you need to update the generated code and clean it up before. This little change adds a `regenerate` make target to do exactly that:
1. clean the generated code
2. generate it again

Add "regenerate" make target

---

migration/migration.go
migration/sql-files/062-link-system-preparation.sql

This is a non-invasive change to introduce a new table to store the new link type combinations. Everything else related to links will come later in subsequent PRs.

Prepare database for new link combinations

---

controller/space_codebases.go
controller/space_codebases_test.go

StackId is not saved in DB when creating a space codebase
Fixes https://github.com/almighty/almighty-core/issues/1430

SpaceCodebasesController.Create saves StackId

---

controller/workitem_blackbox_test.go
remoteworkitem/trackeritem_repository_test.go

Also replace a `assert.Nil` with `require.Nil` in another test.
Fixes #1453

Restore removed test (#1453)

---

codebase/codebase.go
codebase/codebase_test.go
controller/codebase.go
controller/codebase_blackbox_test.go
controller/space_codebases.go
controller/space_codebases_test.go

Spacecodebases could be created with nil stackId.
Fixes https://github.com/almighty/almighty-core/issues/1430

fix(space-codebases): panic when stackId is nil

---

migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/066-work_item_links_data_integrity.sql
migration/sql-test-files/066-work_item_links_data_integrity.sql

make the 'link_type_id', 'source_id' and 'target_id' columns not nullable in the 'work_item_links' table
Fixes #1402

Enforce data integrity in the `work_item_links` table (#1402)

---

controller/filters_blackbox_test.go
design/filters.go

Was already unused in the controller. Just removed the param in
the design and applied the change in the test.
Fixes #1140

Remove the unused `filter` param in the `filters` endpoint (#1140)

---

migration/migration_blackbox_test.go
migration/sql-files/067-comment-parentid-uuid.sql
migration/sql-test-files/067-comment-parentid-uuid.sql

Added an SQL statement to migrate the content of the `comment_revisions.comment_parent_id` column
Added some data in the .sql test file
Added the test in the list of tests to execute (!)
Fixes 1476

Data migration failure because of invalid data (#1476)

---

account/init_tenant.go
codebase/codebase.go
convert/equaler.go
workitem/workitem_repository.go
workitem/workitemtype.go

I checked out https://github.com/dominikh/go-tools and I have used `gosimple` on our repo. https://github.com/dominikh/go-tools/tree/master/cmd/gosimple
It shows some minor modifications.
Running this command `for pkg in $(go list -f '{{ join .Deps  "\n"}}' . | grep 'fabric8-wit/[^vendor]'); do gosimple "$pkg"; done` shows all warnings/issues.

small cleanup using gosimple

---

controller/space.go
jsonapi/jsonapi_utility.go
space/space.go

We're tracking one issue that we saw in the SpaceController for the Show operation. The following output is what we got in the logs.
```
July 1st 2017, 19:11:13.209    {"err":"http: request method or response status code does not allow body","fields.msg":{"errors":[{"code":"unknown_error","detail":"http: request method or response status code does not allow body","status":"500","title":"Unknown error"}]},"file":"/tmp/go/src/github.com/fabric8-services/fabric8-wit/jsonapi/error_handler.go","func":"github.com/fabric8-services/fabric8-wit/jsonapi.ErrorHandler.func1.1","level":"error","line":66,"msg":"uncaught error detected in ErrorHandler","pid":1,"pkg":"jsonapi.ErrorHandler.func1","req_id":"c9b5c63b-dce7-4cca-8f9d-91c407796819","time":"2017-07-01 17:11:13"} …
```

Added logs to space controller/repo to log internal or unknown error details

---

account/init_tenant.go
goasupport/forward_requestid.go
goasupport/forward_requestid_test.go

Fixes lack of log coordination between tenant service and core.
client.ContextRequestID != middleware.ContextRequestID as they are stored
under different local keys.

Forward X-Request-ID to tenant service

---

.golint_exclude

Before we would exclude not only `bindata_assetfs.go` but also any file that substitutes the dot (`.`) with a different symbol. This is not critical but the exclude file was simply wrong.

Fix golint exclude file

---

area/area.go
area/area_blackbox_test.go
controller/area_blackbox_test.go
design/areas.go
errors/errors.go
jsonapi/jsonapi_utility.go

Fixes https://github.com/fabric8-services/fabric8-wit/issues/1484
When an area creation with the same name in the same space/path is attempted, return an HTTP 409, instead of HTTP 400 which was earlier being mapped from `BadParameterError`. In this PR, a new `Error` type `DataConflictError` is returned and mapped into a HTTP 409 . 
Note, HTTP 409 is returned for `VersionConflictError` as well.
Error in logs:
```
ERRO[2017-07-17 23:36:31] unable to create child area because an area in the same path already exists  err="pq: duplicate key value violates unique constraint \"areas_name_space_id_path_unique\"" file="/Users/shoubhikbose/dev/alm-core-sbose/src/github.com/fabric8-services/fabric8-wit/area/area.go" func="github.com/fabric8-services/fabric8-wit/area.(*GormAreaRepository).Create" …
```

Add DataConflictError & return HTTP 409 when creating duplicate areas

---

controller/golden_files_test.go

I added some logs to better trace the source of the problem when comparing a golden file with a generated obj. When trying to debug the reason of some failures in my CI jobs, I couldn't get any error logs explaining what was the problem.
```
=== RUN   TestCreate/ok
panic: test executed panic(nil) or runtime.Goexit
goroutine 4674 [running]:
panic(0xe37600, 0xc420c5bf70)
/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4207623c0)
/usr/lib/golang/src/testing/testing.go:579 +0x25d
runtime.Goexit()
/usr/lib/golang/src/runtime/panic.go:340 +0xec
testing.(*common).FailNow(0xc420762180)
/usr/lib/golang/src/testing/testing.go:453 +0x39
testing.(*common).Fatalf(0xc420762180, 0xf54f7a, 0x3, 0xc420d03de8, 0x1, 0x1)
/usr/lib/golang/src/testing/testing.go:496 +0x83 …
```

Added logs in the comparison of objects with the expected golden file

---

controller/space.go

The show action was returning always a body regardless of the conditional request. This body was null or {data: space{yadayada}}, that is what it was causing the issue when returning a status code 304 with a body {data: null}
related to: https://github.com/fabric8-services/fabric8-wit/issues/1508

Fixed space show action to avoid multiple header calls

---

controller/comments.go
controller/comments_blackbox_test.go
design/comments.go

Breaking changes block Core from being pushed to prod.
Related to #1380
Note: @kwk @DhritiShikhar

Keep old structure around until clients are updated.

---

.codecov.yml

We are not writing tests to cover the design package.

ignore the "design" package from coverage

---

codebase/che/client.go
controller/codebase.go
design/codebases.go

see the comment - https://github.com/fabric8-services/fabric8-wit/issues/1506
Providing new endpoints for starting che server asyncronously and getting it's state:
`PATCH api/codebases/che/start`
`GET     api/codebases/che/state`
https://github.com/fabric8-services/fabric8-wit/issues/1506

fabric8-wit #1506: Using Async CheStarter API from Codebases and exposing API for starting and getting che server state

---

configuration/configuration.go
controller/area.go
controller/comments.go
controller/iteration.go
controller/space.go
controller/test-files/work_item_type/show/not_modified_using_if_modified_since_header.headers.golden.json
controller/test-files/work_item_type/show/not_modified_using_ifnonematch_header.headers.golden.json
controller/test-files/work_item_type/show/ok.headers.golden.json
controller/test-files/work_item_type/show/ok_using_expired_etag_header.headers.golden.json
controller/test-files/work_item_type/show/ok_using_expired_lastmodified_header.headers.golden.json
controller/work_item_link.go
controller/work_item_link_type.go
controller/work_item_relationships_links.go
controller/workitem.go
controller/workitemtype.go
controller/workitemtype_blackbox_test.go

Nowadays we set the same max-age for a single resource or a list of resources. Therefore, this PR aims to define a different max-age for a single resource.

Add control cache max-age for single resources

---

controller/work_item_type_group.go
controller/work_item_type_group_blackbox_test.go
workitem/typegroup/typegroup.go

TypeGroup should return "Execution" as well.
Now the following object is added to the list.
```
{
"group": "execution",
"level": [
2,
0
],
"name": "Execution",
"wit_collection": [
"bbf35418-04b6-426c-a60b-7f80beb0b624"
]
}
```
Tests are updated as well.

Add "Execution" to the TypeGroup list.

---

controller/work_item_link_blackbox_test.go
design/work_item_link.go
design/work_item_link_category.go
design/work_item_link_type.go
workitem/link/category_repository.go
workitem/link/link_repository.go
workitem/link/type_repository.go

In addition to the issues https://github.com/fabric8-services/fabric8-wit/issues/1485, we adapted the code in other models to retunr 409 conflicts when an item already exists.

Return 409 errors whenever the item already exists

---

account/init_tenant.go
controller/user_service.go
design/user_service.go
main.go

Gives other services a common view of the Tenant
namespaces in use for a given user.
Related to openshiftio/openshift.io#283

Expose tenant service Show

---

controller/iteration_blackbox_test.go
controller/search_blackbox_test.go
iteration/iteration.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/071-iteration-related-changes.sql
migration/sql-test-files/071-iteration-related-changes.sql

Added a `relationships_changed_at` column in the `iterations` table to record
the timestamp of changes in work items when they are linked/unlinked to an
iterations, or soft-deleted.
The filling of the `relationships_changed_at` is performed by a
set of triggers and functions.
Added tests to verify that the `ETag` and `Last-Modified` response headers
change when a work item is added to/removed from an iteration.

Etag for iterations does not change when number of attached WIs changed (#1587)

---

controller/login.go
controller/login_test.go
design/auth.go

If `scope=offline_access` param is added to the authentication request then the offline token will be issued instead of a regular refresh token.
Example: `api.openshift.io/api/login/authorize?scope=offline_access`
Fixes https://github.com/fabric8-services/fabric8-auth/issues/69

Support offline token generation

---

search/search_repository_whitebox_test.go

... because we deleted all created entries with `s.clean = cleaner.DeleteCreatedEntities(s.DB)` at the end of each test anyway.

Remove deferred deletion calls

---

test/testfixture/customize_entity_callbacks.go
test/testfixture/make_functions.go
test/testfixture/recipe_funcs.go
test/testfixture/testfixture.go

testfixture: Make recipe-function callbacks typesafe without breaking compatibility and rename callback to func

---

controller/search_blackbox_test.go
search/query_language_whitebox_test.go
search/search_repository.go

Fixes #1609
Filter query with assignee = null in the top-level produce 500 error

Top-level assignee = null produce error in WIQL

---

token/token.go
token/token_test.go

Auth will be communicating with WIT using service account tokens . 
( https://github.com/fabric8-services/fabric8-auth/commit/8d7f5a3646974ae8820893d75c29f3f5e9b1ff66#diff-6b1a7621961d1f6fe7463db59c5afef5R374 ) 
This PR adds a method to detect if the token is a service account token ( and not a user token )

Validate if token is associated with a service account

---

account/identity_blackbox_test.go
account/user_blackbox_test.go
auth/state_blackbox_test.go
comment/comment_repository_blackbox_test.go
comment/comment_revision_repository_blackbox_test.go
controller/comments_blackbox_test.go
controller/planner_backlog_blackbox_test.go
controller/planner_backlog_test.go
controller/search_blackbox_test.go
controller/space_iterations_test.go
controller/work_item_children_blackbox_test.go
controller/work_item_link_blackbox_test.go
controller/work_item_link_type_blackbox_test.go
controller/work_item_type_group_blackbox_test.go
controller/workitem_blackbox_test.go
controller/workitemtype_blackbox_test.go
gormtestsupport/db_test_suite.go
login/service_blackbox_test.go
remoteworkitem/tracker_repository_blackbox_test.go
remoteworkitem/trackeritem_repository_test.go
remoteworkitem/trackerquery_repository_blackbox_test.go
search/search_repository_blackbox_test.go
search/search_repository_whitebox_test.go
workitem/link/link_repository_blackbox_test.go
workitem/link/link_revision_repository_blackbox_test.go
workitem/workitem_repository_blackbox_test.go
workitem/workitem_revision_repository_blackbox_test.go
workitem/workitemtype_repository_blackbox_test.go

Now, each test suite sets up a new migration context and populates the
database with common values.
Also, the SetupTest() now automatically sets up a clean function that is
executed at TearDownTest(). No custom suite implementation needs to do
this manually now. For this to work, if you override SetupTest() you
need to call the embedded function manually.

simplify db-test-suite setup

---

controller/search_blackbox_test.go
search/search_repository.go

Allow the user to filter on label IDs, similar to state/iteration/assignee etc.
To search work items which are having label X and are in space Y:
```
{  
"$AND":[  
{  
"space":"a8bb67dc-31e9-4384-bebf-837441f41d7c"
},
{  
"label":"d00b263e-cba8-49b9-9e7b-ec365f92186c"
}
]
}
```
To search work items which are NOT having label X and are in space Y:
```
{  
"$AND":[  
{  
"space":"da35e7d3-9b6c-49c7-9afc-0094d04586a4"
},
{  
"label":"d00b263e-cba8-49b9-9e7b-ec365f92186c",
"negate":true
}
]
}
```
To search work items which are having labels IN (A, B)
```
{  
"$AND":[  
{  
"space":"da35e7d3-9b6c-49c7-9afc-0094d04586a4"
},
{  
"label":{  
"$IN":[  
"5a410c6a-b8a9-48a6-91c8-e32b23e82bf7",
"d00b263e-cba8-49b9-9e7b-ec365f92186c"
]
}
}
]
}
```

Filter on label

---

README.adoc

This document assume the GOPATH is set to a single directory.
Technically it is possible to set multiple directories as the
value for GOPATH environment variable [1].  With multiple
diretctories in the GOPATH, the commands given in the document
will not work as expected.
[1]: https://github.com/golang/go/wiki/GOPATH

GOPATH should be set to a single directory

---

Makefile
configuration/configuration.go
docker-compose.yml

This PR adds new WIT dependencies to the docker compose file on the Auth service and its DB.
So, `make dev` now creates and starts three containers:
- WIT DB
- Auth DB
- Auth
We can't relay on prod-preview auth only because auth needs to create a new user in WIT during login. Otherwise WIT won't have any user in the WIT DB. The workflow is the following:
- User logs into Auth via <auth>/login (if wit api is used then <wit>/login/authorize will redirect to <auth>/login)
- Auth redirects to KC to login and after successful login will creates a new user in the Auth DB and will call WIT to create a new user in WIT. So, Auth need to know the WIT URL.
`make dev` configures all containers so, no additional configuration needed by default.

Include auth service in make dev

---

.make/test.mk
Dockerfile.builder

This should greatly minimize the test output in our CI. I've removed the `-v` switch from `go test` but you can re-enable it by running `GO_TEST_VERBOSITY_FLAG=-v make test-integration-no-coverage` or any other test target.
Apart from that I've set the log level in tests to a high level (`error`). This can be overridden as well.
For example: `GO_TEST_VERBOSITY_FLAG=-v F8_LOG_LEVEL=info make test-integration-no-coverage`

Reduce test output to minimum

---

controller/search_spaces_blackbox_test.go
controller/space_blackbox_test.go
controller/work_item_children_blackbox_test.go
space/space.go

Using the `Last-Modified` response header when possible.
Also, prefix some spaces to create to avoid collision with existing data during search.
Also, making sure that the list of spaces is always ordered by
`updated_at DESC` to get the most recents spaces first.

Stabilize/disable tests related to if_modified_since_header (#1655)

---

docker-compose.yml

This fixes fabric8-wit docker image URL and resolves https://github.com/fabric8-services/fabric8-wit/issues/1679

Update fabric8-wit docker image URL in docker-compose.yml

---

auth/resource.go
configuration/configuration.go
controller/collaborators.go
controller/login.go
controller/search.go
controller/users.go
rest/proxy/proxy.go

We have to use the short name of Auth service (auth) in our OS clusters instead of referring to the full Auth URL like https://auth.openshift.io when using reverse proxy. Otherwise the OS routers go crazy and route the traffic which targets auth to the same WIT. So, it's a loop.
Fixes https://github.com/fabric8-services/fabric8-wit/issues/1696

Fix a loop when proxy is used in OS env

---

rest/proxy/proxy.go

This fixes the issue of proxied responses received from Auth has `http` links for all requests , in the related links section. https://github.com/fabric8-services/fabric8-wit/issues/1702
This PR sets the `X-Forwarded-Proto` while starting the proxy request, which would be picked up by the Auth service: 
https://github.com/fabric8-services/fabric8-auth/blob/master/rest/url.go#L20
```
xForwardProto := req.Header.Get("X-Forwarded-Proto")
if xForwardProto != "" {		
scheme = xForwardProto
}
```

Pass on the original scheme

---

docker-compose.yml

remove the `network_mode` option in the containers
specify the host/port for the `auth` service to connect to its `db`, using the
internal Postgres port (5432) and using the container's hostname (the container
name itself)
Fixes #1705

`make dev` fails to start because of container connection issue on macOS (#1705)

---

docker-compose.macos.yml

keep the previous changes in `docker-compose.macos.yml` for now
revert the changes as they break on Linux
Fixes #1705

'make dev' fails to start because of container connection issue on macOS (#1705)

---

configuration/configuration.go

`make dev` now starts Auth service, so we don't have to disable authorization in dev mode by default anymore.

Enable Authorization by default

---

controller/iteration.go
controller/iteration_blackbox_test.go

Fixes: https://openshift.io/openshiftio/openshiftio/plan/detail/1555

Save description when new iteration created

---

controller/search_blackbox_test.go
migration/migration.go
workitem/link/link_repository.go
workitem/link/link_repository_blackbox_test.go
workitem/link/topology.go

Based on [this discussion](https://chat.openshift.io/developers/pl/gqwxx3mj13fejfdwqqc61mrwba) we decided to make the parenting link type have a tree topology.
See also https://github.com/fabric8-ui/fabric8-planner/pull/2291#issuecomment-339278719

Make the parenting link type have a tree-topology

---

controller/search_blackbox_test.go
controller/test-files/search/search_codebase_per_url_multi_match.json
controller/test-files/search/search_codebase_per_url_single_match.json

Use a different ordering to make sure that the test pass no matter which
ID has been allocated to the codebases and their spaces.
Ordering the codebases in `data` by the ID of their related space, and
ordering the `included` spaces by their ID ensures that all data are in
such an order, than replacing all ID with incremental UUIDs in the files
still works.
Fixes openshiftio/openshift.io#1246

Fix test failures with golden file (openshiftio/openshift.io#1246)

---

codebase/codebase.go
codebase/codebase_test.go
controller/codebase.go
controller/codebase_blackbox_test.go
controller/test-files/codebase/show/ok_with_stackId.golden.json
controller/test-files/codebase/show/ok_without_stackId.golden.json
design/codebases.go

Endpoint and repository method to remove a codebase given its `ID`.
Fixes #1673

Codebase removal (#1673)

---

controller/iteration_blackbox_test.go
controller/test-files/iteration/create/ok_create_child.golden.json

`Use old date for test case`
There was a test having `startAt` and `endAt` with 4th Nov and 25th Nov 2017 respectively. We added a logic that returns `User Active` flag calculated on the fly using those dates and hence it started giving value as `True` since 4th Nov 2017. But the golden file was created with value `False`, hence the failure.
Lesson learned: Use old dates while writing tests.

Fix failing test for create-iteration

---

controller/iteration.go
controller/iteration_blackbox_test.go
controller/test-files/iteration/create/ok_create_child_ID_paylod.golden.json

Added a test to verify that when create-iteration payload has ID in it then it will be used as PK.

test to verify that create-child-iteration-API uses payload.ID correctly

---

configuration/configuration.go
glide.lock
glide.yaml
main.go

Metrics are exposed under /metrics and the used port
can be controlled via F8_METRICS_HTTP_ADDRESS. By
default same port as F8_HTTP_ADDRESS is used.

Expose basic go runtime metrics via Prometheus

---

.make/Makefile.lnx
Makefile
docker-compose.macos.yml

Using `docker.for.mac.localhost` as the hostname to connect from a container (auth)
to the WIT service running on the host machine, when running on macOS.
Also, use the `docker-compose.macos.yml` in `make dev` when `uname -r` is `Darwin` (macOS).
Fixes #1707

`auth` docker container cannot connect to `wit` running on host on macOS (#1707)

---

application/transaction_test.go
area/area_blackbox_test.go
codebase/codebase_test.go
controller/area_blackbox_test.go
controller/codebase_blackbox_test.go
controller/filters_blackbox_test.go
controller/iteration_blackbox_test.go
controller/label_blackbox_test.go
controller/namedspaces_test.go
controller/search_spaces_blackbox_test.go
controller/space_codebases_test.go
controller/status_test.go
controller/trackerquery_blackbox_test.go
controller/workitem_whitebox_test.go
iteration/iteration_test.go
label/label_blackbox_test.go
remoteworkitem/tracker_repository_test.go
remoteworkitem/trackeritem_test.go
remoteworkitem/trackerquery_repository_test.go
test/testfixture/testfixture_test.go

Test suites don't need to define the own `clean` function. The `DBTestSuite` takes care of this in setup and teardown phase.

Use DBTestSuite cleanup

---

test/testfixture/make_functions.go

Prefixed the path of any work item type generated by the test fixture with `workitem.SystemPlannerItem`. This is needed when we want to find work items that were generated by a test fixture as planner items.

prefix paths of work item types generated by test fixture

---

controller/namedspaces_test.go
controller/space.go
controller/space_blackbox_test.go
controller/test-files/search/search_codebase_per_url_multi_match.json
controller/test-files/search/search_codebase_per_url_single_match.json
controller/test-files/space/show_space_ok.golden.json
controller/work_item_children_blackbox_test.go
controller/work_item_link_blackbox_test.go
controller/work_item_link_type_blackbox_test.go
controller/workitem_blackbox_test.go
controller/workitemtype_blackbox_test.go

Added a call to `rest.AbsoluteURL()` when generating the `owned-by` relationship's relative URL
Refactored the test on the space controller to organize tests with subtests, using a "golden file"
to validate the response to "show" a space, which includes the verification that all relationships'URL
are absolute.
Fixes openshiftio/openshift.io#1310

`relationships.owned-by.related` URL must be absolute when showing a space (openshiftio/openshift.io#1310)

---

test/login.go
token/token.go
token/token_test.go

For consistency sake.
We are using github repo name as service account names.

Rename auth Service Account to 'fabric8-auth'

---

account/init_tenant.go
codebase/che/client.go
controller/codebase.go
controller/codebase_blackbox_test.go
main.go
test/data/che/che_delete_codebase_workspaces.failure.yaml
test/data/che/che_delete_codebase_workspaces.ok.yaml
test/http_monitor/http_transport_monitor.go

refactored the code to be able to use a custom/mock HTTP client
in the tests, using `go-vcr` to respond to HTTP requests with a
predefined response.
Fixes #1749

codebase's workspace deletion (#1749)

---

controller/search_blackbox_test.go
controller/test-files/search/show/filter_assignee_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_assignee_null_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_update_work_item.golden.json
test/testfixture/customize_entity_funcs.go
test/testfixture/query_functions.go

Before the test didn't filter by space ID. I should say, it specified a space ID in their call to `test.ShowSearchOK()` but that `spaceID` is  internally ignored if a filter expression is also given.
I've created more than one work item per test and changed the query to an `AND` filter which includes the old query and the new *by-space-query*.
Some supporting changes I've done are these:
* Added test fixture customization functions:
* `SetWorkItemField` this lets a user set any field in a work item by giving its key as the first argument. We validated the input based on the work item's type definition and return an error if a wrong argument is passed.
* Added test fixture query functions:
* `WorkItemTypeByID`

Improve TestSearchController.TestUpdateWorkItem() test

---

controller/golden_files_test.go
controller/test-files/codebase/show/ok_with_stackId.golden.json
controller/test-files/codebase/show/ok_without_stackId.golden.json
controller/test-files/iteration/create/bad_request_unknown_parent.golden.json
controller/test-files/iteration/create/conflict_for_same_name.golden.json
controller/test-files/iteration/create/ok_create_child.golden.json
controller/test-files/iteration/create/ok_create_child_ID_paylod.golden.json
controller/test-files/search/search_codebase_per_url_multi_match.json
controller/test-files/search/search_codebase_per_url_single_match.json
controller/test-files/search/show/filter_assignee_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_assignee_null_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_update_work_item.golden.json
controller/test-files/space/show_space_ok.golden.json

When you update a golden file using `go test -update` it will contain a set of new random UUIDs.
Those new UUIDs appear as changes inside a commit if you just do `git add myGoldenFile.json`. This clutters the commit and hides the real change that might have appeared in your commit.
I want you to be able to focus on the real changes to the API and not on some random UUIDs.
That is why a golden file that is generated with `controller.compareWithGoldenUUIDAgnostic()` will now have all UUIDs replaced with  "00000000-0000-0000-0000-000000000001", "00000000-0000-0000-0000-000000000002", ..., "00000000-0000-0000-0000-00000000000N" and so on.
The next time you update your golden files will be much easier.

UUID agnostic golden file comparison replaces real UUIDs during update

---

controller/test-files/search/show/filter_assignee_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_assignee_null_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_show_after_update_work_item.golden.json
controller/test-files/search/show/filter_label_null_update_work_item.golden.json
controller/workitem.go
design/workitems.go

I've created a long missing `related` link to a new `workItemLinks` relationship in the work item response.
With this change, the UI no longer needs to construct the URL to fetch links for a work item manually.

Add "workItemLinks" relationship on work item response

---

controller/test-files/work_item_link/create/ok.golden.json
controller/test-files/work_item_link/create/ok.headers.golden.json
controller/test-files/work_item_link/list/ok.golden.json
controller/test-files/work_item_link/show/not_found.errors.golden.json
controller/test-files/work_item_link/show/ok.golden.json
controller/test-files/work_item_link/show/ok.headers.golden.json
controller/work_item_link.go
controller/work_item_link_blackbox_test.go
controller/work_item_relationships_links.go
design/work_item_link.go
design/work_item_link_type.go
search/search_repository.go
test/testfixture/make_functions.go
test/testfixture/recipe_funcs.go

Most of the change is due to golden files being added.
Apart from that I've removed all the ugliness of test setup and have grouped tests into sub-tests under their proper parent test (e.g. `TestCreate`, `TestList`, `TestShow`, `TestUpdate`, `TestDelete`).
In responses for work item links I've removed the work item link category from the included section as well.

Rework controller link tests

---

controller/test-files/work_item_type_group/list/ok.witg.golden.json
controller/test-files/work_item_type_group/show/ok.witg.golden.json
controller/work_item_type_group.go
controller/work_item_type_group_blackbox_test.go
controller/work_item_type_groups.go
design/work_item_type_group.go

Before you could view a WIT group by hitting
```
/api/spacetemplates/<SPACE_TEMPLATE_ID>/workitemtypegroups/<WIT_GROUP_ID>
```
That level of nesting should not be needed becaus the `<WIT_GROUP_ID>` is good enough to filter on a work item type group. Now you can view a group with
```
/api/workitemtypegroups/<WIT_GROUP_ID>
```
The *list* action is still located under the space template endpoint:
```
/api/spacetemplates/<SPACE_TEMPLATE_ID>/workitemtypegroups
```

Made show action for WIT group standalone

---

controller/space.go
controller/test-files/search/search_codebase_per_url_multi_match.json
controller/test-files/search/search_codebase_per_url_single_match.json
controller/test-files/space/show_space_ok.golden.json

And remove an obsolete and unused links entry for WIT groups.
Previously the link to list all work item type groups used to be
```
http:///api/spacetemplates/00000000-0000-0000-0000-000000000002/workitemtypegroups/
```
Now it is
```
http:///api/spacetemplates/00000000-0000-0000-0000-000000000002/workitemtypegroups
```
NOTICE: the missing trailing `/`.

Fix link to WIT groups in space

---

controller/work_item_link.go

We didn't use a transaction to wrap the link creation before. This is required.

Use transaction when creating a link

---

controller/work_item_children_blackbox_test.go
controller/work_item_link.go
controller/work_item_link_blackbox_test.go
controller/work_item_relationships_links.go
design/work_item_link.go
workitem/link/link_repository.go
workitem/link/link_repository_blackbox_test.go
workitem/link/link_revision.go
workitem/link/link_revision_repository_blackbox_test.go

Removes **Update**/**Save** method of work item link repository and all controllers.
The only permitted actions to a link once created are:
* **delete**
* **show**
* **list**
In order to mimic the **update** behavior you have to **delete and recreate** a link with different settings (e.g. with a different link type). This is needed in order for us to maintain a valid *topology*.
Also the `Create` method has been removed from the `/api/workitems/<ID>/relationships/links` endpoint. Only the `List` method remains for this endpoint.

Link updates

---

glide.lock

Updated to 1.0.4 (specified hash)
Ref: https://github.com/sirupsen/logrus/commits/master

update logrus version

---

controller/area.go
controller/area_blackbox_test.go
controller/codebase.go
controller/codebase_blackbox_test.go
controller/comments.go
controller/comments_blackbox_test.go
controller/iteration_blackbox_test.go
controller/space_areas_blackbox_test.go
controller/workitem.go
controller/workitemtype.go
ptr/doc.go
ptr/ptr.go

Package `ptr` provides functions to create on the fly pointer values for some built-in types. This might seem stupid at first but in our codebase we have a lot of places in which we just need to create variable just to get the pointer. That clutters the code a lot and causes distraction. Most of the time those strings are just throw-away constants and the pointer "is not really important later".
I've also changed the function `newCreateChildAreaPayload` to accept a `string` rather than a `*string` because in 99% of the time the string is not nil.

introduce "ptr" package for on-the-fly pointer values

---

controller/golden_files_test.go

When using the `-update` switch to `go test` this will auto-create the directory and potential parent directories in order for you to write golden test to. Just use 
```go
compareWithGoldenUUIDAgnostic(t, filepath.Join("foo", "bar", "foobar.golden.json"), payload)
```
and `/foo/bar` will be created with `0777` permissions.

auto-create dir to write golden file to

---

test/testfixture/customize_entity_funcs.go
test/testfixture/testfixture_test.go

Here's a much easier way to create link trees without the hassle of big switch statements. I've used two link chains in order to demonstrate that you can create disjoint links as well.
```go
chain1 := tf.LinkChain("A", "B", "C")
chain2 := tf.LinkChain("D", "E", "F", "G")
fxt := tf.NewTestFixture(t, s.DB,
tf.WorkItemLinkTypes(1, tf.SetTopologies(link.TopologyDependency)),
tf.WorkItems(7, tf.SetWorkItemTitles("A", "B", "C", "D", "E", "F", "G")),
tf.WorkItemLinksCustom(5, tf.BuildLinks(append(chain1, chain2...)...)),
)
```
Before you would have to write this (which is still supported):
```go
fxt = tf.NewTestFixture(t, s.DB,
tf.WorkItemLinkTypes(1, tf.SetTopologies(link.TopologyDependency)),
tf.WorkItems(7, tf.SetWorkItemTitles("A", "B", "C", "D", "E", "F", "G")),
tf.WorkItemLinksCustom(5, …
```

Added simplification for creating link chains in test

---

id/doc.go
id/map.go
id/map_blackbox_test.go
id/slice.go
id/slice_blackbox_test.go

The `id` package defines these handy containers for UUIDs:
```go
type Slice []uuid.UUID
type Map map[uuid.UUID]struct{}
```
In recent tests that I discovered that I wrote a lot of duplicate code for dealing with UUIDs. That's where `Slice` and `Map` come in.
`Map` comes with these functions:
```go
func MapFromSlice(s Slice) Map
func (m Map) ToSlice() Slice
func (m Map) Copy() Map
func (m Map) ToString(sep string, fn ...func(ID uuid.UUID) string) string
func (m Map) String() string
```
Slice comes with these functions:
```go
func (s Slice) Diff(b Slice) Slice
func (s Slice) Sub(b Slice) Slice
func (s Slice) Unique(b Slice) Slice
func (s Slice) ToString(sep string, fn ...func(ID uuid.UUID) string) string
func (s Slice) String() string
```

Added "id" package with "Slice" and "Map" of UUIDs

---

controller/search.go
controller/search_blackbox_test.go
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true.res.golden.json

Before I treated the `interface{}` object in the `"included"` response of the search `show` action as `*app.WorkItem` __pointers__. But it turned out that they are indeed just `app.WorkItem` __objects__. That is why my `WorkItemInterfaceSlice.Less` implementation was wrong. It can now handle pointers as well as values the same.

Fix sorting of WorkItemInterfaceSlice

---

kubernetes/apps_kubeclient.go

This small fix ensures that pod counts will be returned even if there are no running pods.  This allows the UI to display a '0' pod count, which the user can then scale to 1 or higher.
Before:
$ curl -H "Authorization: Bearer $PROD" http://localhost:8080/api/apps/spaces/9c21a121-3c9e-49e3-9ce4-afa8593d34da
{"data":{"applications":[{"name":"stooke-test1","pipeline":[]}]}}
After:
$ curl -H "Authorization: Bearer $PROD" http://localhost:8080/api/apps/spaces/9c21a121-3c9e-49e3-9ce4-afa8593d34da
{"data":{"applications":[{"name":"stooke-test1","pipeline":[{"name":"run","pods":{"running":0,"starting":0,"stopping":0,"total":0},"version":"1.0.2"},{"name":"stage","pods":{"running":0,"starting":0,"stopping":0,"total":0},"version":"1.0.2"}]}]}}

ensure pod status is returned even when no pods are running

---

controller/apps.go
controller/apps_osioclient.go
design/apps.go
kubernetesV1/apps_kubeclient.go
kubernetesV1/apps_kubeclient_blackbox_test.go
kubernetesV1/apps_metrics.go
kubernetesV1/apps_metrics_blackbox_test.go

This PR addresses issue #1867.
Various implementation files, directories, function and type names are renamed so that the JSON-API breaking change can co-exist with the old API.  
After the UI has been updated (and deployed all the way to production) to use the new JSON-API endpoints (which are not yet merged into WIT/master), then this code can be deleted in a future PR.

Ensure /apps API old and new formats can run in same WIT

---

area/area.go
area/area_blackbox_test.go
iteration/iteration.go
iteration/iteration_test.go

fixes https://github.com/openshiftio/openshift.io/issues/2040
If we call LoadMultiple from area/area.go or iteration/iteration.go with an empty slice of IDs then the following query is executed `SELECT * FROM "areas"  WHERE "areas"."deleted_at" IS NULL` which in turn loads the whole table unnecessarily.

fix loadMultiple functions from area & iteration repo

---

controller/apps.go
design/apps.go

This patch renames some more types that were missed in PR #1868
When merging the JSON-API code, some more duplicate type names / function names were found.

Eliminate some more duplicate names for deployments API refactoring

---

controller/user_service.go
design/user_service.go
glide.lock
glide.yaml

URLs used by UI, Proxy, Che etc to handle a multi-cluster
setup.
Fixes #1859

Expose additional cluster URLs from tenant service

---

controller/apps.go
controller/apps_blackbox_test.go
kubernetesV1/apps_kubeclient.go
kubernetesV1/apps_kubeclient_blackbox_test.go
kubernetesV1/apps_metrics.go
kubernetesV1/apps_metrics_blackbox_test.go

This PR fixes a resource leak caused by creating a new Hawkular go-routine each time the Deployments API is invoked. See #https://github.com/openshiftio/openshift.io/issues/2087 for more details.
The main change is adding a new Close method to KubeClientInterface, which the apps controller uses when finished with a particular client instance. I have added tests to verify that each Deployments API method invokes Close before returning.

Add close method to release Hawkular resources

---

controller/search.go
controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/include_children.res.payload.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=true.res.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B_with_tree-view=true.res.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true.res.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/D_with_tree-view=true.res.golden.json
design/media_types.go

The UI team asked for this because since 3e88355c2b8a081660d95b923e31e3a6b4e00520 we put ancestors and siblings to matches in the "included" array. The ancestors will be shown expanded in the UI whereas the siblings don't. But that's just UI work.
Co-authored-by: Pranav Gore <pranavgore09@gmail.com>

List ancestor IDs in search results

---

workitem/link/link_repository.go
workitem/link/link_repository_blackbox_test.go

* fixes #1846
* Adds tests for workitem children reorder

Returns workitem children list according to order of execution

---

controller/apps.go
controller/apps_blackbox_test.go
controller/deployments.go
controller/deployments_blackbox_test.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
kubernetes/deployments_metrics.go
kubernetes/deployments_metrics_blackbox_test.go

A new JSON-API compliant version of the "apps" controller named "deployments" was recently added by https://github.com/fabric8-services/fabric8-wit/pull/1870. This new controller also needs the fix to properly release Hawkular resources added by https://github.com/fabric8-services/fabric8-wit/pull/1875.
This PR is simply a port of the above fix, with name conflicts resolved using the "V1" suffix used throughout the older apps controller.

Port Hawkular close fix to deployments controller

---

workitem/link/link_repository_blackbox_test.go
workitem/workitem_repository.go

Before reordering was only tested with 2 items. The problem with this is that there were two pairs of operations that have the same effect:
1. move above / move to top
2. move below / move to bottom
In order to test all four operations separately I needed to have three work items to move around.

Simplify child reorder tests

---

controller/test-files/work_item_type_group/list/ok.witg.golden.json
controller/test-files/work_item_type_group/show/ok.witg.golden.json
controller/work_item_type_group.go
design/work_item_type_group.go
workitem/typegroup.go

This removes the `defaultType`, `nextGroup` and `prevGroup` relationships from a work item type group. This will make it easier to persist type groups in the database later.

TypeGroup: Remove unused relationships

---

.make/docker.mk
Dockerfile.builder
cico_run_coverage.sh

@aslakknutsen observed quite an improvement in speed when running tests with coverage with Golang 1.10:
make target | Go 1.8.4 (current CentOS version) | Go 1.10 (version from golang website)
-----| ------------ | -------------
`test-unit-no-coverage` | 42s | 13s
`test-unit` | 20m38s | 48s
That's why i've introduced a [docker build arg](https://docs.docker.com/engine/reference/builder/#arg) `USE_GO_VERSION_FROM_WEBSITE`. It defaults to `0` and is only set to `1` through an environment variable when running `cico_run_coverage.sh`.
Running the coverage calculation with a newer Go version is fine because we proof correctness of tests with the current CentOS version of Go already.
@aslakknutsen I'm not sure you've tweaked the test runs as well, so please let me know if more is needed.

Use Go 1.10 version from website when running tests with coverage

---

README.adoc

Tested locally and was able to run wit against prod-preview

Updating obsolete local prod-preview setup instructions

---

codebase/che/client.go
codebase/che/client_test.go
controller/codebase.go
controller/test-files/codebase/show/ok_with_stackId.golden.json
controller/test-files/codebase/show/ok_without_auth.golden.json
controller/test-files/codebase/show/ok_without_stackId.golden.json
controller/test-files/search/search_codebase_per_url_multi_match.json
controller/test-files/search/search_codebase_per_url_single_match.json
design/codebases.go

Deprecating  '/:codebaseID/edit' Adding '/:codebaseID/workspaces' and returning more workspace data (id / links)
https://github.com/openshiftio/openshift.io/issues/1439
Should be merged together with PR to UI: https://github.com/fabric8-ui/fabric8-ui/pull/2521
#

openshift.io #1439 Deprecating  '/:codebaseID/edit' Adding '/:codebaseID/workspaces' and returning more workspace data (id / links)

---

Dockerfile.builder

Fixes this error on CI build:
```
/bin/sh: bc: command not found
```
This supersedes #1907 because this PR does only one small thing compared to #1907.

Add missing "bc" to docker build container

---

search/search_repository.go
search/search_repository_blackbox_test.go
workitem/expression_compiler.go
workitem/expression_compiler_blackbox_test.go

We have two places in `search.Query.generateExpression()` where we inspect a field name. One was missing in #1912. Now I've added a test to ensure it is covered.
Fixes:
Bad value for parameter 'key not found': 'iteration.name'
Also fixes the following follow-up problem by adding the explicit table name to the resolved column names in the expression compiler:
pq: column reference "space_id" is ambiguous

search: fixup for #1912

---

Dockerfile.deploy

This will help reduce build cycle while doing development in containers.
Right now the way COPY commands are placed require all subsequent layers
to be built. Which has a time consuming yum install as well.

move COPY cmds in Dockerfile.deploy to end

---

search/search_repository.go

`typegroup.name` instead of `$WITGROUP` will be the new field to query for typegroups and the special handling for wit groups in the `search_repository.go` will go away soon. But in order to give the UI a chance to replace `$WITGROUP` with `typegroup.name` I wanted to get this change in as early as possible.

Replace $WITGROUP with typegroup.name

---

search/search_repository.go

Reverts fabric8-services/fabric8-wit#1929
Broke preview and blocking prod rollout:
```
error listing work items for expression '{"$AND":[{"space":{"$EQ":"8764603a-6e8a-4cfb-be9f-26abbb09534a"}},{"$WITGROUP":{"$EQ":"Experiences"}}],"$OPTS":{"tree-view":true}}': failed to parse filter string: Bad value for parameter 'key not found': '$WITGROUP'
```

Revert "Replace $WITGROUP with typegroup.name"

---

design/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go

This PR addresses the backend work for [1], adding deployment specific quota information.
This PR is complete, but relies on [2], which is included as the first commit in this PR. When [2] is merged, that commit will be removed, and this PR will be rebased onto master.
Edit:
[2] has been merged and removed from this PR. This PR is ready to merge.
[1] https://github.com/openshiftio/openshift.io/issues/2183
[2] https://github.com/fabric8-services/fabric8-wit/pull/1894

Add Deployment quotas data

---

controller/search_blackbox_test.go
search/query_language_whitebox_test.go
search/search_repository.go
search/search_repository_whitebox_test.go

This addresses the backward compatibility problems I introduced with #1929 (was reverted meanwhile).
`typegroup.name` instead of `$WITGROUP` will be the new field to query for typegroups and the special handling for wit groups in the `search_repository.go` will go away soon.
In #1929 I removed support for `$WITGROUP` but here I kept it an only added support for an additional `typegroup.name`. I've modified all tests that deal with `$WITGROUP` to now test for `typegroup.name` as well.

fix(search): support old "$WITGROUP" as well as new "typegroup.name" fields

---

workitem/expression_compiler.go
workitem/expression_compiler_blackbox_test.go
workitem/table_join.go
workitem/table_join_blackbox_test.go

This change consist of three parts:
1. The `workitem.Compile` function now returns a slice of ordered table join pointers instead of an unordered map. I analyse all joins (depth first) and begin with the joins that don't activate another join. I end with joins that activate joins that came before them. Essentially, this is not possible in SQL and this first part addresses exactly this problem:
```sql
SELECT foo.id FROM foo
LEFT JOIN a ON a.id = b.id -- b is not yet known here (move down in order to fix this)
LEFT JOIN b ON b.id = foo.id;
```
2. One can delegate the handling of fields with a certain prefix to another table join now. This is needed in my space templates branch in order to get a correct order when a access to a field is required over multiple joins and the joins depend on …

WIP: Ordered TableJoins with delegation and optional where

---

kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
kubernetes/deployments_kubeclient_whitebox_test.go
test/kubernetes/replicationcontroller-scaled-down.json

This PR addresses https://github.com/openshiftio/openshift.io/issues/2356. Currently, if there are multiple replication controllers present for a given deployment config, we always use the most recently created one. This PR changes this to use the following algorithm which is also used by the OpenShift web console.
1. Consider replication controllers that are in-progress or currently have replicas.
2. Also consider the most recently created RC in the "Completed" state. (Assures we have something to show when scaled down)
3. From those, choose the RC with the highest deployment version according to the relevant annotation. If for some reason the annotations are missing, compare RC names lexicographically.
There is a new blackbox test that verifies that the expected replication controller …

Update Replication Controller selection logic to mirror the web console

---

controller/deployments.go
controller/deployments_blackbox_test.go
controller/deployments_osioclient.go
design/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go

This PR adds functionality to delete an OpenShift deployment from an environment consisting of the following resources:
- Deployment Configs
- Replication Controllers
- Pods
- Services
- Routes
This functionality is exposed via the `DELETE` method on the endpoint: `/deployments/spaces/{spaceID}/applications/{appName}/deployments/{environmentName}`. This API fixes https://github.com/openshiftio/openshift.io/issues/1663.
I have written tests for both the new controller and Kubernetes code in a separate feature branch:
https://github.com/ebaron/fabric8-wit/tree/delete-tests. ~~These tests depend on the test fixture introduced in #1894, which has not been merged yet. Once that PR is merged, I can add the tests to this PR.~~ The unit tests have now been added to this PR.

Add Deployments API for deleting a deployment

---

controller/search.go
controller/search_blackbox_test.go
controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/do_not_include_children.res.payload.golden.json
controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/include_children.res.payload.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=false.res.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=true.res.golden.json
controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true.res.golden.json

This reverts commit bc9240d7e6ed5b3f55deacaf46dd07af906ff006.
Reason for revert:
TestSearchController/TestIncludedParents/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true
fails from time to time.

Revert "Removes sort by name/ID of workitems in result.Data in search API. (#1924)"

---

controller/codebase.go
controller/iteration_blackbox_test.go
controller/test-files/iteration/show/ok.res.iteration.golden.json
controller/workitem_blackbox_test.go
workitem/workitem_repository.go

* Refactored `controller.createSpaceAndRootAreaAndIterations()` to use test fixture
* Replaced `controller.createOneRandomUserIdentity()/createOneRandomIteration()/createOneRandomArea()` with test fixture
* Added conversion check for `workitem.Fields[SystemOrder].(float64)` on work item repo's `Save()` method

Cleanup controller helper functions

---

Makefile

```
$$ make help
dev-wit-openshift                   - Starts minishift and creates/uses a project named wit-openshift
Deploys DB, DB-AUTH, AUTH services from minishift/kedge/*.yml
Runs WIT service on local machine
dev-wit-openshift-clean             - Removes the project created by `make dev-wit-openshift`
```

Show help text for dev-wit-openshift and dev-wit-openshift-clean targets

---

kubernetes/deployments_kubeclient.go

This PR fixes a typo in GetRoutes where the wrong string variable is used.

Fix wrong string used in GetRoutes

---

account/init_tenant.go
controller/user_service.go
design/user_service.go
glide.lock
glide.yaml

DELETE /api/user/services?remove=true
The User will be auto reprovisioned later when needed. Used by e2e
tests to test init flow and during user abuse.
Related to openshiftio/openshift.io#2393

Expose option to remove a user from the provisioned cluster

---

controller/codebase_blackbox_test.go
controller/filters_blackbox_test.go
controller/golden_files_test.go
controller/iteration_blackbox_test.go
controller/label_blackbox_test.go
controller/query_blackbox_test.go
controller/search_blackbox_test.go
controller/space_blackbox_test.go
controller/test-files/iteration/create/bad_request_missing_name.req.payload.golden.json
controller/test-files/iteration/create/bad_request_unknown_parent.req.payload.golden.json
controller/test-files/iteration/create/conflict_for_same_name.req.payload.golden.json
controller/test-files/iteration/create/ok_create_child.req.payload.golden.json
controller/test-files/iteration/create/ok_create_child.res.iteration.golden.json
controller/test-files/iteration/create/ok_create_child_ID_paylod.req.payload.golden.json
controller/test-files/iteration/create/ok_create_child_with_ID_paylod.res.iteration.golden.json
controller/test-files/iteration/create/unauthorized.req.payload.golden.json
controller/test-files/iteration/create/unauthorized_other_user.req.payload.golden.json
controller/test-files/iteration/show/ok.res.iteration.golden.json
controller/test-files/work_item_type/create/animal.headers.golden.json
controller/test-files/work_item_type/create/animal.wit.golden.json
controller/test-files/work_item_type/create/person.golden.json
controller/test-files/work_item_type/create/person.headers.golden.json
controller/test-files/work_item_type/show/ok.wit.golden.json
controller/test-files/work_item_type/show/ok_using_expired_etag_header.wit.golden.json
controller/test-files/work_item_type/show/ok_using_expired_lastmodified_header.wit.golden.json
controller/work_item_link_blackbox_test.go
controller/work_item_type_group_blackbox_test.go
controller/workitemtype_blackbox_test.go
gormtestsupport/db_test_suite.go
workitem/link/link_repository_blackbox_test.go

The function `controller.compareWithGoldenUUIDAgnostic` was renamed to just `controller.compareWithGoldenAgnostic` and will now replace time values conforming to [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) as well.
This essentially means, that you no longer have to write:
```go
resetFn := s.DisableGormCallbacks()
defer resetFn()
```
in your test before you compare/create a golden file with dates in it. Dates in golden files will be set to a default, namely `"0001-01-01T00:00:00Z"`, when running in agnostic mode.
In addition to RFC3339 we also support time replacements for [RFC7232 Sec 2.2](https://tools.ietf.org/html/rfc7232#section-2.2) now. So times like the `Last-Modified` header values in golden files will be replaced with `"Mon, 01 Jan 0001 00:00:00 GMT"` as of now.
The …

time agnostic golden files for RFC7232 (section 2.2) and RFC3339

---

controller/named_work_items_blackbox_test.go
controller/workitem.go
controller/workitem_blackbox_test.go
migration/migration.go
workitem/workitem_repository.go

I was looking at [this code](https://github.com/fabric8-services/fabric8-wit/blob/master/migration/migration.go#L765). The fields defined there are essentially our "planner item type". There's no `system.number` field in there but we return it for every work item. I wondered if the planner item type only knows about fields that could be **set by the user**? But that cannot be entirely true because the `system.created_at` and `system.updated_at` are fields of planner item type as well. And they are system defined and **read-only**. 
This change makes the `system.number` part of the planner item as well but treats it as read-only.

WIP: Added read-only number to the planner item type.

---

openshift/core.app.yaml

Fixes openshiftio/openshift.io#2675
Differentiate the number of nodes we run in preview and prod to make preview breath a little lighter.

Dynamically set replicas via saasherder

---

openshift/core.app.yaml

[pos 4001]: json: expect char '"' but got char '1'
Fixes openshiftio/openshift.io#2675

Make value in template a string

---

comment/comment_repository.go
comment/comment_repository_blackbox_test.go

If no comments are found, c would be an empty struct and
cause all comments to be deleted.
Fixes openshiftio/openshift.io#2688

Only delete comments if any comment found

---

space/space.go
space/space_test.go

Do not run the query, just return an empty slice when the list of input IDs
is empty
Fixes openshiftio/openshift.io#2686

Spaces API query SQL Error (OSIO#2686)

---

openshift/core.app.yaml

Restrict how much memory the container can consume.
Limit to avoid it overtaking the cluster if the process were to go rogue.
Related to openshiftio/openshift.io#2685

Set resource limits on Container level

---

controller/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_whitebox_test.go
kubernetes/deployments_metrics.go

Currently, we communicate with Kubernetes and OpenShift with the default timeout, which is no timeout at all. To avoid having perpetually open connections in the face of network/server issues, this PR adds a timeout to these requests. The timeout can be set using the new "Timeout" field added to KubeClientConfig, which is propagated to the Kubernetes and OpenShift clients by NewKubeClient. I also had to refactor things a bit to be able to test that the timeouts were passed to these clients.
This PR fixes https://github.com/openshiftio/openshift.io/issues/2462.

Add timeout parameter to Kubernetes/OpenShift clients 

---

kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
test/kubernetes/deploymentconfig-nospace.json
test/kubernetes/deploymentconfig-wrongspace.json

Currently all Spring Boot boosters do not work in the Deployments page, due to a change causing their space labels to not be applied at build-time (https://github.com/openshiftio/openshift.io/issues/2360). A proper fix for this involves changing the way fabric8 determines which space a project belongs to, and how the labels are applied.
In the meantime, we can work around this problem by not returning an error if the space label is missing from a Deployment Config. We instead rely on Deployment Configs having the same name as their corresponding Build Config. If the label is present and indicates the config belongs to a different space, we still return an error. If the label is missing, we proceed and log a warning. I have included tests for both of these cases.

Temporarily work around missing space label

---

controller/deployments.go
controller/deployments_blackbox_test.go
design/deployments.go
kubernetes/deployments_kubeclient.go

This addresses https://github.com/openshiftio/openshift.io/issues/2597
Unused deployments API endpoints are removed.
* removes /spaces/:spaceId/applications/:appName
* removes /environments/:envName
* removes /environments/:envName/applications/:appName/pods

Remove unused deployments api

---

glide.lock
glide.yaml

Also, updated to the latest version of `go-vcr`.
Other updates/changes in `glide.lock` resulted from the `glide update` 
command execution.
Fixes #1964

Move go-vcr dependency in the `testImports` section of glide (#1964)

---

kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go

We are leaking goroutines from the Hawkular client again. I believe the cause is due to not closing the Hawkular client if we fail to read the fabric8-environments config map from the user's OpenShift namespace. I don't see any other code paths that could result in a non-closed Hawkular client.
Fixes: https://github.com/openshiftio/openshift.io/issues/2087

Close Hawkular client if error occurs before returning from NewKubeClient

---

openshift/core.app.yaml

This points to a cluster-specific url called http://core-dsaas-preview.b6ff.rh-idev.openshiftapps.com/ which makes it difficult for service migrations across clusters.

remove route 'core'

---

notification/notification.go

Helps trace the original call that caused the notification service invocation

Forward X-Request-ID header to Notification call

---

codebase/codebase.go
codebase/codebase_test.go
controller/deployments_osioclient.go
controller/space_codebases.go
controller/space_codebases_test.go
design/codebases.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/084-codebases-spaceid-url-index.sql
migration/sql-test-files/084-codebases-spaceid-url-idx-cleanup.sql
migration/sql-test-files/084-codebases-spaceid-url-idx-setup.sql
migration/sql-test-files/084-codebases-spaceid-url-idx-test.sql
migration/sql-test-files/084-codebases-spaceid-url-idx-violate.sql

When adding/associating codebase with a space, there is a possibility
that user tries to add an already existing codebase.
This commit adds a check to see if the codebase user is trying to add
already exists in space.
Fixes https://github.com/fabric8-services/fabric8-wit/issues/1294

add check to see codebase exists in space

---

test/testfixture/make_functions.go

Use account.KeycloakIDP instead of "test provider"

---

Makefile
goasupport/jsonapi_errors_stringer/generator.go

Before the error output looked like this in case of an JSONAPIError:
```
workitem_testing.go:1798: invalid response media: got variable of type *app.JSONAPIErrors, value &{Errors:[0xc420c6e5f0]}, expected instance of app.WorkItemSingle
```
after output looks like this:
```
workitem_testing.go:1798: invalid response media: got variable of type *app.JSONAPIErrors, value 1 JSONAPI Error(s):
[ERROR No.   0]:
Code:    (*string)((len=13) "bad_parameter")
Detail:  (string) (len=100) "Bad value for parameter 'space': 'ab05ffa4-f8e3-45e8-b27a-136c39e8cb95' (expected: 'valid space ID')"
ID:      (*string)(<nil>)
Links:   (map[string]*app.JSONAPILink) <nil>
Meta:    (map[string]interface {}) <nil>
Source:  (map[string]interface {}) <nil>
Status:  (*string)((len=3) "400")
Title:   (*string)((len=19) …
```

Generate String() for app.JSONAPIErrors

---

Gopkg.lock
Gopkg.toml

Add missing `github.com/pilu/fresh` dependency.
Fixes #2018

`make dev` fails after `dep` migration (#2018)

---

auth/resource.go
controller/space.go
controller/space_blackbox_test.go

The issue was introduced by https://github.com/fabric8-services/fabric8-wit/commit/f704d8cbd38e1ef04e923a0127cc176f96e165c6#diff-ebe2c82ed83d49b7c1b2c79e7fd306f1R132
During handling the response from Auth service the response body was read from the stream before decoding it. So, the output stream is already empty by the time we decode the result body and response decoding failed.
Quick fix would be just move the body reading inside an error handling block - https://github.com/fabric8-services/fabric8-wit/pull/2027/commits/aaf315e3bb1f32af6d077a19408d5439d0600b12#diff-ebe2c82ed83d49b7c1b2c79e7fd306f1R75 but we actually don't need the response body of a successful result at all. It's not used anywhere. So, I removed this body decoding completely in this PR.
Fixes …

Fix space creation

---

README.adoc

Recently we migrated from `glide` to `dep`. At that time we forget to update README description.
This PR brings updated usage of dependency management tool i.e. `deps`

docs: update go dependency tool from glide to dep

---

Gopkg.lock
controller/test-files/work_item_type/list/ok_base.res.headers.golden.json
controller/test-files/work_item_type/list/ok_base.res.payload.golden.json
controller/test-files/work_item_type/list/ok_legacy.res.headers.golden.json
controller/test-files/work_item_type/list/ok_legacy.res.payload.golden.json
controller/test-files/work_item_type/list/ok_scrum.res.headers.golden.json
controller/test-files/work_item_type/list/ok_scrum.res.payload.golden.json
controller/test-files/work_item_type_group/list/ok_scrum_template.payload.golden.json
controller/workitemtypes_blackbox_test.go
spacetemplate/assets/scrum.yaml

Change icons of work item types and side panel entries according to these designs: https://redhat.invisionapp.com/share/WJGSJ17SMHN#/screens/290540724.
**NOTE**: Most of the changed files are new golden files. We didn't have golden files for listing work item types of the pre-known space templates before and that is what bloats this PR. The important change is this: https://github.com/fabric8-services/fabric8-wit/pull/2067/files#diff-f71e2910b3317a6a57a3a93edc987a7b.
**Impediment** (WIT):
Changed from `fa fa-question` to `fa fa-stumbleupon`  ![bildschirmfoto von 2018-04-30 13-04-52](https://user-images.githubusercontent.com/193408/39424456-1a76daa0-4c77-11e8-876b-3e977f7a1274.png)
**Product Backlog Item** (WIT) / **Backlog Items** (Sidepanel entry): 
Change from `fa fa-question` to …

Fix scrum icons

---

controller/planner_backlog.go
controller/search.go
controller/work_item_comments.go
controller/work_item_link.go
controller/workitem.go
controller/workitem_whitebox_test.go
controller/workitems.go

In this PR I've changed the signature of the `controller/ConvertWorkItem` and `controller/ConvertWorkItems` function. They now accept the work item type of the work item that is supposed to be converted. The type itself is **not yet** used but it will in a future PR.
This is needed to support generic fields (see #2070).

Call WI's conversion from model to to JSONAPI and back using the WI's type

---

Gopkg.lock
Gopkg.toml
controller/user_service.go
controller/user_service_test.go
design/user_service.go

Now when calling `/user/services`, the namespaces information that is
returned by wit service will also include an attribute
`cluster-capacity-exhausted` which is a boolean which indicates if the
cluster this namespace is hosted on has exhausted it's resources or is
still capable of running more workloads.
This information can be used by OSIO services to make a decision whether
to spawn any new OSIO service in user namespace on that cluster.
Related to openshiftio/openshift.io#3320

Add capacity flag to namespaces - `cluster-capacity-exhausted`

---

codebase/che/client.go
controller/codebase.go
design/codebases.go

che-starter PR - https://github.com/redhat-developer/che-starter/pull/303
osio issue - https://github.com/openshiftio/openshift.io/issues/3320
Adding support of new `clusterFull` property exposed on che-starter side while obtaining Che state - http://che-starter-dsaas-preview.b6ff.rh-idev.openshiftapps.com/swagger-ui.html#!/che-server-controller/getCheServerInfoUsingGET

osio-3320: Adding support of 'clusterFull' property while obtaining Che server state

---

controller/space.go
test/data/codebases/codebases_delete_space.ok.yaml

Before when codebases were deleted we were only checking if the return
code is 200. But the codebase deletion API returns 204 or No content. So
this commit fixes that, by adding a check for all return code from 200
to 299.

fix codebase deletion return code check

---

controller/space.go
controller/space_blackbox_test.go
test/data/deployments/deployments_delete_space.401.yaml
test/data/deployments/deployments_delete_space.403.yaml
test/data/deployments/deployments_delete_space.404.yaml
test/data/deployments/deployments_delete_space.500.yaml
test/data/deployments/deployments_delete_space.different-owner.yaml

The order of deletion of spaces is changed to look like following:
```    
del-space/
├── 00-list-codebases
├── 01-delete-each-codebase
├── 02-delete-all-openshift-resources
└── 03-delete-space-from-db
```

delete openshift resources before spaces

---

controller/space.go
controller/space_test.go
test/data/deployments/deployments_delete_space.404.space_not_found.yaml

instead of validating the JSON-API errors, we just retrieve the first error (assuming there's only one) and return an InternalError using the error's detail

fix panic when deleting an OpenShift resource failed

---

workitem/link/topology.go
workitem/link/topology_blackbox_test.go

There were no tests for the `link.Topology.Scan()` function before.

Improve value scanning of topology with tests

---

controller/test-files/event/list/ok-kindFloat.res.headers.golden.json
controller/test-files/event/list/ok-kindFloat.res.payload.golden.json
controller/test-files/event/list/ok-kindInt.res.headers.golden.json
controller/test-files/event/list/ok-kindInt.res.payload.golden.json
controller/work_item_events.go
controller/work_item_events_test.go
workitem/event/event_repository.go
workitem/event/event_repository_blackbox_test.go

The events API didn't not handle dynamic fields with `Kind=float/int`.
This PR updates the event API to deal with the missing types.
Fixes https://github.com/fabric8-services/fabric8-wit/issues/2107
Note - I cannot add tests for this PR since we do not have test fixtures capable of creating the workitem wtih type `Epic` (or any other type from Scrum template)

Update workitem events API to handle fields with type float and int

---

test/testfixture/make_functions.go

Due to a copy'n'paste error I checked for the wrong entity to have a space template associated with it.
Thanks to @michaelkleinhenz for finding it.

Fix error in WIT group creation

---

Dockerfile.deploy.rhel
cico_setup.sh
openshift/core.app.yaml

This PR is part of the effort to move to Quay.
This is the list of changes in this PR:
- Pushes to Quay instead of the Devshift registry
- Uses an image hosted in Quay to build the RHEL based container image
- Uses the new env-toolkit to load variables from jenkins-env
- Changes the default path of the image to quay (note that this should not affect production because it is overridden in the saas repo)
A companion PR should have been submitted to the appropriate saas repo to change the staging url from devshift to quay. The PR to the saas repo should be merged before this one.
https://github.com/openshiftio/saas-openshiftio/pull/919

Move to Quay.io

---

controller/deployments.go
controller/deployments_blackbox_test.go
design/deployments.go

This patch introduces a new endpoint to the deployment api that returns all environments. 
The endpoint is defined under "/api/deployments/environmetns" and returns all environments to the client. This behaviour currently exists under "api/deployments/spaces/$SPACE", which will be modified according to the note below.
Note : This is step 1/2 of https://github.com/openshiftio/openshift.io/issues/2889, the second being to modify the previously existing endpoint to actually use the spaceId parameter.

fix(deployments): add all environments endpoint

---

gormapplication/application.go

No need to create two variables (`x` and `y`) for it.

Use underscore to test if interface is implemented

---

controller/work_item_labels_blackbox_test.go

The gormtestsupport.DBTestSuite already takes care of that.

No need to manually clean created entities in test

---

Makefile
controller/comments_blackbox_test.go
controller/iteration_blackbox_test.go
rest/http.go
space/authz/authz.go
space/authz/authz_test.go
test/error.go
test/http.go
test/login.go
test/suite/unit_test_suite.go
test/token/token.go

This PR is a temporal solution for native authorization via Auth service.
Instead of fetching an entitlement token for the resource (space) from Keycloak it loads the list of identity-roles (users with assigned roles) for the space from Auth service.
If the current user is not among the space admins or contributors then access is not granted.
This PR eliminates Keycloak from AuthZ flow.
The next step will be an implementation of new AuthZ flow based on Auth RPT tokens.
fixes https://github.com/fabric8-services/fabric8-auth/issues/493

Switch permission check from KC to Auth service

---

.make/test.mk
application/application_db_calls_bench_test.go
application/transaction_test.go

Fixes https://github.com/fabric8-services/fabric8-wit/issues/2134
Tests from the following packages will also be executed
1. `github.com/fabric8-services/fabric8-wit/application`
2. `github.com/fabric8-services/fabric8-wit/application/repository`
3. `github.com/fabric8-services/fabric8-wit/gormapplication`

Change test file exclude pattern

---

Makefile
docker-compose.macos.yml
docker-compose.yml
minishift/Makefile

The docker-compose file and makefile reference container images from `docker hub` which we no longer use. We're using `quay.io`  as our container registry (see https://github.com/fabric8-services/fabric8-wit/pull/2116). This PR updates docker compose and makefile to use the correct container registry.

Use container images from quay.io instead of docker hub

---

controller/space_areas_blackbox_test.go

Fixes issue similar to https://github.com/fabric8-services/fabric8-wit/issues/2155

Clean test entites created by space_areas_blackbox_test.go

---

cico_setup.sh

This prevents error messages like this one:
```
docker run \
--detach=true \
-t \
-i \
--name="fabric8-wit-local-build" \
-v /root/payload:/tmp/go/src/github.com/fabric8-services/fabric8-wit:Z \
-u 0:0 \
-e GOPATH=/tmp/go \
-w /tmp/go/src/github.com/fabric8-services/fabric8-wit \
fabric8-wit
/usr/bin/docker-current: Error response from daemon: Conflict. The container name "/fabric8-wit-local-build" is already in use by container aef0c5eb4f38e45d2fb41df5d660da1057acf0bda90ccd35ec1ff938bf85a79d. You have to remove (or rename) that container to be able to reuse that name..
```
The `docker-rm` make target removes containers with the name `fabric8-wit-local-build` (if any) so that `docker-start` can run through without problems.

Remove flow-heater container if it already exists

---

cico_setup.sh

Reverts fabric8-services/fabric8-wit#2188
Because the root cause as described here might be two jobs assigned to the same container. https://github.com/openshiftio/openshift.io/issues/3838#issuecomment-399006019

Revert "Remove flow-heater container if it already exists"

---

.make/docker.mk
cico_setup.sh

Use `BUILD_TAG` (available in Jenkins environment) for docker container name.
For jenkins job 123, container name would be `jenkins-devtools-fabric8-wit-123` and for local build it would be `fabric8-wit-local-build`
see - https://github.com/openshiftio/openshift.io/issues/3838

Don't use same container for all builds

---

design/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
test/kubernetes/getenvironment-all-objects.yaml
test/kubernetes/getenvironment-no-compute.yaml
test/kubernetes/getenvironment-no-cpu.yaml
test/kubernetes/getenvironment-no-mem.yaml
test/kubernetes/getenvironment-no-objects.yaml
test/kubernetes/getenvironments-rq-error.yaml
test/kubernetes/getenvironments.yaml

Currently, the deployments page shows CPU and memory resource usage and limits for each environment. There are also quotas enforced for the number of certain types of objects in each namespace. Hitting these quotas can prevent further deployments to those environments, so this information is useful to show to the user.
This PR adds usage and limits, for each type of object that has an active quota, to the data returned by the ShowEnvironments API. After discussing the design with UX, we agreed to show only object types that have a quota set up. The possible object types are: pods, replication controllers, resource quotas, services, secrets, config maps, persistent volume claims, and image streams [1]. Currently, my OpenShift starter account has only quotas enabled for replication …

Add object count quotas to environment stats

---

controller/endpoints.go
controller/test-files/endpoints/list/ok.res.payload.golden.json
design/endpoints.go
main.go

With this PR the endpoints (see #521) are served under `/api` and each endpoint relationship link has a proper URL-schema prefix.
The `/api` temporarily redirects to `/api/endpoints`.
Co-authored-by: Konrad Kleine 193408+kwk@users.noreply.github.com

Serve endpoints API under /api and fix missing URL schema for relationship links of endpoints

---

workitem/workitemtype_blackbox_test.go

This adds a unit-test test to check that workitem type constants are not changed accidentally. 
This makes usage of constants in tests more safe as discussed in today's meeting with @jarifibrahim and @michaelkleinhenz .

Add constants test for work item types

---

Makefile
docker-compose.yml
main.go

This serves the generated `swagger.json` under `/api/swagger.json` and replaces the host with the current setting from `config.GetHTTPAddress()`. This should make the swagger output compatible with whatever host it is running on (local, prod-preview, prod, ...).
I've also added a swagger-ui container that starts up on `make dev` and is served at [http://localhost:8081/](http://localhost:8081/) and looks like this:
See also #165 for an old version of this.

Serve swagger under /api/swagger.json and swagger-ui

---

main.go

As a follow up for #2217 this change will properly replace the host (currently always `host: "0.0.0.0:8080",`) in the [generated swagger file](https://api.prod-preview.openshift.io/api/swagger.json) with the host of the request that tries to access the swagger file. We strip off the `http://` or `https://` prefix because that's handled in the swagger `schemes` section.
We also set the scheme to `https` if the current request was made using `https://`.

Replace swagger host with request host and adjust scheme

---

main.go
rest/url.go

A fixup up for #2217 to properly adjust the schemes defined in swagger.
Previously the X-Forwarded-Proto wasn't respected but now it is.

Fix swagger scheme

---

controller/test-files/work_item_type_group/list/ok_agile_template.headers.golden.json
controller/test-files/work_item_type_group/list/ok_agile_template.payload.golden.json
controller/work_item_type_group_blackbox_test.go

The work item type groups of the agile template haven't been tested so far. This file dumps them to their own golden files.
This is important to recognize changes, when somebody changes the type groups in the YAML file. For example in #2222 the changes are unnoticed which is bad.

have golden files for work item type groups from agile template

---

controller/test-files/work_item_type_group/list/ok_legacy_template.payload.golden.json
controller/work_item_type_group.go
design/work_item_type_group.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/101-add-description-to-witg.sql
spacetemplate/assets/legacy.yaml
spacetemplate/importer/importer_blackbox_test.go
workitem/typegroup.go
workitem/typegroup_repository_blackbox_test.go

To support #2222 where @Preeticp wants to add info tips texts to work item type groups. Here I've added just one description (as pointed out here: https://github.com/fabric8-services/fabric8-wit/pull/2222#issuecomment-411048527) to see that it works. @Preeticp can do the rest in her PR.

Add description in work item type group

---

migration/migration_blackbox_test.go

Last two tests were using the wrong index in order to update the work item DB.

Fix migration test

---

spacetemplate/importer/repository.go

This caused some new fields in the WIT not to be respected by the creator.

Use create from model function when importing WIT from YAML

---

cico_run_e2e_tests.sh

We want to have end to end tests checking our PRs and in https://github.com/fabric8-services/fabric8-wit/pull/2197 @rgarg1 is working on how this.
It makes sense to run the end to end tests as a standalone job because the tests can be slow and can output messages that we don't want to see inside of our unit or integration tests.
This change adds a `cico_run_e2e_tests.sh` file that fails all the time and outputs a message. Once the file https://github.com/openshiftio/openshiftio-cico-jobs/blob/master/devtools-ci-index.yaml is adjusted to pick up run the end to end tests using this file, then @rgarg1 can adjust his PR to execute the tests in this `.sh` file.

Added cico_run_e2e_tests.sh

---

migration/migration_blackbox_test.go

The same thing is tested in migration 98 function.

Remove unused migration test function

---

actions/actions.go
actions/actions_whitebox_test.go
actions/change/changeset.go
actions/doc.go
actions/rules/action.go
actions/rules/action_field_set.go
actions/rules/action_field_set_test.go
actions/rules/action_nil.go
convert/changeset.go
workitem/workitem.go

The actions system is a key component for process automation in WIT. It provides a way of executing user-configurable, dynamic process steps depending on user settings, schema settings and events in the WIT.
The idea here is to provide a simple, yet powerful "signal-slot" system that can connect any "event" in the system to any "action" with a clear decoupling of events and actions with the goal of making the associations later dynamic and configurable by the user ("user connects this event to this action"). Think of a "IFTTT for WIT".
Actions are generic and atomic execution steps that do exactly one task and are configurable. The actions system around the actions provide a key-based execution of the actions.
Some examples for an application of this system would be:
closing all childs of …

Actions infra

---

migration/migration_blackbox_test.go

This fixes the numbering of the migration tests where somehow, we started not using the migration order number from 100 to 102. This is somewhat confusing when adding new tests there. We should keep the order there.

Fixed migration test numbering and func order.

---

controller/test-files/work_item_type/list/ok_agile.res.payload.golden.json
controller/test-files/work_item_type/list/ok_scrum.res.payload.golden.json
controller/workitemtype.go
design/workitemtype.go
spacetemplate/assets/agile.yaml
spacetemplate/assets/scrum.yaml
spacetemplate/importer/import_helper.go
spacetemplate/importer/importer_blackbox_test.go
spacetemplate/importer/repository.go
workitem/enum_type.go
workitem/enum_type_blackbox_test.go
workitem/enum_type_whitebox_test.go
workitem/field_definition.go
workitem/json_storage.go
workitem/list_type.go
workitem/list_type_blackbox_test.go
workitem/simple_type.go
workitem/simple_type_blackbox_test.go
workitem/workitem_repository.go
workitem/workitemtype.go

This change introduces the ability for any field type to OPTIONALLY specify a custom default value. See also https://openshift.io/openshiftio/Openshift_io/plan/detail/35 and https://github.com/openshiftio/openshift.io/issues/3832.
For lists and simple types, the only restriction is that the default value is of the same kind as the list or simple type (e.g. integer, float, string, user, label, ...). For enum fields the custom default value needs to be in the list of allowed values.
As an example, we've set the default for severity and priority fields to a medium value instead of the first on in the list, which would be a high severity/priority. (See also https://github.com/openshiftio/openshift.io/issues/3832)
When a space template is imported it creates or overrides the work item types. …

Default value

---

controller/deployments.go
controller/deployments_blackbox_test.go
design/api.go
design/deployments.go
goamiddleware/jwt_middleware.go
goamiddleware/jwt_shared.go
goamiddleware/jwt_token_context.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
log/log.go
main.go

This addresses the 'events' side of https://github.com/openshiftio/openshift.io/issues/2380
The endpoint `api/deployments/environments/{environmentId}/events/watch` is added that allows websocket clients to connect and receive the Kubernetes Events ListAndWatch results.
This is a WIP PR and contains commits and files that need to be cleaned before merging. These are:
Commit: 
temp(deployments): set localhost
fix(deployments): add readme for websockets prototype
Files:
examples/client.go

Add Kubernetes events watcher websocket endpoint

---

log/log.go

Inside of `log/log.go` we've imported the `github.com/sirupsen/logrus` package under the alias `log` which seemed confusing. With this change we import `github.com/sirupsen/logrus` as is.

Import github.com/sirupsen/logrus as is in log/log.go

---

controller/work_item_boardcolumns_blackbox_test.go

Possibly related to openshiftio/openshift.io#4299

The board column tests don't cleanup after themselves.

---

Gopkg.lock

The `gopkg.lock` file is out of date. This PR updated it.
How to verify this PR
1. Run `dep ensure` on current master. You should see the `gopkg.lock` is modified.
2. Check the changes in `gopkg.lock` file against the ones in this PR. They should be same.
3. Run `dep ensure` again and you would notice `gopkg.lock` has not changed.

Update gopkg.lock file

---

workitem/workitem_repository.go

We're seriously wasting time in calculating numbers of work items in
iterations by ignoring the fact that we're in a space. @pbergene gave
me a dump of slow queries this morning and while I was looking for
something completely else I noticed this piece:
```
"Query Text": "SELECT iterations.id as IterationId, count(*) as Total,\
\    \    \    count( case fields->>'system.state' when 'closed' then '1' else null end ) as Closed FROM \\"work_items\\" left join iterations\
\    \    \    on fields@> concat('{\\"system.iteration\\": \\"', iterations.id, '\\"}')::jsonb WHERE (iterations.space_id = $1\
\    \    \    and work_items.deleted_at IS NULL) GROUP BY IterationId",
```
This query is so slow (~55 to 60ms) that and it appears so often that
the log of slow queries is cluttered with this. …

Improve perf of calculating WIs in iteration

---

openshift/core.app.yaml

from 60 seconds to now 120 seconds
See #2291

Double the amount of allowed time for a pod to be ready

---

controller/space.go

Minor improvements to errors returned from the `Detele` action on space controller.

Improve DeleteSpace error messages

---

migration/sql-files/106-number-sequences.sql
migration/sql-test-files/106-number-sequences.sql

In order to avoid a sequential table scan on the `work_items` DB table we take the already calculated values for the new `number_sequences` table from the old `work_item_number_sequences`.
Before this was the query plan for `INSERT` into the new `number_sequences` table:
```
EXPLAIN
SELECT space_id, 'work_items' "table_name", MAX(number) 
FROM work_items 
WHERE number IS NOT NULL 
GROUP BY 1,2;
+--------------------------------------------------------------------------------+
| QUERY PLAN                                                                     |
|--------------------------------------------------------------------------------|
| GroupAggregate  (cost=37097.49..38835.71 rows=37629 width=52)                  |
|   Group Key: space_id, 'work_items'::text …
```

Use existing number sequences instead of looking them up again

---

controller/deployments.go
design/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
test/kubernetes/podquota-emptyresources.yaml
test/kubernetes/podquota-multicontainer.yaml
test/kubernetes/podquota-noresources.yaml
test/kubernetes/podquota-split.yaml
test/kubernetes/podquota.yaml

This PR adds a new API serviced by the deployments controller at `/deployments/spaces/{spaceID}/applications/{appName}/deployments/{deployName}/podlimits`. 
Calling this API on a particular deployment determines the CPU and memory resources required in order to add a new pod to the deployment. This will allow the front-end to decide whether to stop the user from attempting to scale up a deployment if they do not have sufficient quota to do so successfully.
Example usage:
Request: `GET https://openshift.io/api/deployments/spaces/$SPACE/applications/$APP/deployments/run/podlimits`
Response: `{"data":{"limits":{"cpucores":1,"memory":262144000}}}`
This work was initially done by @chrislessard, and I have added tests and some modifications.
Fixes: …

Add deployments API to compute quota necessary for scale-up

---

migration/sql-files/106-number-sequences.sql

In order to avoid the following deadlock situation, the 106 migration now acquires an exclusive lock on the `spaces`, `iterations`, `areas` and `work_item_number_sequences` tables.
Legend:
- relation `36029` = `spaces`
- relation `36042` = `iterations`
```
2018-09-26 07:55:25 UTC:172.31.53.17(37984):dbadmin@postgres:[875]:ERROR:  deadlock detected
2018-09-26 07:55:25 UTC:172.31.53.17(37984):dbadmin@postgres:[875]:DETAIL:  Process 875 waits for AccessExclusiveLock on relation 36029 of database 13322; blocked by process 5634.
Process 5634 waits for AccessShareLock on relation 36042 of database 13322; blocked by process 875.
Process 875: -- Create the number sequences table
CREATE TABLE number_sequences (
space_id uuid REFERENCES spaces(id) ON DELETE CASCADE,
table_name text CHECK …
```

acquire exclusive lock on spaces, areas, iterations and work_item_number_sequences table to avoid deadlock during migration

---

migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/107-number-sequences-table.sql
migration/sql-files/108-number-column-for-area.sql
migration/sql-files/109-number-column-for-iteration.sql

This adds back the `number_sequences` table the `number` columns on the `areas` and `iterations` tables (known from #2287 but then reverted). But it does this in three individual steps. This change is backwards compatible with the old code as the `number` column is nullable. Except for this structural change, no data is changed.

Add number_sequences table and nullable 'number' column on areas and iterations tables

---

controller/deployments.go
controller/deployments_blackbox_test.go
design/deployments.go
kubernetes/deployments_kubeclient.go
kubernetes/deployments_kubeclient_blackbox_test.go
test/kubernetes/getspaceandotherenvironmentusage-rq-error.yaml
test/kubernetes/getspaceandotherenvironmentusage.yaml

This PR adds a deployments-related API under `/deployments/environments/spaces/:spaceID`. This endpoint returns resource usage for each of the user's environments, divided into usage by the specified space and usage by all other spaces combined. Currently this only returns CPU and memory usage, and not objects such as pods or secrets.
There is an older `/deployments/spaces/:spaceID/environments` endpoint which has been left for backwards compatibility until the front-end is switched over completely.
Example usage:
Request: `GET https://openshift.io/api/deployments/environments/spaces/$SPACE_ID`
Response:
```json
{
"data": [
{
"attributes": {
"name": "run",
"other_usage": {
"cpucores": {
"quota": 2,
"used": 0.488
},
"memory": {
"quota": 1073741824,
"used": 262144000
}, …
```

Add API to show resource usage for the current space

---

controller/space.go

This PR adds more logs to the delete action on space controller.
See https://github.com/fabric8-services/fabric8-wit/pull/2280 and https://github.com/fabric8-services/fabric8-wit/pull/2297

Add more logs for Delete action on space controller

---

migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/110-update-number-for-existing-iterations.sql
migration/sql-test-files/110-update-number-for-existing-iterations.sql

This updates all existing iterations and assigns a number to each iteration partitioned by space and in ascending order by creation time.
This change also makes the number a not-NULLable column on the iterations.
Also a constraint (`iterations_space_id_number_idx`) is created that ensures an iteration number can only occur once per iteration.

update number for existing iterations

---

search/search_repository_blackbox_test.go

This PR
1. Renames some tests from `TestSearch.*` to `TestFilter.*` because those tests are for filter and not search.
2. Separate tests into `TestFilter` and `TestFullTextSearch`. Earlier they are all mixed up.
**NOTE** - This PR does not add/remove any test. This PR only renames and rearranges tests.

Rearrage search repository blackbox tests

---

controller/comments_blackbox_test.go
controller/search_blackbox_test.go
controller/space.go
controller/workitem_blackbox_test.go

With this PR
- The default template used for space creation would be `Agile`.
The only relevant change is https://github.com/fabric8-services/fabric8-wit/pull/2323/commits/306a8f3781f0bddf154e62e8f4547bf87a687445. 
Rest of the changes are fixes to the tests which depended on the default template. I've changed them to use `fxt.WorkitemTypes` instead of `workitem.SystemFeature/workitem.SystemBug`
See https://github.com/fabric8-services/fabric8-wit/issues/2317 and https://github.com/openshiftio/openshift.io/issues/4427

Make agile default template for space creation

---

controller/test-files/work_item_type/list/ok_agile.res.payload.golden.json
spacetemplate/assets/agile.yaml
spacetemplate/importer/repository_blackbox_test.go

Add `None` to a Defect's resolution in the Agile space template and make it the default resolution by putting it in first place.
See https://github.com/openshiftio/openshift.io/issues/3832

Add 'None' as default resolution for defect

---

spacetemplate/importer/repository.go
spacetemplate/importer/repository_blackbox_test.go

Previously the [deployment failed](https://github.com/fabric8-services/fabric8-wit/pull/2334#issuecomment-433887438):
```
failed to overwrite default of old field type with None (string):
failed to set default value of enum type to None (string):
value: None (string) is not part of allowed enum values:
[Done Duplicate Incomplete Description Can not Reproduce Deferred Won't Fix Out of Date Verified]
file: spacetemplate/importer/repository.go
line: 91
```
We've updated the resolution enum to
have a new value and that is also the new default. That new value didn't
exist in the old enum type but we tried to make it the new default for
the old type anyways. That didn't work because the `FieldType.SetDefault()`
implementation for enums checks if the given value is part of the
allowed enum …

Fixup for bbd8f88c789943293680644ae8a49b5342a55575 #2334

---

.github/CODEOWNERS

We want to use this file in Github to automatically assign reviewers to PRs if they are declared as "owners".
Read more about this file here:
* https://blog.github.com/2017-07-06-introducing-code-owners/
* https://help.github.com/articles/about-codeowners/
So far I've added only "my" parts and the ones I feel deeply responsible for.
We can add more code owners later.

Added .github/CODEOWNERS file

---

controller/golden_files_test.go

Before we used to have a list of booleans in order to configure the comparison and generation of golden files. Now we have a defined set of comparison options:
```go
// compareOptions define how the comparison and golden file generation will take
// place
type compareOptions struct {
// Whether or not to ignore UUIDs when comparing or writing the golden file
// to disk
UUIDAgnostic bool
// Whether or not to ignore date/times when comparing or writing the golden
// file to disk
DateTimeAgnostic bool
// Whether or not to call JSON marshall on the actual object before
// comparing it against the content of the golden file or writing to the
// golden file. If this is false, then we will treat the actual object as a
// []byte or string.
MarshalInputAsJSON bool
}
```
And a new compare function: …

Cleanup golden files comparison and generation by introducing compareOptions

---

.make/test.mk

Test integration regularly failed with:
```
--- FAIL: TestJSONAPICompliance (0.70s)
--- FAIL: TestJSONAPICompliance/TestListSpaces (0.11s)
```
https://github.com/fabric8-services/fabric8-wit/blob/master/controller/json_api_compliance_test.go#L67 
The failure is intermittent and seems to occurs bc the of the state of the DB
The proposal is to run integration test (only test requiring DB) forcing them to run on 1 program/test binaries.
```
> go help build
...
-p n
the number of programs, such as build commands or
test binaries, that can be run in parallel.
The default is the …
```

Do not run parallel integration test

---

docker-compose.macos.yml

When running `make dev` on macOS, this error is reported:
```
ERROR: No such service: swagger_ui
make: *** [docker-compose-up] Error 1
```
this error was introduce by https://github.com/fabric8-services/fabric8-wit/pull/2217 in the PR the macOS file was missed.
Updating the macOs file fix the issue.

Add swagger_ui to macOS doker-compose

---

controller/search_blackbox_test.go
workitem/expression_compiler.go

This PR enables searching workitems by trackerquery ID.
[1]  Adds Tracker Query table details, alias in expression compiler.
[2] Tests for the same

Enables searching of workitems by trackerquery id

---

controller/codebase.go
test/data/che/che_delete_codebase_workspaces.ok.yaml

The response for workspace list returned from che starter does not contain a delete link.
This PR removes the check for the delete link in the response payload.
Fixes https://github.com/openshiftio/openshift.io/issues/4559

Delete workspaces: Don't rely on links in the list workspaces response
