fabric8-services/fabric8-wit

Makefile, jenkins/linux/build.sh
Add a `all-tests` make target that runs `test-unit` and `test-integration` targets.
The `test` make target was renamed to `test-unit`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/43)
=> test targets

models/field_definition.go, models/simple_type.go, models/workitemtype_test.go, workitemtype.go
fixed #41 
NOTE: Awaiting https://github.com/almighty/almighty-core/pull/45 to avoid format changes to clutter the diff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/49)
=> WIP: Add suffix to Kind names to avoid name conflict on simple words

design/api.go, design/resources.go, workitem.go, workitem_test.go
fixes #29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/50)
=> Add response 201 with Location header on WorkItem POST

.gitignore, .make/Makefile.lnx, .make/Makefile.win, Makefile
This adds an `$(INSTALL_PREFIX)` Makefile variable that is used by all of our binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/61)
=> Fix #60 Move make build artifacts to ./bin/

glide.lock, glide.yaml, tool/alm-cli/main.go
fixes #63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/65)
=> Update Goa to include cli help payload example

README.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/71)
=> Consistently require 1.6

README.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/73)
=> Change prerequisites in to a list, add make

Makefile, README.adoc, docs/development/README.adoc, docs/development/getting-started-win.adoc
This includes a new directory called docs/development
with a README and "Getting started on Windows" guide.
The main Makefile has been updated to be able to build
in cygwin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/83)
=> Created developer documentation for Windows

.make/test.mk, README.adoc
This adds a section about coverage to the README. It is ready to merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/116)
=> README section about coverage

README.adoc
Fixes #55
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/117)
=> Fix #55 - Debugging instructions for the command line using delve

README.adoc, design/resources.go
Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/138)
=> Use plural form of nouns in REST API

docs/development/ide-setup.adoc
WHY:
Having an IDE helps in spending less effort in figuring our syntax and compilation issues.
WHAT:
Added steps for vscode. Folks could enhance the same and also add on steps for other IDEs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/87)
=> Started the ide setup doc with instructions for vscode 

design/user_types.go
Instead of relying on pure generated data structures
we can provide help examples that are a bit closer to
reallity. The provided example should work on a clean system/
new project/user.
fixes #153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/154)
=> Add usable data to the workitem create/update cli help

docker-compose.yml
It has been specified in the Dockerfile.deploy already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/175)
=> No need to specify entrypoint

cico_build_deploy.sh
Do not merge yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/181)
=> setup a script to get the container image built, if tests pass

design/media_types.go, design/user_types.go, migration/migration.go, models/expression_compiler.go, models/repository.go, models/workitem.go, models/workitem_repository.go, workitem.go, workitem_test.go
Why: The name attribute is redundant since it should be a field in the constituent map.
What: Removed the name from both the REST and storage layer
Fixes #151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/171)
=> Remove name attribute from WorkItem

design/user_types.go, examples/create_workitem.json, migration/migration.go, models/simple_type.go, models/workitem_repository.go, workitem_test.go
* system.userstory
* system.feature
* system.bug
All typs have the fields
* system.title
* system.description
* system.assignee
* system.state
fixes #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/185)
=> Add predefined basic workitem types

design/resources.go
Allows easy access for script etc to see what is currently running.
fixes #198 
NOTE: Do not merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/201)
=> Add un-authorized api/version Endpoint

.make/docker.mk, cico_build_deploy.sh, cico_run_tests.sh
Fixes #203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/204)
=> Show combined coverage output at last step in PR jobs

.make/test.mk
Fixes #221
This increases the overall coverage from **22.00%** to **23.70%** which is a plus of **1.7%**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/223)
=> Remove bindata_assetfs.go from coverage

README.adoc
Adds a badge with the current build status and a link to the last build job on the jenkins system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/225)
=> Badge: build status and link to last built master

.make/test.mk
In addition to the the function level coverage information, these commands will now also append a section called `Package coverage`:
* `make coverage-unit`
* `make coverage-integration`
* `make coverage-all`
Here's an example output (only the new portion of it):
```
Package coverage:
github.com/almighty/almighty-core                                                18.00%
github.com/almighty/almighty-core/app                                               n/a
github.com/almighty/almighty-core/app/test                                          n/a
github.com/almighty/almighty-core/client                                            n/a
github.com/almighty/almighty-core/criteria                                       52.40%
github.com/almighty/almighty-core/design …
```
=> Coverage by package

cico_run_tests.sh
This relates to #235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/236)
=> Only source those env vars we really need

tracker_test.go, workitem_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/237)
=> fix tracker test - pass scheduler

migration/migration.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/239)
=> Add ValueProposition & Fundamental WIT

cico_run_tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/235)
=> WIP Upload coverage to codecov.io

cico_build_deploy.sh, cico_run_tests.sh
This will upload coverage for master as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/245)
=> Upload coverage to codecov

design/user_types.go
=> Example data for Tracker/TrackerQuery payloads

remoteworkitem/tracker_repository.go, tracker_test.go, workitem_test.go
Fix added to convert string to integer value using base 10.
Fix added to append tracker items in the List method, which was missing and hence returning <nil>
Tests added for List and Show of tracker.
Fixes #190 #189 #191 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/197)
=> Fix+Tests for non-bogus ID and non-nil tracker items in List and Show actions of tracker.

design/media_types.go, remoteworkitem/repository.go, remoteworkitem/trackerquery_repository.go, trackerquery.go
Fixes #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/almighty/almighty-core/202)
=> Fix #192 Changed Tracker ID to string

remoteworkitem/flatten_test.go, remoteworkitem/remoteworkitem.go, remoteworkitem/remoteworkitem_test.go
Added `nil` test for `flatern` method.
Fixed few warnings by `golint`.
=> Refactor as per golint warnings.

design/user_types.go, trackerquery.go, trackerquery_test.go
=> Fix#228 Trackerquery test case

migration/migration.go, migration/sql-files/002-tracker-items.sql, remoteworkitem/github.go, remoteworkitem/jira.go, remoteworkitem/remoteworkitem_test.go, remoteworkitem/scheduler.go, remoteworkitem/trackeritem.go, remoteworkitem/trackeritem_repository.go, remoteworkitem/trackeritem_test.go
=> Avoid duplicate tracker items while importing

README.adoc, account/identity.go, account/user.go, account/user_test.go, config.yaml, configuration/configuration.go, design/api.go, design/media_types.go, design/resources.go, glide.lock, glide.yaml, login.go, login/service.go, login/service_blackbox_test.go, login/service_whitebox_test.go, login_test.go, main.go, migration/migration.go, migration/sql-files/003-login.sql, status_test.go, token/token.go, token/token_test.go, user.go, user_test.go
Fixes #20, #219, #321, #325, #327, #328, #337
Related #304
=> Add Login Service using GitHub

workitem.2.go, workitem_whitebox_test.go
=> set links for pagination

workitem.2.go, workitem_blackbox_test.go
=> Return Absolute URLs in Pagination links

design/user_types.go, remoteworkitem/tracker_repository.go, remoteworkitem/tracker_repository_test.go, remoteworkitem/trackerquery_repository_test.go
- Fixes #85
- Adds pattern and min validation
- Validates url of tracker
=> Expands on attribute validation in REST api

workitem.2.go, workitem_blackbox_test.go
=> Add default(20) and max(100) page size consts for work item list

application/repositories.go, design/resources.go, remoteworkitem/trackerquery_repository.go, remoteworkitem/trackerquery_repository_test.go, trackerquery.go, trackerquery_test.go
- fixes #169 
- Adds List and Delete actions for TrackerQuery
=> Adds TrackerQuery List and Delete action

account/identity.go, application/application.go, application/repositories.go, design/media_types.go, design/resources.go, design/user_types.go, gormapplication/application.go, identity.go, identity_blackbox_test.go, main.go, test/db.go
=> List user identity API

design/resources.go, tracker_blackbox_test.go, tracker_test.go, trackerquery_blackbox_test.go, trackerquery_test.go, workitem_whitebox_test.go
=> Secure Tracker REST Endpoints

models/workitem_repository.go, models/workitemtype_repository.go, remoteworkitem/tracker_repository.go, remoteworkitem/trackerquery_repository.go
This is the result of looking for problems described in #424 and #425. Turns out, it only happens in very view places.
=> Fix gorm DB usages

search/search_repository.go, search/search_repository_whitebox_test.go
=> Update the URL to reflect the lastest URL endpoint

configuration/configuration.go, login/service_whitebox_test.go, remoteworkitem/github.go, resource/require.go
=> WIP: Adds oauth access token to github client

login/service_whitebox_test.go
Fix #493 
Retrying Github availability for failing TestValidOAuthAccessToken
=> Retrying Github availability for failing TestValidOAuthAccessToken

workitem.go, workitem_blackbox_test.go
=> Handle PATCH relationship BaseType in WorkItem API

application/application.go, comment/comment.go, comment/comment_test.go, comments.go, design/comments.go, design/jsonapi_helpers.go, design/workitems.go, gormapplication/application.go, main.go, test/db.go, work-item-comments.go, work-item-comments_test.go, workitem.go
Links "self" points to the []Comment of related comments
to this WorkItem
"comments" relationship include "meta" "totalCount"
Related to #526
=> Add "comments" relationship to WorkItem API

design/workitems.go, workitem.go, workitem_blackbox_test.go
WorkItemList now include links.self to each WorkItem in the list
Related to #526
=> Move WorkItem links.self to data.links.self

design/comments.go, work-item-comments.go, workitem.go, workitem_blackbox_test.go
=> API link adjustments 

design/workitems.go, workitem.go, workitem_blackbox_test.go
=> Add system.creator as relationship in WorkItem API

comments.go, design/jsonapi_helpers.go, design/media_types.go, design/resources.go, design/search.go, design/workitems.go, search.go, search_blackbox_test.go, work-item-comments.go, workitem.go, workitem_blackbox_test.go
Related to #526
Related to #515
Awaiting UI changes from @sanbornsen
=> Convert Search WorkItem to JSON API

comments.go, design/comments.go, work-item-comments.go
* self GET the ResourceID Objects for the related Comments
* related GET the Comment Object for the related Comments
* related POST to Create new Comment
note: self DELETE/PATCH/POST not supported
note: related DELETE/PATCH not supported
Related to #526
=> Add self/related links to WorkItem Comments

application/application.go, design/resources.go, gormapplication/application.go, main.go, test/db.go, users.go, users_test.go
=> API to get an individual user

workitem/workitem_repository.go, workitem_blackbox_test.go
=> created-at should be available after create/update

account/identity.go, design/jsonapi_helpers.go, design/user_types.go, users.go, workitem.go
=> Add self links to User relations in WorkItem API

design/work-item-link-category.go, design/work-item-link-type.go, design/work-item-link.go, work-item-link-blackbox_test.go, work-item-link-category-blackbox_test.go, work-item-link-category.go, work-item-link-type-blackbox_test.go, work-item-link-type.go, work-item-link.go
Adds "links" element to:
* work item link categories
* work item link types
* work item links
=> Fix #564 Add "links" element to work item link / type / category

work-item-link-blackbox_test.go, work-item-link.go, workitem/link/link-repository.go, workitem/workitem.go, workitem/workitem_repository.go
According to @tsmaeder 's comments on #525 (after it was being merged), this PR includes some cleanups.
=> Followup on #525

application/application.go, design/iterations.go, design/workitems.go, gormapplication/application.go, iteration.go, iteration/iteration.go, iteration/iteration_test.go, iteration_test.go, jsonapi/jsonapi_utility.go, main.go, migration/migration.go, migration/sql-files/013-iterations.sql, project-iterations.go, project-iterations_test.go, test/db.go, workitem.go, workitem/field_definition.go, workitem/fieldtype_blackbox_test.go, workitem/simple_type.go, workitem/workitemtype.go, workitem/workitemtype_repository.go, workitem_blackbox_test.go
=> Add Iteration Repository | REST Endpoint | WorkItem integration

login/service.go
Modified the logic in the Perform function in `login/service.go`
to retrieve the user everytime, and save the identity if
the user already existed, not just during creation.
=> Stored Github User information should be updated (#537)

design/iterations.go, project-iterations_test.go
Related to #572 
https://github.com/almighty/almighty-core/pull/572#discussion_r92841860
=> Remove unused Filter/Pagination from Iterations

comment/comment.go, comment/comment_test.go, comments.go, design/comments.go
=> REST API to update comment

design/spaces.go, space.go, space_test.go
Fixes #659
* Added link of list-iteration-per-space in the response of list-spaces.
=> Add listIterations link in space response

migration/migration.go, workitem/workitemtype_cache.go, workitem/workitemtype_cache_blackbox_test.go, workitem/workitemtype_repository.go, workitem/workitemtype_repository_blackbox_test.go
This cache is just a simple synchronized unexported global var.
Fixes #242
=> Use WIT cache instead of fetching same WITs many times

design/userspace.go, main.go, userspace.go
Initial version of a dispatcher service between
userspace data collectors and saas.
v 0.000001, slup all data to see what is comming in and what
we can do with it.
=> Simple slurp in anything endpoint

comment/comment.go, comment/comment_test.go, comments.go, design/comments.go, work-item-comments.go, work-item-comments_test.go
Fixes https://github.com/fabric8io/fabric8-planner/issues/729
=> Pagination for comments

design/spaces.go, iteration_test.go, migration/migration.go, migration/sql-files/021-add-space-description.sql, space-iterations_test.go, space.go, space/space.go, space/space_test.go, space_test.go
Fixes #665
Adds description as an attribute to a space.
Descriptions for a space can be null.
Updated unit tests likewise.
=> Adds description to spaces.

account/user.go, iteration_test.go, search/search_repository_blackbox_test.go, search/search_repository_whitebox_test.go, search_blackbox_test.go, space-iterations_test.go, space_test.go, test/account.go, work-item-comments_test.go, work-item-link-blackbox_test.go, workitem_blackbox_test.go
Moved `TestIdentity` in `test/account_test.go` and fixed
errors on all impacted code.
Fixes #730
=> Move TestIdentity variable in the 'test' package #730

remoteworkitem/trackeritem_test.go, workitem/workitemtype_repository.go
This PR aims to fix some minor issues regarding the types used in the print calls.
=> Aligned types with the print argument calls

comments.go, configuration/configuration.go, design/search.go, iteration.go, login/service.go, login/service_blackbox_test.go, remoteworkitem/remoteworkitem_test.go, search/search_repository.go, search/search_repository_whitebox_test.go, space.go, workitem.go
https://goreportcard.com/report/github.com/almighty/almighty-core#misspell
=> Fixed typos found by "Go Report Card" service

.make/test.mk
As requested by @alexeykazakov
=> Enable dev mode during tests

remoteworkitem/tracker_repository_blackbox_test.go, remoteworkitem/trackerquery_repository_blackbox_test.go, search/search_repository_blackbox_test.go, search/search_repository_whitebox_test.go, tracker_blackbox_test.go, trackerquery_blackbox_test.go, workitem/workitem_repository_blackbox_test.go, workitemtype_blackbox_test.go
Found here:
https://goreportcard.com/report/github.com/almighty/almighty-core#ineffassign
almighty-core/tracker_blackbox_test.go
Line 22: warning: err assigned and not used (ineffassign)
almighty-core/trackerquery_blackbox_test.go
Line 28: warning: err assigned and not used (ineffassign)
almighty-core/workitemtype_blackbox_test.go
Line 298: warning: err assigned and not used (ineffassign)
almighty-core/search/search_repository_blackbox_test.go
Line 122: warning: res assigned and not used (ineffassign)
almighty-core/workitem/workitem_repository_blackbox_test.go
Line 91: warning: err assigned and not used (ineffassign)
Line 126: warning: err assigned and not used (ineffassign)
Line 141: warning: err assigned and not used (ineffassign)
Line 109: warning: err assigned and not used …
=> Fix ineffectual assignments in Go code

design/search.go, search.go, search_spaces_blackbox_test.go, space/space.go
Fixes #667 .
Adds a search API for spaces, to search for spaces having name or description that matches the search text.
=> Adds capability to search for spaces with specified search text in name or description

design/workitems.go, migration/migration.go, workitem.go, workitem/field_definition.go, workitem/fieldtype_blackbox_test.go, workitem/simple_type.go, workitem/workitemtype.go, workitem/workitemtype_repository.go, workitem_blackbox_test.go
- Filter workitem by area
- Associate a workitem with an area
Fixes #786
=> Associate a workitem with an area

main.go
related to: https://github.com/almighty/almighty-core/issues/788
=> Log request details only when the developer mode is enabled

README.adoc, config.yaml, configuration/configuration.go, main.go
related to: https://github.com/almighty/almighty-core/issues/778
=> Retry loop to connect to db and connection timeout parameter

account/doc.go, application/doc.go, area/doc.go, comment/doc.go, configuration/doc.go, design/doc.go, errors/doc.go, gormapplication/doc.go, gormsupport/doc.go, iteration/doc.go, login/doc.go, migration/doc.go, remoteworkitem/doc.go, rendering/doc.go, search/doc.go, space/doc.go, token/doc.go, workitem/doc.go, workitem/link/doc.go
related to https://github.com/almighty/almighty-core/issues/754
=> Added doc files to improve the documentation

log/log.go, log/log_test.go
Added some tests for the logging and documentation for the logging functions.
=> WIP Added tests for the logging and documentation

login/service_whitebox_test.go, main.go, test/login.go, token/token.go, token/token_test.go
Related to https://github.com/almighty/almighty-core/pull/807
=> Refactored test token generation

controller/workitem_whitebox_test.go
as discussed on chat, these tests were wrong.
=> fix wrong tests

account/identity.go, account/identity_blackbox_test.go, login/service.go
=> Workaround for Keycloak & DB unsynchronization in case the KC DB is lost

area/area_test.go
=> fix area tests needing unique space names

migration/migration.go
This is my proposal using golang text/templates due to the following comment https://github.com/almighty/almighty-core/pull/886#issuecomment-282831282
Example:
```
-- Alter the table work_item_link_types
+INSERT INTO spaces (created_at, updated_at, id, name, description) VALUES (now(),now(), '{{index . 0}}','{{index . 1}}','{{index . 2}}');
+ALTER TABLE work_item_link_types ADD space_id uuid DEFAULT '{{index . 0}}' NOT NULL;
```
Result:
```
-INSERT INTO spaces (created_at, updated_at, id, name, description) VALUES (now(),now(),'2e0698d8-753e-4cef-bb7c-f027634824a2', 'system.space', 'Initial space');
-ALTER TABLE work_item_link_types ADD space_id uuid DEFAULT '2e0698d8-753e-4cef-bb7c-f027634824a2' NOT NULL;
```
=> Pass parameters to the sql files using golang text/templates

controller/search_blackbox_test.go
As requested by @baijum , I've made this a simple PR and outsource it from my other PR.
=> Restructure search_blackbox_test.go to use test suite

cico_setup.sh
=> Use another destination for the docker push

migration/migration.go
There hasn't been any icon defined for a user story and so I've picked
the map marker icon (See here http://fontawesome.io/icon/map-marker/).
But I accidently used the wrong CSS name. This change uses the correct
CSS name.
=> User story icon was not showing

design/workitemtype.go
=> Improve documentation on "icon" of WIT

design/areas.go
=> Fix comments in area design

controller/workitem.go, controller/workitem_blackbox_test.go, design/workitems.go, migration/migration.go, workitem/workitem_repository.go, workitem/workitemtype.go
GET /api/workitems/x supports request If-Modified-Since header.
=> Expose system.updated_at and set Last-Modified header

controller/identity_blackbox_test.go, controller/login_test.go, controller/status_test.go, controller/users_blackbox_test.go
Remove dependency on global DB variable
=> Restructure tests to use suites

controller/search_blackbox_test.go, controller/search_spaces_blackbox_test.go, controller/work_item_link_blackbox_test.go, controller/work_item_link_category_blackbox_test.go, controller/work_item_link_type_blackbox_test.go, controller/workitem_blackbox_test.go, controller/workitem_whitebox_test.go, controller/workitemtype_blackbox_test.go
Remove dependency from:
search, search_spaces, work_item_link, work_item_link_category,
workitem, workitemtype
=> Remove controller tests dep on global DB instance

Makefile, controller/space_iterations_test.go, controller/work_item_children_blackbox_test.go, controller/work_item_link.go, controller/work_item_link_blackbox_test.go, controller/work_item_link_category.go, controller/work_item_link_category_blackbox_test.go, controller/work_item_link_category_whitebox_test.go, controller/work_item_link_type.go, controller/work_item_link_type_blackbox_test.go, controller/workitemtype.go, iteration/iteration.go, migration/migration.go, workitem/link/category.go, workitem/link/category_blackbox_test.go, workitem/link/category_repository.go, workitem/link/link.go, workitem/link/link_repository.go, workitem/link/link_revision_repository.go, workitem/link/link_revision_repository_blackbox_test.go, workitem/link/type.go, workitem/link/type_repository.go, workitem/workitem_repository_blackbox_test.go
moved the conversion from model to app representations in the
controllers instead of the repositories
Fixes #1043
=> Remove dependency to 'app' package in 'workitem/link' (#1043)

controller/comments_blackbox_test.go, controller/identity.go, controller/search_blackbox_test.go, controller/space.go, controller/work_item_link_blackbox_test.go, controller/work_item_link_type.go, controller/workitem.go, controller/workitem_blackbox_test.go, controller/workitem_whitebox_test.go, design/spaces.go, design/work_item_link_category.go, design/work_item_link_type.go, design/workitems.go
Many objects are missing their self links when related to work items, spaces, identities, etc...
=> Add missing Self links to objects

controller/namedspaces.go, controller/planner_backlog.go, controller/search.go, controller/space.go, controller/space_test.go, controller/work_item_link_type.go, design/spaces.go, iteration/iteration.go
=> Add meta total count property to backlog link under space api

controller/workitem.go, controller/workitem_blackbox_test.go, design/workitems.go
=> Temporarly remove support for DELETE WIT in API

controller/iteration_test.go, controller/space_iterations_test.go, controller/space_test.go, controller/workitem.go, controller/workitemtype_blackbox_test.go, design/api.go, goasupport/conditional_request/generator.go
Workaround. Should be fixed upstream
Related #1067
=> Use HTTP date format for Last-Modified and If-Last-Modified

controller/space.go, controller/space_test.go, design/spaces.go
Fixes #1031  and #1012 
New response looks like ~
```javascript
.
.
"workitems": {
"links": {
"related": "http://localhost:8080/api/spaces/2e0698d8-753e-4cef-bb7c-f027634824a2/workitems"
}
},
"workitemtypes": {
"links": {
"related": "http://localhost:8080/api/spaces/2e0698d8-753e-4cef-bb7c-f027634824a2/workitemtypes"
}
}
.
.
```
=> Added URL to list WI/WIT based on space

login/service.go
related to this bug: https://github.com/almighty/almighty-core/issues/1084
=> Collect the error of validating the token claims

configuration/configuration.go, rest/url.go, rest/url_blackbox_test.go
=> Add check for X-Forwarded-Proto to detect HTTPS

controller/workitem.go
=> Remove custom Request creation in WIT Link

account/identity_blackbox_test.go, account/user_blackbox_test.go, auth/state_blackbox_test.go, comment/comment_repository_blackbox_test.go, comment/comment_revision_repository_blackbox_test.go, controller/planner_backlog_blackbox_test.go, controller/search_blackbox_test.go, controller/space_iterations_test.go, controller/work_item_children_blackbox_test.go, controller/work_item_link_category_blackbox_test.go, controller/work_item_link_type_blackbox_test.go, controller/workitem_blackbox_test.go, controller/workitemtype_blackbox_test.go, gormtestsupport/db_test_suite.go, login/service_blackbox_test.go, remoteworkitem/tracker_repository_blackbox_test.go, remoteworkitem/trackerquery_repository_blackbox_test.go, search/search_repository_blackbox_test.go, search/search_repository_whitebox_test.go, workitem/link/link_revision_repository_blackbox_test.go, workitem/workitem_repository_blackbox_test.go, workitem/workitem_revision_repository_blackbox_test.go, workitem/workitemtype_repository_blackbox_test.go
related to: https://github.com/almighty/almighty-core/issues/1063
=> Populate the DB as part of the test suite 

.make/docker-compose.integration-test.yaml, .make/test.mk, cico_setup.sh
related to: https://github.com/almighty/almighty-core/issues/1082
```
Creating make_postgres_integration_test_1
+ trap cleanup_env EXIT
+ make docker-test-migration
docker exec -t -i "almighty-core-local-build" bash -ec 'export ALMIGHTY_POSTGRES_HOST=172.17.0.3; make test-migration'
ALMIGHTY_RESOURCE_DATABASE=1 go test github.com/almighty/almighty-core/migration -v
=== RUN   TestConcurrentMigrations
--- FAIL: TestConcurrentMigrations (0.00s)
assertions.go:241: 
Error Trace:	migration_test.go:36
asm_amd64.s:2086
Error:		Expected nil, but got: Failed to start transaction: dial tcp 172.17.0.3:5432: getsockopt: connection refused
assertions.go:241: 
```
=> [RFC] Check if postgresql is healthy to continue with the tests

controller/comments.go, controller/comments_blackbox_test.go, design/comments.go
=> Add creator with link to identity

controller/work_item_link_blackbox_test.go
=> Ensure that system.space is not removed during tests

controller/planner_backlog.go, controller/planner_backlog_blackbox_test.go, controller/planner_backlog_test.go, controller/space.go, test/work_item_repository.go, workitem/workitem_repository.go
related to: https://github.com/almighty/almighty-core/issues/1075
=> Get count of backlog items for space controller

controller/space_areas_blackbox_test.go
=> Bug in space areas test (#1125)

config.yaml, configuration/configuration.go, controller/area_blackbox_test.go, controller/filter.go, controller/filters_blackbox_test.go, main.go
=> Add conditional requests and cache-control headers on the 'filters' endpoints (#1138)

controller/space.go, controller/space_test.go, design/spaces.go
Fixes https://github.com/fabric8io/fabric8-planner/issues/1569
=> Add filters API end point to spaces

gormsupport/cleaner/db_clean.go
=> cleaner.DeleteCreatedEntities: Only create tx if not already in one	

.gitignore, .make/docker-compose.integration-test.yaml, Makefile, main.go, migration/migration.go, migration/migration_blackbox_test.go, migration/migration_test.go, migration/sql-test-files/044-insert-test-data.sql, migration/sql-test-files/045-update-work-items.sql, migration/sql-test-files/046-insert-oauth-states.sql, migration/sql-test-files/047-insert-codebases.sql, migration/sql-test-files/048-unique-idx-failed-insert.sql, migration/sql-test-files/050-users-add-column-company.sql
Related to: https://github.com/almighty/almighty-core/issues/1063
=> Improve the migration tests

cico_setup.sh
This adds image tagging with commit hash to version images pushed to registry. Latest also stay sthere
=> Add commit tagging for images

login/service.go
This is a temporary thing. Just to get very detailed logs for login requests. To debug the current login problem.
=> Added logs to debug login problems

controller/login.go, controller/login_test.go, login/profile.go, login/service.go, login/service_blackbox_test.go, login/service_whitebox_test.go
Only users with "approved" attribute in the Keyclaok account will be logged in and created in the core DB.
DO NOT MERGE YET.
Still waiting for OSO side to populate our KC.
Fixes https://github.com/almighty/almighty-core/issues/933
=> WIP Login only approved users

controller/space.go
If the space creation failed we should not create space resources in Keyclaok. Otherwise we will leak resources.
Fixes https://github.com/almighty/almighty-core/issues/1180
=> Create KC resource only when space created

openshift/core.app.yaml
This fixes `oc apply` failures
=> Fix validity issues

log/log.go, migration/migration.go
related to: https://github.com/almighty/almighty-core/issues/849
=> Set log level for the tests

controller/workitem.go, controller/workitem_blackbox_test.go
1. Any user should be able to create a WI in any space
2. Only WI creator and space collaborators should be able to edit the WI
(WI links, comments, etc are out of the scope of this PR)
Fixes https://github.com/almighty/almighty-core/issues/1204
=> Allow any logged-in user to create Work Items 

main.go
related to https://github.com/almighty/almighty-core/issues/1208
=> Check if the log level is debug to enable debug mode for the db

controller/workitem.go
Fixes https://github.com/almighty/almighty-core/issues/1207
=> Avoid loading WI for auth only for so to load Wi to change it

login/service.go
=> Minor clean up in logs

area/area.go, controller/area_blackbox_test.go, controller/space_areas_blackbox_test.go, controller/workitem.go, controller/workitem_blackbox_test.go, controller/workitem_whitebox_test.go, migration/migration.go, migration/sql-files/055-assign-root-area-if-missing.sql
=> If workitem area is PATCH'ed as nil, set it to root area (#1186)

login/profile.go
Fixes https://github.com/almighty/almighty-core/issues/1159
=> Use lower case for user profile attributes in keycloak

auth/authz.go, auth/authz_blackbox_test.go, design/auth.go, login/service.go, login/service_whitebox_test.go
=> Fix parsing tokens with long lifespan

controller/login.go, controller/login_test.go, controller/logout.go, controller/logout_test.go
related to: https://github.com/fabric8io/fabric8-ui/issues/886#issuecomment-296339218
I am not sure if we need to add to the other operations of the login controller. :-/
=> Added no cache header to login/logout operations

codebase/che/client.go, codebase/codebase.go, codebase/codebase_test.go, controller/codebase.go, controller/codebase_blackbox_test.go, design/codebases.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/057-add-last-used-workspace-to-codebase.sql, migration/sql-test-files/057-add-last-used-workspace-to-codebase.sql
We need to expose in the rest API of codebases the workspace name. We store the last used workspace name extracted from che client.
=> Add last used workspace name property

controller/collaborators.go, controller/collaborators_test.go
Fixes https://github.com/almighty/almighty-core/issues/1252
=> Fix add/remove multiple collaborators

controller/area_blackbox_test.go, controller/planner_backlog_blackbox_test.go, controller/planner_backlog_test.go, controller/space_areas.go, controller/space_iterations.go, controller/users.go, controller/users_blackbox_test.go, controller/workitem_blackbox_test.go, controller/workitemtype.go, goasupport/conditional_request/generator.go, gormsupport/cleaner/db_clean.go, gormtestsupport/db_test_suite.go, gormtestsupport/remote_test_suite.go, jsonapi/jsonapi_utility.go, main.go, test/account.go, workitem/link/link_repository.go, workitem/workitem.go, workitem/workitemtype_repository.go
We are using logrus in many places where we should use our logging package
=> Removed references to logrus and replaced by calls to our log functions

controller/space.go, controller/space_test.go, design/spaces.go, errors/errors.go, errors/errors_blackbox_test.go, jsonapi/jsonapi_utility.go, jsonapi/jsonapi_utility_blackbox_test.go
Fixes https://github.com/almighty/almighty-core/issues/1290
=> Only space owner should be able to delete a space

Dockerfile.builder, Dockerfile.deploy
I wanted to get rid of my personal email address in the dockerfiles
=> Replace my personal email address with a more public one

goasupport/conditional_request/generator.go
=> Improve function comments in generated code about condition requests (#1271)

auth/authz.go, controller/login.go, login/service.go
=> Close HTTP responces

migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/060-fixed-identities-username-idx.sql
related to: https://github.com/almighty/almighty-core/issues/1321
=> Fixed index to be case insensitive

controller/login.go
related to https://github.com/almighty/almighty-core/issues/1257
=> Return 401 error when the Keycloak refresh operation returns 400

controller/collaborators.go, controller/collaborators_blackbox_test.go
Fixes https://github.com/almighty/almighty-core/issues/1344
=> Fix collaborators paging

controller/iteration.go, controller/iteration_test.go, design/iterations.go
Partial fix of #1299 (comment)
Updated/added tests.
=> Only space owner can create child & update iterations.

controller/workitem.go, controller/workitem_whitebox_test.go
related to https://github.com/almighty/almighty-core/issues/1343
=> Removed duplicated root calls when creating a workitem

controller/area.go, controller/area_blackbox_test.go, controller/space_areas_blackbox_test.go, design/areas.go
partial fix for #https://github.com/almighty/almighty-core/issues/1299
tests updated/ added as needed.
=> Only space owner can create a child area.

migration/migration.go, workitem/workitem_repository.go
=> Sql formatting

auth/authz.go, auth/authz_blackbox_test.go, space/authz/authz.go, space/authz/authz_test.go, test/login.go
=> Better KC test resource cleanup

controller/space_codebases.go, controller/space_codebases_test.go, design/codebases.go
Only the space owner should be able to create a codebase.
Part of https://github.com/almighty/almighty-core/issues/1299
=> Secure codebase API

test/account.go
This new function can be used to create Spaces (and other objects) in our tests with OwnerID pre-defined in golden files.
As @kwk requested :)
The workflow would be:
1. Create a test identity with pre-defined ID equaled to the ID from the golden file.
2. Create a context with that identity.
3. Create a space using that context.
4. Compare the result with the golden file.
5. PROFIT
=> New function to create Identity with pre-defined ID (to be used in tests)

controller/comments.go
Load work item only if logged in user is not the creator.
=> small optimization in delete comment API

workitem/link/link_repository.go, workitem/link/link_repository_blackbox_test.go
Ready for review now that #1411 is fixed.
=> Do not count existing link(s) when validating topology during link update #1412

controller/search.go, controller/work_item_link.go, controller/work_item_link_blackbox_test.go, controller/work_item_link_category.go, controller/work_item_link_category_blackbox_test.go, controller/work_item_link_type.go, controller/work_item_relationships_links.go, controller/workitem.go, controller/workitem_whitebox_test.go
As @hectorj2f suggested a while ago, we should remove those checks.
=> Remove some nil checks from NewXYCtrl fns

controller/workitem.go, controller/workitem_blackbox_test.go, design/workitems.go
Fixes https://github.com/almighty/almighty-core/issues/1358
=> Only space collaborator should be able to create a work item

controller/codebase.go, controller/codebase_blackbox_test.go, controller/test-files/codebase/show/ok_without_stackId.golden.json
=> fix(codebase): cb.stackId can be nil

application/transaction_test.go
=> Fix almighty-core -> fabric8-wit packages in transaction tests

migration/migration.go
I missed to add the if statement in the code so we always print the default case.
=> Added if statement to check if error is nil

area/area.go, codebase/codebase.go, comment/comment.go, comment/comment_repository.go, space/space.go
Fixes #1493
See also http://jinzhu.me/gorm/models.html#table-name-is-the-pluralized-version-of-struct-name
=> fix(database): move TableName() from repo to model

log/context.go
=> Remove TokenManager as req to log identity_id

login/logout.go, login/service.go, space/authz/authz.go
Fixes https://github.com/fabric8-services/fabric8-wit/issues/1498
=> Log variable names should use _ not -

controller/search.go, controller/search_blackbox_test.go, controller/test-files/search/show/bad_expression_missing_curly_brace.error.golden.json, controller/test-files/search/show/bad_expression_missing_curly_brace.headers.golden.json, controller/workitemtype_blackbox_test.go, search/search_repository.go
=> Fix error messages for search controller

controller/workitemtype.go, controller/workitemtype_blackbox_test.go, design/workitemtype.go
Related https://github.com/fabric8-services/fabric8-wit/issues/1299
=> Only space owner should be able to create Work Item Type

controller/login.go
=> Better logging when token generation fails

controller/search.go, controller/search_blackbox_test.go, search/search_repository.go
related to: https://github.com/fabric8-services/fabric8-wit/issues/1524
=> Check for nil arguments and throw errors in such a case

Makefile
Fixes https://github.com/fabric8-services/fabric8-wit/issues/1534
=> Fix controller generation with correct `app` path

Makefile, configuration/configuration.go, controller/comments.go, controller/comments_blackbox_test.go, controller/work_item_comments.go, controller/work_item_comments_blackbox_test.go, controller/workitem.go, controller/workitem_blackbox_test.go, controller/workitems.go, glide.lock, glide.yaml, main.go, notification/notification.go, openshift/core.app.yaml, openshift/core.config.yaml, test/notification.go
* create|update workitem|comment
Fixes #1488
=> Call notification service on given events

controller/search_blackbox_test.go, search/query_language_whitebox_test.go, search/search_repository.go
=> Support explicit $EQ, $NE

controller/search_blackbox_test.go, search/search_repository.go
=> 'workitemtype' alias to 'type' in query language

README.adoc
Adding info about prod preview & che-starter setup
=> Adding info about prod preview & che-starter setup to README.adoc

glide.lock, glide.yaml
=> Remove unused dependency: `bitbucket.org/pkg/inflect` (#1562)

cico_setup.sh
With registry.devshift.net we need to secure push actions - this PR enables that
=> Use push.registry.devshift.net

controller/users.go
I thought user max-age was properly set for the show operation in the user controller.
Good catch @aslakknutsen
=> Use single resource max-age when showing an user data

.make/check_gopath.go
there are some compiling issues in check_path.go
=> Fixed compiling issues

workitem/expression_compiler.go, workitem/expression_compiler_blackbox_test.go
=> JSON field name must contain dot(period) character

cico_setup.sh
Use the pre-defined size for the docker image tag
=> Use DEVSHIFT_TAG_LEN to define the tag size

Makefile
related to: https://github.com/fabric8-services/fabric8-wit/issues/1576
=> Generate junit file and run tests prior any release

account/init_tenant.go, controller/user_service.go, design/user_service.go, glide.lock, main.go
Related to fabric8-services/fabric8-tenant#75
=> Expose Clean tenant endpoint as part of user/service

controller/space.go, controller/space_blackbox_test.go, design/spaces.go, workitem/typegroup/typegroup.go
Added List WITG URL in space response.
Renamed "Execution" to "Iterations" for display only.
Tests are updated.
=> Add "WITypegroup" URL in space links

controller/search_blackbox_test.go, controller/test-files/search/show/non_existing_key.error.golden.json, controller/test-files/search/show/non_existing_key.headers.golden.json, search/query_language_whitebox_test.go, search/search_repository.go
=> Handle query expressions with non-existing keys

controller/codebase.go, main.go
Related to openshiftio/openshift.io#619
=> Resolve che namespace from tenant service 

.gitignore, Makefile, auth/policy.go, auth/resource.go, config.yaml, configuration/configuration.go, configuration/configuration_blackbox_test.go, configuration/configuration_whitebox_test.go, controller/collaborators.go, controller/collaborators_blackbox_test.go, controller/space.go, controller/space_blackbox_test.go, glide.lock, glide.yaml, main.go, space/authz/authz.go, space/authz/authz_test.go
This PR covers the WIT part of https://github.com/fabric8-services/fabric8-auth/issues/27
=> Delegate Keycloak Resource creation to Auth service

controller/search_blackbox_test.go, controller/test-files/search/show/assignee_null_negate.error.golden.json, controller/test-files/search/show/assignee_null_negate.headers.golden.json, search/query_language_whitebox_test.go, search/search_repository.go
=> Support for issues assigned to nobody

controller/space.go
If space resource is not found when a space is being removed then we should remove the space anyway.
It can happen to old spaces if Keycloak failed to create a space resource for some reason during space creation.
New spaces won't be created if the space resource wasn't created but we have to ignore this errors for old spaces.
Ref: https://github.com/openshiftio/openshift.io/issues/651
=> Delete space even if corresponding space resource not found

Jenkinsfile
after a new release version lets raise a PR against fabric8-platform so it gets included in the next fabric8 release
=> lets PR fabric8-platform on each release

controller/space.go
We should not just ignore such error but actually force space removal anyway
=> Delete space even if no space resource found

migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/073-labels.sql, migration/sql-test-files/048-unique-idx-failed-insert.sql, migration/sql-test-files/073-label-color-code.sql, migration/sql-test-files/073-label-color-code2.sql, migration/sql-test-files/073-label-empty-name.sql, migration/sql-test-files/073-label-same-name.sql
=> Adds database schema for labels

controller/space.go, controller/space_blackbox_test.go, design/spaces.go
=> Adds link to Labels in Space response

label/label.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/075-label-unique-name.sql
The uniqueness should consider `deleted_at` column
=> Use unique index instead of constraint

iteration/iteration_test.go
=> Removes unnecessary UserActive field from iteration tests

application/application_db_calls_bench_test.go, application/transaction_bench_test.go, codebase/codebase_bench_test.go, comment/comment_repository_blackbox_bench_test.go, controller/planner_backlog_bench_test.go, controller/planner_backlog_blackbox_bench_test.go, gormtestsupport/benchmark/db_bench_suite.go, workitem/workitem_repository_bench_test.go, workitem/workitemtype_repository_bench_test.go
This is the same as #1645 but this time for benchmarks instead of tests.
=> simplify-dbbench-suite

controller/user.go, controller/user_test.go, design/account.go
Fixes https://github.com/openshiftio/openshift.io/issues/1036
=> Proxy /user to Auth instead of redirect

area/area.go, controller/workitem_blackbox_test.go, test/testfixture/customize_entity_callbacks.go, test/testfixture/environments.go, test/testfixture/make_functions.go, test/testfixture/testfixture_test.go
A collaborative effort with @pranavgore09 (did pair programming), @xcoulon (brain storming) and @aslakknutsen (initial idea)
=> Added CreateWorkItemEnvironment()

Jenkinsfile
=> WIP: Attempt to fix #1678

controller/golden_files_test.go
I've added compareWithGoldenUUIDAgnostic() with the same signature as
the compareWithGolden() function. Documentation and tests are included.
=> Make golden-files UUID agnostic (optionally)

controller/work_item_link_type.go, test/testfixture/customize_entity_funcs.go, test/testfixture/recipe_funcs.go, test/testfixture/testfixture_test.go, workitem/link/link_repository_blackbox_test.go, workitem/link/topology.go, workitem/link/type.go, workitem/link/type_blackbox_test.go
=> Make link topology a type based on string

search/search_repository_whitebox_test.go
Update TestSearch - By Number
Add "not found" case for when searching by space and not by space.
Added case with single and multiple results for when searching by number without a space.
=> Added "not found" cases for search by number

controller/filter.go, controller/test-files/filter/list/list_available_filters.golden.json
=> Use just `state` instead of `workitemstate`

controller/search_blackbox_test.go, search/query_language_whitebox_test.go, search/search_repository.go
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1627
=> Support $EQ syntax for null value

design/user_types.go
* Removes `CreateTrackerPayload` and `UpdateTrackerPayload` from `user_types` which is not required now.
=> Removes unnecessary tracker payload

controller/login.go
Added error logs for if it fails to create or update keycloak user
Fixes https://github.com/fabric8-services/fabric8-wit/issues/1739
=> Added error logs for if it fails to create or update keycloak user

controller/users.go, token/token.go, token/token_test.go
- Modified isServiceAccount(ctx) method to accept other services and not just "fabric8-auth" by adding a parameter for service name, 
- modifies tests according to changes made 
(#1764)
=> Parameterised isServiceAccount(ctx) method

README.adoc
Always mention the elephant in the room; especially when its pink and weighs 18T.
=> Explain what WIT is

controller/named_work_items.go, controller/named_work_items_blackbox_test.go, design/workitems.go
fixes https://github.com/openshiftio/openshift.io/issues/1219
fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1672
=> Temporary instead of permanent redirect for fetching WI by number

codebase/che/client.go, controller/codebase.go, design/codebases.go
* What issues does it solve? #1788 
Adding info about che-server type (single-tenant / multi-tenant)
Related che-starter PR https://github.com/redhat-developer/che-starter/pull/247
=> wit #1788: Adding MultiTenant info to CheServerState

controller/space_template.go, controller/test-files/work_item_type_group/list/ok.witg.golden.json, controller/test-files/work_item_type_group/show/ok.witg.golden.json, controller/work_item_type_group.go, design/work_item_type_group.go
I've just added a `SpaceTemplate` relation to the work item type group.
=> Added SpaceTemplate relation to work item type group response

controller/test-files/work_item_type_group/list/ok.witg.golden.json, controller/test-files/work_item_type_group/show/ok.witg.golden.json, controller/work_item_type_group.go, design/work_item_type_group.go
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1752
=> Add "show-in-sidebar" to work item type group response

glide.lock
Path to Import path changed from `github.com/Sirupsen/logrus` to `github.com/sirupsen/logrus`
=> increment prometheus/common to fix logrus

glide.lock, glide.yaml
=> include kingpin - a dependency for prometheus

configuration/configuration.go, openshift/core.config.yaml
=> endpoint in WIT to proxy requests to toggles-service - fix example ConfigMap (#OSIO1796)

design/featuretoggles.go
Fixes openshiftio/openshift.io#1871
=> Fix controller mount in `core` (#OSIO1871)

controller/test-files/work_item_type_group/list/ok.witg.golden.json, controller/test-files/work_item_type_group/show/ok.witg.golden.json, migration/migration.go, workitem/typegroup.go
Update icon for group type as per the below VD
https://redhat.invisionapp.com/share/NVEWGDU4W#/screens/269980285/
=> fix(grouptype-icon): update icon for group types

search/query_language_whitebox_test.go
=> test cases for multiple values with AND & OR

account/init_tenant.go, auth/resource.go, codebase/che/client.go, controller/user.go, rest/url.go
=> Ensure HTTP Responses are read and closed to avoid FD leak

configuration/configuration.go, glide.lock, glide.yaml, main.go, openshift/core.app.yaml
=> Enable diagnostic options for goroutines/stack/cpu/mem/profile

controller/search.go, controller/test-files/search/show/in_topology_A-B-C-D_and_B-E_search_for_B_and_C/include_children.res.payload.golden.json, controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B,C_with_tree-view=true.res.golden.json, controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/B_with_tree-view=true.res.golden.json, controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/C_with_tree-view=true.res.golden.json, controller/test-files/search/show/in_topology_A-B-C_and_A-D_search_for/D_with_tree-view=true.res.golden.json
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1876
=> include hasChildren attribute in meta section

controller/codebase.go, design/codebases.go
Adding separate attribute with workspace status
https://github.com/openshiftio/openshift.io/issues/1439 - `ability to handle workspace statuses`
=> wit #1439: Adding separate attribute with workspace status

controller/area_blackbox_test.go, controller/iteration_blackbox_test.go, controller/space_blackbox_test.go, controller/test-files/work_item_type/validate/invalid_oversized_name.golden.json, controller/work_item_link_category_blackbox_test.go, design/resources.go, test/common.go
Changed Name (for multiple entities) Max Length validation from 62 to 63
Fix issue: https://github.com/openshiftio/openshift.io/issues/1869
=> Fix issue: 1869 - Failed to create space with max character length (63 chars)

workitem/workitem_repository.go
when fetching the top or bottom work item for example
=> Add error checking in reorder functions

Makefile
Show the Go version that is used in build
=> Show go info in the log

controller/codebase.go, design/codebases.go
Adding possibility to send 'branch' info during workspace creation
Adding Project information (location / branch) to workspace model
* What issues does it solve? 
https://github.com/openshiftio/openshift.io/issues/1439
=> openshift.io #1439: Adding possibility to send 'branch' info during workspace creation

config.yaml, configuration/configuration.go, configuration/configuration_blackbox_test.go, configuration/configuration_whitebox_test.go, controller/deployments.go
Feature for: https://github.com/openshiftio/openshift.io/issues/2665 (parent: https://github.com/openshiftio/openshift.io/issues/2664)
=> Added config field for deployments timeout

controller/space_iterations.go, controller/space_iterations_test.go, ptr/ptr.go
Fixes https://github.com/openshiftio/openshift.io/issues/1791
=> Save Create Iteration with Force Active

id/slice.go, id/slice_blackbox_test.go
=> Add id.Slice.ToMap and id.Slice.ToStringSlice

controller/json_api_compliance_test.go
=> Only log JSON API compliance errors when not valid

controller/iteration_blackbox_test.go, controller/workitem_blackbox_test.go
=> Refactor iteration test func createSpaceAndRootAreaAndIterations

application/repository/exister.go
=> Fix comment on repository.Exister.CheckExists

migration/migration.go
This should fix this error:
`sql: Scan error on column index 6: failed to convert any '<nil>' to kind: kind is not a string value <nil>`
=> fix for: sql: Scan error on column index 6: failed to convert any '<nil>' to kind: kind is not a string value <nil>

.gitignore, .make/Makefile.lnx, .make/Makefile.win, Dockerfile.builder, Makefile
=> Remove build dependency on `hg`/`mercurial` (#2023)

Gopkg.lock, Gopkg.toml, Makefile
Until https://github.com/golang/go/issues/25048 is resolved.
See also https://github.com/golang/lint/issues/397
=> Temporarily disable golint

controller/deployments.go, controller/deployments_blackbox_test.go
May not be directly linked to the issue, but returning
errors result in a response status code with a `0` value.
=> Deployments page returns 401 errors (OSIO#3290)

controller/test-files/work_item_link/create/link_cycle_detected.res.headers.golden.json, controller/test-files/work_item_link/create/link_cycle_detected.res.payload.golden.json, controller/work_item_link_blackbox_test.go, workitem/link/link_repository.go
Fixes https://github.com/openshiftio/openshift.io/issues/2864
=> data conflict (409) on link cycle detection instead internal server error (500)

Gopkg.lock, Gopkg.toml, Makefile
This reverts commit ac2f7333343955343fc858e630416c65c624b9f5.
fixes #2041
=> Revert "Temporarily disable golint (#2040)"

Gopkg.lock, controller/test-files/work_item_type/list/ok_base.res.payload.golden.json, controller/test-files/work_item_type/list/ok_legacy.res.payload.golden.json, controller/test-files/work_item_type/list/ok_scrum.res.payload.golden.json, controller/workitemtypes_blackbox_test.go
=> Make test for listing WITs of predefined space templates aware of IDs

.gitignore
Possible cause of commit in Status API show up as xxx-dirty
=> Add .cico-prepare to gitignore

controller/space.go
=> Add log when OpenShift resource deletion failed

account/init_tenant.go, account/init_tenant_test.go, errors/errors.go, test/data/account/delete_tenant.yaml
Expected response code is `204`, not `200`
Fixes openshiftio/openshift.io#3526
=> Fix for "url.Error: Delete http://f8tenant:80/api/tenant?remove=false: EOF"

controller/deployments.go, controller/deployments_blackbox_test.go, controller/deployments_urlprovider.go, design/deployments.go, kubernetes/deployments_kubeclient.go, kubernetes/deployments_kubeclient_blackbox_test.go, test/kubernetes/deletedeployment-delete-dc-error.yaml, test/kubernetes/deletedeployment-delete-routes-error.yaml, test/kubernetes/deletedeployment-delete-svc-error.yaml, test/kubernetes/deletedeployment-get-dc-error.yaml, test/kubernetes/deletedeployment-get-routes-error.yaml, test/kubernetes/deletedeployment-get-svc-error.yaml, test/kubernetes/getdeployment-build-error.yaml, test/kubernetes/getdeployment-dc-error.yaml, test/kubernetes/getdeployment-pod-error.yaml, test/kubernetes/getdeployment-rc-error.yaml, test/kubernetes/getdeployment-route-error.yaml, test/kubernetes/getdeployment-svc-error.yaml, test/kubernetes/getenvironments-rq-error.yaml, test/kubernetes/getspace-bc-error.yaml, test/kubernetes/newkubeclient-statuserror.yaml, test/kubernetes/scaledeployment-get-error.yaml, test/kubernetes/scaledeployment-put-error.yaml
This PR enriches errors returned from deployments_kubeclient.go with _Status_ information returned by OpenShift. _Status_ is a Kubernetes API object detailing the result of an operation, like the following:
```json
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "some error",
"reason": "BadRequest",
"code": 400
}
```
This allows us to return more informative error messages and also pass through select HTTP status codes in the response. This PR changes our API to return 400 - Bad Request and 404 - Not Found when a corresponding OpenShift call does so.
Error before PR:
```
$ curl -H "Authorization: Bearer $MY_TOKEN" http://localhost:8080/api/deployments/spaces/$SPACE
{"errors":[{"code":"internal_error","detail":"could not retrieve space testspace: …
```
=> Check for Status errors from OpenShift and convert to appropriate errors

controller/filter.go, controller/test-files/filter/list/list_available_filters.golden.json
See openshiftio/openshift.io#2972
=> Change title and description of WIT filter

controller/work_item_labels_blackbox_test.go
Fixes https://github.com/fabric8-services/fabric8-wit/issues/2128
=> TestRunWorkItemLabelREST: Delete test artifacts

codebase/codebase.go, codebase/codebase_test.go, controller/codebase.go, controller/codebase_blackbox_test.go, controller/space_codebases.go, controller/space_codebases_test.go, controller/test-files/codebase/show/ok_with_stackId.golden.json, controller/test-files/codebase/show/ok_without_auth.golden.json, controller/test-files/codebase/show/ok_without_stackId.golden.json, controller/test-files/search/search_codebase_per_url_multi_match.json, controller/test-files/search/search_codebase_per_url_single_match.json, design/codebases.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/093-codebase-add-cve-scan.sql, migration/sql-test-files/093-codebases-add-cve-scan-cleanup.sql, migration/sql-test-files/093-codebases-add-cve-scan-setup.sql, migration/sql-test-files/093-codebases-add-cve-scan-with.sql, migration/sql-test-files/093-codebases-add-cve-scan-with2.sql, migration/sql-test-files/093-codebases-add-cve-scan-without.sql, test/testfixture/make_functions.go
This attribute `cve-scan` will tell whether to enable CVE scan from the
analytics service for this particular codebase repository.
=> Add bool attribute cve-scan to codebase

controller/work_item_comments_blackbox_test.go
Fixes https://github.com/fabric8-services/fabric8-wit/issues/2155
=> WI_comments_blackbox_test: Delete test entities after each test

test/testfixture/make_functions.go, workitem/workitemtype_repository.go
Allow work items to be created from a given model an not only from a given set of arguments.
=> Added workitem.GormWorkItemTypeRepository.CreateFromModel

config.yaml
Fixes openshiftio/openshift.io#4125
=> Update OSO Proxy URL to external route name

controller/test-files/event/list/ok-area.res.payload.golden.json, controller/test-files/event/list/ok-assignees.res.payload.golden.json, controller/test-files/event/list/ok-description.res.payload.golden.json, controller/test-files/event/list/ok-iteration.res.payload.golden.json, controller/test-files/event/list/ok-kindFloat.res.payload.golden.json, controller/test-files/event/list/ok-kindInt.res.payload.golden.json, controller/test-files/event/list/ok-labels.res.payload.golden.json, controller/test-files/event/list/ok-state.res.payload.golden.json, controller/test-files/event/list/ok-title.res.payload.golden.json, controller/test-files/event/list/ok.bool_list.res.payload.golden.json, controller/test-files/event/list/ok.bool_single.res.payload.golden.json, controller/test-files/event/list/ok.float_list.res.payload.golden.json, controller/test-files/event/list/ok.float_single.res.payload.golden.json, controller/test-files/event/list/ok.integer_list.res.payload.golden.json, controller/test-files/event/list/ok.integer_single.res.payload.golden.json, controller/test-files/event/list/ok.markup_list.res.payload.golden.json, controller/test-files/event/list/ok.markup_single.res.payload.golden.json, controller/test-files/event/list/ok.string_list.res.payload.golden.json, controller/test-files/event/list/ok.string_single.res.payload.golden.json, controller/test-files/event/list/ok.url_list.res.payload.golden.json, controller/test-files/event/list/ok.url_single.res.payload.golden.json
This commit contains only the golden files for what has been changed in https://github.com/fabric8-services/fabric8-wit/pull/2212. Please see that PR if you want to know what the code for these changes look like.
=> Event cleanup (golden files)

controller/test-files/work_item_link_type/list/ok.agile.res.headers.golden.json, controller/test-files/work_item_link_type/list/ok.agile.res.payload.golden.json, controller/test-files/work_item_link_type/list/ok.base.res.headers.golden.json, controller/test-files/work_item_link_type/list/ok.base.res.payload.golden.json, controller/test-files/work_item_link_type/list/ok.legacy.res.headers.golden.json, controller/test-files/work_item_link_type/list/ok.legacy.res.payload.golden.json, controller/test-files/work_item_link_type/list/ok.scrum.res.headers.golden.json, controller/test-files/work_item_link_type/list/ok.scrum.res.payload.golden.json, controller/work_item_link_types_blackbox_test.go, design/work_item_link_type.go, workitem/link/category.go, workitem/link/type.go
This adds a golden file for the payload and response of all work item link types defined in all space templates.
=> Add golden files for all work item link types of all space templates

migration/migration.go, migration/sql-files/100-drop-userspace-data.sql
Fixing migration 100 to be consistent with all the other migrations
=> fixing migration 100 to be consistent with others

migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/103-user-email-notnull-notempty.sql, migration/sql-test-files/103-user-email-notnull-notempty.sql
Fixes https://github.com/fabric8-services/fabric8-wit/issues/2237
=> Add NotNull and NotEmpty constraint on Users.email column

id/slice.go, id/slice_blackbox_test.go
Adds `func (s Slice) Contains(v uuid.UUID) bool`.
=> Add id.Slice.Contains with tests

openshift/core.app.yaml
=> Double the amount of allowed time for a pod to be ready

openshift/core.app.yaml
from 120 seconds to now 1200 seconds
See #2291
=> 10x the amount of allowed time for a pod to be ready

openshift/core.app.yaml
See https://github.com/fabric8-services/fabric8-wit/issues/2291
=> Increase deployment timeout to 2X

controller/trackerquery.go, controller/trackerquery_blackbox_test.go, design/tracker_queries.go, remoteworkitem/trackerquery_repository.go, remoteworkitem/trackerquery_repository_test.go
This pr removes update action from trackerquery
=> removes update trackerquery action

controller/trackerquery_blackbox_test.go
Adds missing tests for delete trackerquery on controller level
=> adds tests for delete trackerquery on controller level

controller/trackerquery_blackbox_test.go, test/testfixture/recipe_funcs.go
=> Adds Space, WorkItemType, Tracker dependency in TrackerQuery test

controller/search_blackbox_test.go
=> Adds test for a non-existing tracker query ID

controller/logout.go, controller/test-files/endpoints/list/ok.res.payload.golden.json, design/auth.go
Related to https://github.com/openshiftio/openshift.io/issues/4757
=> Proxy /logout/v2 to Auth service

design/account.go
=> Add security constraint in design for user deletion and obfuscation

openshift/core.app.yaml
=> Fix cpu format
